### ISSUE TITLE
VS. KAPI (New Update/Optimized/Lite/no dialogue)

### ISSUE THREAD

**Issue by FridayNightSans** [luckydog7/Funkin-android#1034]
Lmao, im just porting this after 2 days and it got a new update :v. Meh, im updated. Go check.
NOTE!!!: Cause this custom week port only have   3 songs so i change Wocky into Monster song. If u like to play Wocky then play Monster lmao)
Link (lmao im upload on Mega now):
...
Credits (lmao, score help me credits)
![Screenshot_20210529-171625](https://user-images.githubusercontent.com/81144896/120066801-5f3cff00-c0a2-11eb-93ad-d9f37d0e72fc.png)
Menu Character
![Screenshot_20210529-171643](https://user-images.githubusercontent.com/81144896/120066810-682dd080-c0a2-11eb-8d3a-2f1d2b4cf188.png)
BEATHOVEN
![Screenshot_20210529-171534](https://user-images.githubusercontent.com/81144896/120066849-a0351380-c0a2-11eb-9833-6ba940456311.png)
(I forgot tha name lmao)
Hairball
![Screenshot_20210529-171303](https://user-images.githubusercontent.com/81144896/120066863-b642d400-c0a2-11eb-970d-873a7a2bc95b.png)

**Comment by zLegend77** [comment]
😻❤

**Comment by FridayNightSans** [comment]
No more
