### ISSUE TITLE
Can u port kapi mod new update to mobile 

### ISSUE THREAD

**Issue by TankPain** [luckydog7/Funkin-android#1036]
Please :3

**Comment by Kaique62** [comment]
> Please :3

I ported it yesterday maybe have some bugs have all kapi songs

![Screenshot_20210529-111704](https://user-images.githubusercontent.com/81991014/120073630-8f1edf00-c06f-11eb-95e7-f7f325167ccb.png)

Download: https://www.mediafire.com/file/a6cp3pwp6896v1h/VS_Kapi_By_Kaique62.apk/file
![Screenshot_20210529-075054](https://user-images.githubusercontent.com/81991014/120073625-8cbc8500-c06f-11eb-89f0-9f643cc784cd.png)
![Screenshot_20210529-111658](https://user-images.githubusercontent.com/81991014/120073626-8dedb200-c06f-11eb-8f09-da5e18a4dcbe.png)
![Screenshot_20210529-111642](https://user-images.githubusercontent.com/81991014/120073627-8e864880-c06f-11eb-9a02-cd10b602d14d.png)
-I deleted all other weeks songs and characters

**Comment by TankPain** [comment]
Oh thanks
