### ISSUE TITLE
Error with compiling the game 

### ISSUE THREAD

**Issue by AnUnkownSkeleton** [luckydog7/Funkin-android#1043]
i get this error in the terminal when i try to run

![image](https://user-images.githubusercontent.com/75160111/120083505-5b9b7f00-c086-11eb-872a-28024c776605.png)

is it because i didnt copy the lib folder because i couldnt find it

**Comment by Kaique62** [comment]
> i get this error in the terminal when i try to run
> 
> ![image](https://user-images.githubusercontent.com/75160111/120083505-5b9b7f00-c086-11eb-872a-28024c776605.png)
> 
> is it because i didnt copy the lib folder because i couldnt find it

U made a mistake on source 
This is where did u messed up

**Comment by luckydog7** [comment]
install haxe 4.2.2
