### ISSUE TITLE
Tari and Belle Mod...

### ISSUE THREAD

**Issue by Voicefulmario19** [luckydog7/Funkin-android#1050]
Here's the Mod for You
normal mod:
Bugs: black textures
How to Play: You will enter from Freeplay (it has a lot of bugs in story mode)
the reason all weekler doesn't work has been deleted just the mod's music etc. was placed.
songs:1.BOPEEBO 2.FRESH 3.SATIN PANTIES

low end mod:
bugs: black textures (only for 1gb ram)
tari and belle flying and little ones, for now it's ok but i don't think can fix it

enjoy!

links:
normal:https://mega.nz/file/U8xWFYBL#gA-UCSByBBhEdgBT5akQcgXJDJqnsnqLM_uel2doNtk
lowend:https://mega.nz/file/Ilxz0KCL#fRoD0ITpVKuhmqfX8gN3boM3bLrghU0b_1uJZJoqZP0
files from:https://gamebanana.com/mods/285733

If you see black textures, I would appreciate if you send me a screenshot.
(I am turkish)

**Comment by bloodheroC** [comment]
Extra week or replace week?

**Comment by Voicefulmario19** [comment]
> Extra week or replace week?

replace

**Comment by bf244** [comment]
Black boxes of tari

**Comment by Voicefulmario19** [comment]
> Black boxes of tari

do you have belle black textures

**Comment by bf244** [comment]
Yes

**Comment by Voicefulmario19** [comment]
> Yes

FUCK :(
