### ISSUE TITLE
Can someone change a package name for me?

### ISSUE THREAD

**Issue by DiosDonutSlave** [luckydog7/Funkin-android#1053]
I have no damn clue how to do it in APK Editor nor in Android Studio. Please help me! My telegram is "DiosDonutSlave" if you need that! I'll send you the apk i need changed there! Thanks in advance whoever responds

**Comment by Voicefulmario19** [comment]
I don't have telegram can you post the link here?

**Comment by DiosDonutSlave** [comment]
It's the whitty mod kade engine build lucky dog posted here a few days ago #969

**Comment by DiosDonutSlave** [comment]
Change the package name to "com.diokade.funkin

**Comment by Voicefulmario19** [comment]
https://mega.nz/file/VlgyyaYA#eJ45AV5cLnSKjysmAeNc13L6MZYC3C65HywQHd0ROZ8 here

**Comment by DiosDonutSlave** [comment]
> https://mega.nz/file/VlgyyaYA#eJ45AV5cLnSKjysmAeNc13L6MZYC3C65HywQHd0ROZ8 here

How did you do it anyways? Thanks!

**Comment by Voicefulmario19** [comment]
> How did you do it anyways? Thanks!

 👍

**Comment by Voicefulmario19** [comment]
please close issue
