### ISSUE TITLE
Kate engine optimized mid fight masses

### ISSUE THREAD

**Issue by toybonnie23** [luckydog7/Funkin-android#1078]

**Comment by Hurbmoment** [comment]
you really askin for mods? You want advice? Heres some advice: SEARCH UP ON YT OR PORT IT YOURSELF

**Comment by DabKnight** [comment]
I think someone already ported mid fight on mobile..
Look at the old issues
(good luck finding it)

**Comment by Hurbmoment** [comment]
> I think someone already ported mid fight on mobile..
> Look at the old issues
> (good luck finding it)

Ill try to find it ;-;

**Comment by Hurbmoment** [comment]
I think i found one: 
https://www.mediafire.com/file/ksbpqr8uzl0wtxf/Funkin-debug%282%29.apk/file (apk made by peppy)

**Comment by DabKnight** [comment]
I kinda found one on youtube also(its a extra week):
https://www.mediafire.com/file/ksbpqr8uzl0wtxf/Funkin-debug%282%29.apk/file

**Comment by DabKnight** [comment]
> I think i found one:
> https://www.mediafire.com/file/ksbpqr8uzl0wtxf/Funkin-debug%282%29.apk/file (apk made by peppy)

Nice

**Comment by toybonnie23** [comment]
Thx

**Comment by Hurbmoment** [comment]
> Thx

np!
