### ISSUE TITLE
Shaggy mod optimized

### ISSUE THREAD

**Issue by GTAGAMERVI** [luckydog7/Funkin-android#1101]
The one that luckydog7

**Comment by GTAGAMERVI** [comment]
Made doesn't work

**Comment by FnfWeek7** [comment]
#1064

**Comment by Elmorado** [comment]
Bruh

**Comment by FnfWeek7** [comment]
> Bruh

I'm trying to help you bro >:( be grateful

**Comment by GTAGAMERVI** [comment]
> > Bruh
> 
> I'm trying to help you bro >:( be grateful
What??? It worked

**Comment by GTAGAMERVI** [comment]
> > Bruh
> 
> I'm trying to help you bro >:( be grateful

It worked that I sent 2 because I forgot to attachment to that

**Comment by GTAGAMERVI** [comment]
Kk
