### ISSUE TITLE
Changed Mod 1.0.0 + Hitbox

### ISSUE THREAD

**Issue by LukeyKing123** [luckydog7/Funkin-android#1107]
Here is PC VERSION:
https://gamebanana.com/mods/285131
I can't Port SO PLS

**Comment by ZzayedD0129** [comment]
cringed

**Comment by LukeyKing123** [comment]
> cringed

NnoobedD0129

**Comment by ZzayedD0129** [comment]
> > cringed
> 
> NnoobedD0129

BtichyBtichg123

**Comment by ZzayedD0129** [comment]
Puro is gay
