### ISSUE TITLE
How to long notes in android debug menu? 

### ISSUE THREAD

**Issue by CreatorOlixter** [luckydog7/Funkin-android#1116]
Plis tell me :3

**Comment by FnfWeek7** [comment]
You mean bar notes?

**Comment by CreatorOlixter** [comment]
Maybe....

**Comment by CreatorOlixter** [comment]
Oh

**Comment by AnthonyCTM** [comment]
You can't bc the editor is bugged, luckydog will fix that

**Comment by lilpichu** [comment]
I know!
When you create a note, in the right pad will appear a plus and minus simbols, plus is more larger note and minus, obviously minus xd
But you need to de precise because the buttons are smaller than others <)

**Comment by FridayNightSans** [comment]
Wdym long note. You mean Hold Note. If it then Hold Note ini debug mode is long Forever

**Comment by sasuskindasboa** [comment]
> Plis tell me :3

So, u gonna Go in debug menu and in the superior part have "note" put you Arrow in the chart and press "+" in the "note" and remeber to save before placing another

**Comment by CreatorOlixter** [comment]
Thanks to everyone :3 I'll close this sh*t
