### ISSUE TITLE
About madness tricky...

### ISSUE THREAD

**Issue by Sushi435** [luckydog7/Funkin-android#1131]
Tricky, his mod (first version) works perfectly on my cell 
But madness always makes the game close, I need the  optimized version. Someone have the download?

**Comment by sasuskindasboa** [comment]
> Tricky, his mod (first version) works perfectly on my cell 
> But madness always makes the game close, I need the  optimized version. Someone have the download

Custom week?

**Comment by Sushi435** [comment]
> > Truque, seu mod (primeira versão) funciona perfeitamente no meu celular 
> > Mas a loucura sempre fecha o jogo, preciso da versão otimizada. Alguém tem o download
> 
> Semana personalizada?
I did not understand

**Comment by Sushi435** [comment]
> > Truque, seu mod (primeira versão) funciona perfeitamente no meu celular 
> > Mas a loucura sempre fecha o jogo, preciso da versão otimizada. Alguém tem o download
> 
> Semana personalizada?

What would a custom week be?

**Comment by Sushi435** [comment]
> > Complicado, seu mod (primeira versão) funciona perfeitamente no meu celular 
> > Mas a loucura sempre fecha o jogo, preciso da versão otimizada. Alguém tem o download
> 
> Semana personalizada?

> > Complicado, seu mod (primeira versão) funciona perfeitamente no meu celular 
> > Mas a loucura sempre fecha o jogo, preciso da versão otimizada. Alguém tem o download
> 
> Semana personalizada?

Uuuhhh, SORRY i don't know what is a custom week :^

**Comment by gamingzaidan** [comment]
Noooo

**Comment by Sushi435** [comment]
> Nãããão

No?

**Comment by GetMonke** [comment]
> > Nãããão
> 
> No?

Someone told me to take a 1x1 jpg and replace all of the back ground assets. 
I doubt it will work with no problems at all but you can try it

**Comment by Sushi435** [comment]
> > > Nãããão
> > 
> > 
> > Não?
> 
> Alguém me disse para pegar um jpg 1x1 e substituir todos os recursos de fundo.
> Duvido que funcione sem problemas, mas você pode tentar

Okay
