### ISSUE TITLE
GUYS? DO YOU CHOOSE MOD TRICKY OR SARVENTE? I'M GONNA MAKE TRICKY IF YOU CHOOSE THAT

### ISSUE THREAD

**Issue by OptimizedMaker** [luckydog7/Funkin-android#1138]

**Comment by OptimizedMaker** [comment]
Of you want to choose use react!

⛪ : Sarv
🎈: Tricky

**Comment by adlolzo** [comment]
🎈🎈🎈🎈🎈🎈🎈🎈🎈

**Comment by FridayNightVibin** [comment]
🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈

**Comment by AbujasGaming** [comment]
🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈

**Comment by andre039** [comment]
🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈

**Comment by Kris6528** [comment]
100%🎈

**Comment by OptimizedMaker** [comment]
Sorry Now Luckydog7 Was Release The Coolest Version
