### ISSUE TITLE
Can anyone port Tricky 2.0 as an extra week in normal fnf?

### ISSUE THREAD

**Issue by kffwlp** [luckydog7/Funkin-android#1151]
I want to play the Tricky 2.0 mod but with the normal fnf menus and downscroll

**Comment by kffwlp** [comment]
> N O

then just don't reply

**Comment by OptimizedMaker** [comment]
Everyone can't bro

**Comment by OptimizedMaker** [comment]
Only the creator of tricky can

**Comment by TikyPhase3** [comment]
> Everyone can't bro

I agree

**Comment by kffwlp** [comment]
Oh ok
