### ISSUE TITLE
I have tricky v2 optimized

### ISSUE THREAD

**Issue by FnfWeek7** [luckydog7/Funkin-android#1155]

**Comment by zLegend77** [comment]
Ok amigo

**Comment by FnfWeek7** [comment]
> Ok amigo

Do not ASK AGAIN UNTIL THE REAL CREATOR OF THE OPTIMIZATION RELEASES IT. ok dude?????

**Comment by Elmorado** [comment]
Yes

**Comment by zLegend77** [comment]
> > Ok amigo
> 
> Do not ASK AGAIN UNTIL THE REAL CREATOR OF THE OPTIMIZATION RELEASES IT. ok dude?????

Friend, when I said, you hadn't said that the optimization was someone else's, I hadn't uploaded it 😢

**Comment by FnfWeek7** [comment]
> > > Ok amigo
> > 
> > 
> > Do not ASK AGAIN UNTIL THE REAL CREATOR OF THE OPTIMIZATION RELEASES IT. ok dude?????
> 
> Friend, when I said, you hadn't said that the optimization was someone else's, I hadn't uploaded it 😢

Woah sorry dude I didn't read the start / yours :(

**Comment by FnfWeek7** [comment]
I'm jokin stop stop STOP
