### ISSUE TITLE
The Week 7... FINALE

### ISSUE THREAD

**Issue by Voicefulmario19** [luckydog7/Funkin-android#1197]
tankman and bf
![Screenshot_2021-06-07-15-18-24-852](https://user-images.githubusercontent.com/59393483/121015498-bb3f0c00-c7a3-11eb-8e77-15c92ef70689.jpeg)
the cutscene
![YouCut_20210607_160536388](https://user-images.githubusercontent.com/59393483/121022033-a6b24200-c7aa-11eb-8054-e320924be881.gif)
the bf holding gf
![Screenshot_2021-06-07-16-13-23-739](https://user-images.githubusercontent.com/59393483/121022882-6ef7ca00-c7ab-11eb-9ccf-475caf036f1d.jpeg)
Wow
![Screenshot_2021-06-07-19-32-31-532](https://user-images.githubusercontent.com/82843871/121056887-59909900-c7c7-11eb-97fb-21f36b3b5b14.jpeg) 
link:https://lcc.click/1QbD3zn
It works very well on 2gb rams but i feel sorry for 1gb ram :( (and official files were used)
enjoy!

**Comment by Voicefulmario19** [comment]
I don't think my effort will be worth it :(

**Comment by mcagabe19** [comment]
YEEESSS

**Comment by luigi98-beep4** [comment]
Great job :)

**Comment by mcagabe19** [comment]
> Great job :)

thx bro :)

**Comment by mcagabe19** [comment]
Wow
![Screenshot_2021-06-07-19-32-31-532](https://user-images.githubusercontent.com/82843871/121056887-59909900-c7c7-11eb-97fb-21f36b3b5b14.jpeg)

**Comment by Voicefulmario19** [comment]
> Great job :)

thx :)
