### ISSUE TITLE
The Week 7... (Update)

### ISSUE THREAD

**Issue by Voicefulmario19** [luckydog7/Funkin-android#1204]
tankman and bf
![Screenshot_2021-06-07-15-18-24-852](https://user-images.githubusercontent.com/59393483/121015498-bb3f0c00-c7a3-11eb-8e77-15c92ef70689.jpeg)
the cutscene
![YouCut_20210607_160536388](https://user-images.githubusercontent.com/59393483/121022033-a6b24200-c7aa-11eb-8054-e320924be881.gif)
the bf holding gf
![Screenshot_2021-06-07-16-13-23-739](https://user-images.githubusercontent.com/59393483/121022882-6ef7ca00-c7ab-11eb-9ccf-475caf036f1d.jpeg)

link new:https://url-x.it/FDG9fdf

It works very well on 2gb rams but i feel sorry for 1gb ram :( (and official files were used)

enjoy!

**Comment by GTAGAMERVI** [comment]
> tankman and bf
> ![Screenshot_2021-06-07-15-18-24-852](https://user-images.githubusercontent.com/59393483/121015498-bb3f0c00-c7a3-11eb-8e77-15c92ef70689.jpeg)
> the cutscene
> ![YouCut_20210607_160536388](https://user-images.githubusercontent.com/59393483/121022033-a6b24200-c7aa-11eb-8054-e320924be881.gif)
> the bf holding gf
> ![Screenshot_2021-06-07-16-13-23-739](https://user-images.githubusercontent.com/59393483/121022882-6ef7ca00-c7ab-11eb-9ccf-475caf036f1d.jpeg)
> 
> link old:https://lcc.click/1QbD3zn
> link new:https://lcc.click/J0WsJQY
> 
> changes: performance fixes, new cutscene image, stageback1.png and custombg2.png changed to jpg, Fixed Litte Sucks text.
> 
> It works very well on 2gb rams but i feel sorry for 1gb ram :( (and official files were used)
> 
> enjoy!
I already have it

**Comment by GTAGAMERVI** [comment]
> > tankman and bf
> > ![Screenshot_2021-06-07-15-18-24-852](https://user-images.githubusercontent.com/59393483/121015498-bb3f0c00-c7a3-11eb-8e77-15c92ef70689.jpeg)
> > the cutscene
> > ![YouCut_20210607_160536388](https://user-images.githubusercontent.com/59393483/121022033-a6b24200-c7aa-11eb-8054-e320924be881.gif)
> > the bf holding gf
> > ![Screenshot_2021-06-07-16-13-23-739](https://user-images.githubusercontent.com/59393483/121022882-6ef7ca00-c7ab-11eb-9ccf-475caf036f1d.jpeg)
> > link old:https://lcc.click/1QbD3zn
> > link new:https://lcc.click/J0WsJQY
> > changes: performance fixes, new cutscene image, stageback1.png and custombg2.png changed to jpg, Fixed Litte Sucks text.
> > It works very well on 2gb rams but i feel sorry for 1gb ram :( (and official files were used)
> > enjoy!
> > I already have it

Because of Matt 2.1

**Comment by mcagabe19** [comment]
>  > I already have it
> Because of Matt 2.1

What?

**Comment by MistyFisty** [comment]
![Uploading Screenshot_2021-06-08-11-07-33-28_0be5c96884ab72e264d07889f59f8a8e.jpg…]()

**Comment by mcagabe19** [comment]
What's in this screenshot (not loading screenshot)

**Comment by MistyFisty** [comment]
week 7  i ported yes cutscenes yep full week yes extra week

**Comment by MistyFisty** [comment]
linking it soon

**Comment by mcagabe19** [comment]
> linking it soon

I did not understand what you wrote (I am Turkish) [I will understand if you translate into Turkish]

**Comment by gamingzaidan** [comment]
Oooo

**Comment by mcagabe19** [comment]
> Oooo

???

**Comment by nattangomes** [comment]
b gaming

**Comment by MistyFisty** [comment]
im trying to fix the crash when u play the weeks

**Comment by MistyFisty** [comment]
here mcagabe19 hafta taşıdım evet ara sahneler evet tam hafta evet ekstra hafta

**Comment by MistyFisty** [comment]
yakında bağlanıyor

**Comment by MistyFisty** [comment]
haftaları oynadığında çökmeyi düzeltmeye çalışıyorum
