### ISSUE TITLE
FNF The Yomazone Mod [Full Week]

### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#1205]
Before that, I don't make this mod, just port this mod into Android.
The app that i use Fnf Custom Week port by iPrimeGamerz and Akki
https://youtu.be/EP3sFeYi2mM
iPrimeGamerz YouTube channel
https://youtube.com/channel/UCpWyByigLOl3Cnzux157CHw
Akki Youtube channel
https://youtube.com/channel/UCC9Tw8nWl1n66mERW56jkTA
This port mod will not same as pc version
New characters, New background, Three New Song and have dialogue.

Preview:
![Screenshot_2021-06-08-04-02-34-339_com.ninjamuffin99.funkin.yoma.jpg](https://user-images.githubusercontent.com/81964285/121080970-a9468300-c80e-11eb-93d9-84df2f809aa8.jpg)
![Screenshot_2021-06-08-04-02-42-911_com.ninjamuffin99.funkin.yoma.jpg](https://user-images.githubusercontent.com/81964285/121081012-b9f6f900-c80e-11eb-989f-40abdc3d72b6.jpg)
[Week+]
![Screenshot_2021-06-08-04-02-52-558_com.ninjamuffin99.funkin.yoma.jpg](https://user-images.githubusercontent.com/81964285/121081055-c5e2bb00-c80e-11eb-844e-6d43a3217e60.jpg)
[Dialogue]
![Screenshot_2021-06-08-04-03-06-617_com.ninjamuffin99.funkin.yoma.jpg](https://user-images.githubusercontent.com/81964285/121081405-45708a00-c80f-11eb-83b7-e5ef33ebe1fe.jpg)
[Yoma]
![Screenshot_2021-06-08-04-03-16-907_com.ninjamuffin99.funkin.yoma.jpg](https://user-images.githubusercontent.com/81964285/121081463-56b99680-c80f-11eb-8675-2659d1a22776.jpg)

Download link
Mediafire:
https://www.mediafire.com/file/hxaj306tm5cuxkp/FNF_The_YomaZone_Mod.apk/file
Mega:
https://mega.nz/file/l5h2WIzJ#rrGFZXGJDTWR2asVkX3X9I86L2MZmUBrzGNGcmHpSnI
The mod:
https://gamebanana.com/mods/54733

That all, and if you want showcase or make videos of my port mod, you have to credit me (MrTks216). Thank You

Peace out✌

**Comment by ROBIKALIVE13** [comment]
FIRST

**Comment by GTAGAMERVI** [comment]
> Before that, I don't make this mod, just port this mod into Android.
> The app that i use Fnf Custom Week by iPrimeGamerz and Akki
> https://youtu.be/EP3sFeYi2mM
> iPrimeGamerz YouTube channel
> https://youtube.com/channel/UCpWyByigLOl3Cnzux157CHw
> Akki Youtube channel
> https://youtube.com/channel/UCC9Tw8nWl1n66mERW56jkTA
> This port mod will not same as pc version
> New characters, New background, Three New Song and have dialogue.
> 
> Preview:
> ![Screenshot_2021-06-08-04-02-34-339_com.ninjamuffin99.funkin.yoma.jpg](https://user-images.githubusercontent.com/81964285/121080970-a9468300-c80e-11eb-93d9-84df2f809aa8.jpg)
> ![Screenshot_2021-06-08-04-02-42-911_com.ninjamuffin99.funkin.yoma.jpg](https://user-images.githubusercontent.com/81964285/121081012-b9f6f900-c80e-11eb-989f-40abdc3d72b6.jpg)
> [Week+]
> ![Screenshot_2021-06-08-04-02-52-558_com.ninjamuffin99.funkin.yoma.jpg](https://user-images.githubusercontent.com/81964285/121081055-c5e2bb00-c80e-11eb-844e-6d43a3217e60.jpg)
> [Dialogue]
> ![Screenshot_2021-06-08-04-03-06-617_com.ninjamuffin99.funkin.yoma.jpg](https://user-images.githubusercontent.com/81964285/121081405-45708a00-c80f-11eb-83b7-e5ef33ebe1fe.jpg)
> [Yoma]
> ![Screenshot_2021-06-08-04-03-16-907_com.ninjamuffin99.funkin.yoma.jpg](https://user-images.githubusercontent.com/81964285/121081463-56b99680-c80f-11eb-8675-2659d1a22776.jpg)
> 
> Download link
> Mediafire:
> https://www.mediafire.com/file/hxaj306tm5cuxkp/FNF_The_YomaZone_Mod.apk/file
> Mega:
> https://mega.nz/file/l5h2WIzJ#rrGFZXGJDTWR2asVkX3X9I86L2MZmUBrzGNGcmHpSnI
> The mod:
> https://gamebanana.com/mods/54733
> 
> That all, and if you want showcase or make videos of my port mod, you have credit me (MrTks216). Thank You
> 
> Peace out✌

Never heard of it but I will try it
