### ISSUE TITLE
Please make a BSIDE FNF Android! I would love it!

### ISSUE THREAD

**Issue by Adzen927** [luckydog7/Funkin-android#123]

**Comment by BoyfriendFNF** [comment]
just use apk editor pro to mod in bsides

**Comment by ElPeppyWall** [comment]
Here
https://www.mediafire.com/file/pyus9ieo4detzdl/B-SIDES_REMIXES.apk/file

**Comment by Crunchyyy456** [comment]
> just use apk editor pro to mod in bsides

How the fuck do you do that in the newer version????

**Comment by Adzen927** [comment]
> just use apk editor pro to mod in bsides

I've been trying to, but I can't find any for new version so I can change keybinds. And I would be busy alot this week so I wouldn't have time to replace all those files.

**Comment by Adzen927** [comment]
Well, someone sent me something so imma close this now! Thank you ElPeppy!

**Comment by DanisLixo** [comment]
> > just use apk editor pro to mod in bsides
> 
> How the fuck do you do that in the newer version????

use your head

**Comment by woaa12** [comment]
> > just use apk editor pro to mod in bsides
> 
> How the fuck do you do that in the newer version????

you can mod any verison lololololo

**Comment by BoyfriendFNF** [comment]
> > > just use apk editor pro to mod in bsides
> > 
> > 
> > How the fuck do you do that in the newer version????
> 
> you can mod any verison lololololo

lol true
