### ISSUE TITLE
The Week 7... V3 (Update)

### ISSUE THREAD

**Issue by Voicefulmario19** [luckydog7/Funkin-android#1230]
Changes:
Bf holding gf idle fix,
Performance improvement (again).
More info and link:#1204

**Comment by mcagabe19** [comment]
And the new link was added later so go download it again [sorry :(]

**Comment by Vladi0619** [comment]
Link doesn't to download work anymore

**Comment by mcagabe19** [comment]
> Link doesn't to download work anymore

yeah new issue

**Comment by MistyFisty** [comment]
ah adamım
