### ISSUE TITLE
Help LuckyDog7 ineed help please NGio

### ISSUE THREAD

**Issue by diegoloboner** [luckydog7/Funkin-android#1251]
PS D:\Downloads\monika-master> lime test android
source/NGio.hx:7: characters 8-24 : Type not found : io.newgrounds.NG
source/NGio.hx:8: characters 8-52 : Type not found : io.newgrounds.components.ScoreBoardComponent
source/NGio.hx:9: characters 8-35 : Type not found : io.newgrounds.objects.Medal
source/NGio.hx:10: characters 8-35 : Type not found : io.newgrounds.objects.Score
source/NGio.hx:11: characters 8-40 : Type not found : io.newgrounds.objects.ScoreBoard
source/NGio.hx:12: characters 8-45 : Type not found : io.newgrounds.objects.events.Response
source/NGio.hx:13: characters 8-43 : Type not found : io.newgrounds.objects.events.Result
source/NGio.hx:14: characters 8-43 : Type not found : io.newgrounds.objects.events.Result
source/NGio.hx:28: characters 42-47 : Type not found : Score
source/Highscore.hx:5: lines 5-102 : Defined in this class
source/Highscore.hx:39: characters 8-17 : Class<NGio> has no field postScore
source/GameOverSubstate.hx:65: characters 2-10 : Unexpected override
PS D:\Downloads\monika-master>

**Comment by diegoloboner** [comment]
I already have newgrounds installed

**Comment by Rs232k** [comment]
> I already have newgrounds installed

Quick fix: comment it.

**Comment by diegoloboner** [comment]
i fixed
