### ISSUE TITLE
FNF Kepler Observation Unit (FULL WEEK) (Delete)

### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#1254]
Before that, i don't make this mod, just port this mod into android.
The app that i use Fnf KE Custom Week port by iPrimeGamerz and Akki
https://youtu.be/ouo9cx7sQ6E
iPrimeGamerz YouTube channel
https://youtube.com/channel/UCpWyByigLOl3Cnzux157CHw
Akki Youtube channel
https://youtube.com/channel/UCC9Tw8nWl1n66mERW56jkTA
New characters, New background, Three New Song and have dialogue.
Preview:
[Week x]
![Screenshot_2021-06-11-18-55-54-770_com.ninjamuffin99.funkin.kou.jpg](https://user-images.githubusercontent.com/81964285/121680136-c4094800-caeb-11eb-89fe-e33fc2599f18.jpg)
[Dialogue]
![Screenshot_2021-06-11-18-56-13-419_com.ninjamuffin99.funkin.kou.jpg](https://user-images.githubusercontent.com/81964285/121680175-ce2b4680-caeb-11eb-8840-98b27684d9c0.jpg)
![Screenshot_2021-06-11-18-56-19-693_com.ninjamuffin99.funkin.kou.jpg](https://user-images.githubusercontent.com/81964285/121680190-d5eaeb00-caeb-11eb-8258-149cb4647cd5.jpg)
![Screenshot_2021-06-11-18-56-22-177_com.ninjamuffin99.funkin.kou.jpg](https://user-images.githubusercontent.com/81964285/121680347-06328980-caec-11eb-8cc1-b28f977547a9.jpg)
If you want watch more preview, here:
https://youtu.be/Cq1nFSMat_M
ROBIKALIVE Youtube Channel
https://youtube.com/channel/UCIK7cL2matLNAKfhYwAORCQ
Download link:
Mediafire:
(Delete)
Mega:
(Delete)

The mod:
https://gamebanana.com/mods/55421

That it, if you want to showcase or make a video of my port mod, you have to credit me (MrTks216). Thank you.
Have Fun.

**Comment by FridayNightSans** [comment]
(no horni keirth allowed)
So i wont  be able to downloading this :(

**Comment by MrTks216** [comment]
> (no horni keirth allowed)
> So i wont  be able to downloading this :(

what? lol

**Comment by FridayNightSans** [comment]
@
![Screenshot_20210612-133325](//user-images.githubusercontent.com/81144896/121767528-c9fe3800-cb82-11eb-86fb-cc0648ffc0f9.png)
Here, no horni keirth

**Comment by FridayNightSans** [comment]
![Uploading Screenshot_20210612-133325.png…]()

**Comment by MrTks216** [comment]
> @
> ![Screenshot_20210612-133325](//user-images.githubusercontent.com/81144896/121767528-c9fe3800-cb82-11eb-86fb-cc0648ffc0f9.png)
> Here, no horni keirth

can't see, screenshot, but i gonna delete my port mod, No more download link.

**Comment by MrTks216** [comment]
The proof
![IMG_20210612_084427.jpg](https://user-images.githubusercontent.com/81964285/121768046-9f19e100-cb8e-11eb-9e22-cab006a3d29b.jpg)
