### ISSUE TITLE
The Week 7... (Update) [again]

### ISSUE THREAD

**Issue by mcagabe19** [luckydog7/Funkin-android#1256]
kade engine mobile support and botplay!
https://youtu.be/v-I8Fdxrma0

bf and tankman
![B.jpeg](https://user-images.githubusercontent.com/82843871/121689569-6b2ab700-cacd-11eb-9ece-4215c65e3ee3.jpeg)

bf holding gf
![C.jpg](https://user-images.githubusercontent.com/82843871/121689689-98776500-cacd-11eb-8cd3-5c687aa86e69.jpg)

changes: bf dead animation re-edited (faster)

added: secret song (hint: story mode)
let's see who will find it xd 

link v3.2:https://cntr.click/9GVtVGv
link v3.0:https://url-x.it/FDG9fdf (no secret song and non-kade)

versions:Custom Week (4.0) Tankman (3.2)

enjoy!

**Comment by putinerbasilio** [comment]
Mod govno

**Comment by mcagabe19** [comment]
> kade engine mobile support and botplay!
> https://youtu.be/v-I8Fdxrma0
> 
> bf and tankman
> ![B.jpeg](https://user-images.githubusercontent.com/82843871/121689569-6b2ab700-cacd-11eb-9ece-4215c65e3ee3.jpeg)
> 
> bf holding gf
> ![C.jpg](https://user-images.githubusercontent.com/82843871/121689689-98776500-cacd-11eb-8cd3-5c687aa86e69.jpg)
> 
> changes: bf dead animation re-edited (faster)
> 
> added: secret song (hint: story mode)
> let's see who will find it xd
> 
> link v3.2:https://cntr.click/9GVtVGv
> link v3.0:https://url-x.it/FDG9fdf (no secret song and non-kade)
> 
> versions:Custom Week (4.0) Tankman (3.2)
> 
> enjoy!
