### ISSUE TITLE
Steal without giving credits?

### ISSUE THREAD

**Issue by AngeleAkane** [luckydog7/Funkin-android#1258]
Well, there is a group in discord called FNF Mobile, and it seems that they use the Luckydog Port but with several mods that they placed themselves, but the truth is I feel that they are in a way stealing their credit (and money, because they accept funds I don't know how much they earn though) and I'm not sure if Luckydog.  I mean, I don't know anything about it, and I don't know if they already knew this.  But I already said it :>

I see that nobody recognizes Luckydog and makes me doubt if they at least give him credit, they raid people who steal and re-upload their version of FnF but I don't know if they did the same…

**Comment by Kappandrew** [comment]
... thats the Gamerbross' port, lol

**Comment by AngeleAkane** [comment]
> ... thats the Gamerbross' port, lol

Well I don't know about it anyway, and I just wanted to say it just in case :,>

**Comment by kffwlp** [comment]
They didn't steal it's their port. Entirely a different engine than Luckydog7's

**Comment by AnthonyCTM** [comment]
I just wanna say that luckydog just made an engine and they are using it, like kade engine with fnf on pc, if there is any change on the engine well then the engine is completely from them and it's not something to be crying for, it's just fair use because if we go furter then luckydog would be stealing fnf by making a port of their game without(i think) their permission

**Comment by AngeleAkane** [comment]
> I just wanna say that luckydog just made an engine and they are using it, like kade engine with fnf on pc, if there is any change on the engine well then the engine is completely from them and it's not something to be crying for, it's just fair use because if we go furter then luckydog would be stealing fnf by making a port of their game without(i think) their permission

Mmmm, I understand. Well, at least that way I can stop worrying. Thanks.

**Comment by bloodheroC** [comment]
Maybe close this issue
