### ISSUE TITLE
Sprite resolution

### ISSUE THREAD

**Issue by AngeleAkane** [luckydog7/Funkin-android#1259]
I'll be brief, I feel that one way to better optimize the game is by lowering its resolution. (Although I don't know how) For example, there is Friday Might Funkin that succeeded and works for low-end phones, and at the same time avoids closing so much. But hey, it was just an idea. I don't know how they do it, and yes, the pixels are very noticeable.

**Comment by lilpichu** [comment]
That's right. Because this I can't open week 5! Do you know what is my favorite song? Eggnog. And I can't play it! Let's do this.

**Comment by Luc4s-adv** [comment]
> Isso mesmo. Porque isso eu não posso abrir na semana 5! Você sabe qual é a minha música favorita? Eggnog. E eu não consigo jogar! Vamos fazer isso.

The problem with you not being able to play Week 5 is your ram, to play Week 5 you have to have at least 3 GB RAM, if you have less than that, The way is to download a Fnf lite or Fnf para Gama low

**Comment by Luc4s-adv** [comment]
Even if your cell phone is 64 bits, or has no problem with black texture, it still has to have good ram memory
