### ISSUE TITLE
fnf lite question

### ISSUE THREAD

**Issue by MatheusPanda** [luckydog7/Funkin-android#126]
how on week 4 high and milf dont crash on fnf lite
i want to make high and milf dont crash on my mod but on my mod it crashes

**Comment by DanisLixo** [comment]
replace Mom_assets.png

**Comment by MatheusPanda** [comment]
> replace Mom_assets.png

if work i close

**Comment by MatheusPanda** [comment]
> > replace Mom_assets.png
> 
> if work i close

Week 4 still crashes on high and milf

**Comment by DanisLixo** [comment]
manolo, só troca o mom-car pelo mom no arquivo .json das músicas logo

**Comment by MatheusPanda** [comment]
> manolo, só troca o mom-car pelo mom no arquivo .json das músicas



> manolo, só troca o mom-car pelo mom no arquivo .json das músicas logo

Só troca as musicas e o mom car pelo mom assets?

**Comment by DanisLixo** [comment]
as músicas não, é como trocar de personagem no jogo, só que você faz isso pelo arquivo

**Comment by MatheusPanda** [comment]
> as músicas não, é como trocar de personagem no jogo, só que você faz isso pelo arquivo

eu troquei o mom assets pelo mom car e começo tudo a bugar

**Comment by DanisLixo** [comment]
faz o mod
Substitua o mom-car.png e .xml com o mom_assets.png e .xml
você só esqueceu do .xml

**Comment by DanisLixo** [comment]
Ou você tem essa opção
![Screenshot_20210322-194201](https://user-images.githubusercontent.com/58278276/112067457-d906b880-8b46-11eb-9a51-90da6608f544.png)

**Comment by MatheusPanda** [comment]
> Ou você tem essa opção
> ![Screenshot_20210322-194201](https://user-images.githubusercontent.com/58278276/112067457-d906b880-8b46-11eb-9a51-90da6608f544.png)
Irei tentar

**Comment by MatheusPanda** [comment]
eu vou ter que recolir a mom? e que ela normal ja ta pintanda menos a lite

**Comment by MatheusPanda** [comment]
finalmente funciono obrigado eu tava dando uma de burro pq era só mudar o xml obrigado dani sem o lixo
