### ISSUE TITLE
Türkler Anladı XD

### ISSUE THREAD

**Issue by mcagabe19** [luckydog7/Funkin-android#1263]
![Screenshot_2021-06-12-03-05-54-588](https://user-images.githubusercontent.com/82843871/121758691-259cd700-cb2b-11eb-994b-0151f9c30760.jpeg)
XD

**Comment by Joshuaj970** [comment]
Wat

**Comment by mcagabe19** [comment]
> Wat

Only Turks understand.

**Comment by HighFlyer-222** [comment]
türkler ne anladı

**Comment by StrawRetro** [comment]
31 xdxdxd

**Comment by HighFlyer-222** [comment]
after 3 years
