### ISSUE TITLE
Tankman but what the fuck notes!?!?

### ISSUE THREAD

**Issue by mcagabe19** [luckydog7/Funkin-android#1265]
sorry for lag
https://user-images.githubusercontent.com/82843871/121759379-1a977600-cb2e-11eb-83da-5b23eb69cd8f.mp4
link:pls wait

**Comment by Tonate12** [comment]
BRO THATS MESS UP

**Comment by mcagabe19** [comment]
> BRO THATS MESS UP

wat? (I am turkish)

**Comment by Tonate12** [comment]
THAT NOTE IM NOT GONNA BEAT THAT

**Comment by mcagabe19** [comment]
> BRO THATS MESS UP

sjsjsksjsjsjs There are normal and easy options

**Comment by Tonate12** [comment]
Hmm ok?
