### ISSUE TITLE
Tankman but what the fuck notes!?!? 

### ISSUE THREAD

**Issue by mcagabe19** [luckydog7/Funkin-android#1266]
sorry for lag
https://user-images.githubusercontent.com/82843871/121759379-1a977600-cb2e-11eb-83da-5b23eb69cd8f.mp4
link:https://lcc.click/m6B6jFw

only for 2.5gb or 2gb ram

(luck rate: 0.05%)

write here when you pass

**Comment by mcagabe19** [comment]
SOOOOO HAAARRRDDDDD

**Comment by Tonate12** [comment]
ITS HARDDD

**Comment by mcagabe19** [comment]
> ITS HARDDD

YESSSS I already opened not play in the video XD

**Comment by mcagabe19** [comment]
> > ITS HARDDD
> 
> YESSSS I already opened botplay in the video XD

but still passable (luck rate: 0.05%)

**Comment by mcagabe19** [comment]
write here when you pass

**Comment by mcagabe19** [comment]
> sorry for lag
> https://user-images.githubusercontent.com/82843871/121759379-1a977600-cb2e-11eb-83da-5b23eb69cd8f.mp4
> link:https://lcc.click/m6B6jFw
> only for 2.5gb or 2gb ram

write here when you pass

**Comment by Tonate12** [comment]
How did you makes that mod anyway

**Comment by mcagabe19** [comment]
> How did you makes that mod anyway

which mod is tankman or note mod?

**Comment by Pixelbeep** [comment]
Just put all controls the go in the song easy mode

**Comment by Pixelbeep** [comment]
> sorry for lag
> https://user-images.githubusercontent.com/82843871/121759379-1a977600-cb2e-11eb-83da-5b23eb69cd8f.mp4
> link:https://lcc.click/m6B6jFw
> 
> only for 2.5gb or 2gb ram
> 
> write here when you pass

ez

**Comment by mcagabe19** [comment]
> Just put all controls together then go in the song easy mode

hahahaha i finished hard mode
