### ISSUE TITLE
Notesplash Source Code Well Not Mostly...

### ISSUE THREAD

**Issue by JoseGithubFNF** [luckydog7/Funkin-android#1270]
The Splashing Notes Came From Toadchet Channel That Made The Tankman Mod Here it Is https://www.mediafire.com/view/qtyff742iql51hz/NOTE_assets.png/file And Here Is The Xml File https://www.mediafire.com/file/eqqlf8mtxh3kxdx/NOTE_assets.xml/file How Did You Get the File From Toadchet Don't Ask Question

**Comment by JoseGithubFNF** [comment]
Also If You Wanna Add The File Yourself Then Use Apk Editor Pro! Also Stop Asking For Week 7 And Uploading Fake Source Codes Now Bye And Don't Ask For All The Week 7 Source Code I Only Got The NoteSplash Cuz I Don't Want To Add To Much Pressure To Luckdog7 So Just Use The Gamerbross Is Mod

**Comment by JoseGithubFNF** [comment]
Closing This Issue Cuz I Think No one is using this uh yeah!

**Comment by mcagabe19** [comment]
> Closing This Issue Cuz I Think No one is using this uh yeah!

me used

**Comment by JoseGithubFNF** [comment]
> > Closing This Issue Cuz I Think No one is using this uh yeah!
> 
> me used

Ok Thanks 😁

**Comment by JoseGithubFNF** [comment]
Oh Yeah Forgot Credit This Guy If Your Gonna Use The NoteSplash Source Code You Have To Credit This Guy https://youtube.com/channel/UCHesIeGc_qZ0CUDLnRJSaIg Ok Bye!

**Comment by JoseGithubFNF** [comment]
Looks Like The Source Code Is About To Be Released I Might Need To Close This Now
