### ISSUE TITLE
The Week 7... (Update Release)

### ISSUE THREAD

**Issue by mcagabe19** [luckydog7/Funkin-android#1272]
kade engine mobile support and botplay!
https://youtu.be/v-I8Fdxrma0

bf and tankman
![B.jpeg](https://user-images.githubusercontent.com/82843871/121689569-6b2ab700-cacd-11eb-9ece-4215c65e3ee3.jpeg)

bf holding gf
![C.jpg](https://user-images.githubusercontent.com/82843871/121689689-98776500-cacd-11eb-8cd3-5c687aa86e69.jpg)

added: https://user-images.githubusercontent.com/82843871/121772332-6faea880-cb7d-11eb-837a-4c2135f227bd.mp4 thx @JoseGithubFNF

link v3.5:https://url-x.it/hPYAr14
link v3.2:https://cntr.click/9GVtVGv (no #1270)
link v3.0:https://url-x.it/FDG9fdf (no secret song, non-kade and no #1270)

versions:Custom Week (4.0) Tankman (3.5)

Credits
Prime
Akki
Cowhat
(SHOUTOUT)
FridayNightSans (no horni keirth allowed)
NeonSus
Iwasgt
Cronix
thx :)

enjoy!

**Comment by RoFt-original** [comment]
Nice

**Comment by JoseGithubFNF** [comment]
> kade engine mobile support and botplay!
> https://youtu.be/v-I8Fdxrma0
> 
> bf and tankman
> ![B.jpeg](https://user-images.githubusercontent.com/82843871/121689569-6b2ab700-cacd-11eb-9ece-4215c65e3ee3.jpeg)
> 
> bf holding gf
> ![C.jpg](https://user-images.githubusercontent.com/82843871/121689689-98776500-cacd-11eb-8cd3-5c687aa86e69.jpg)
> 
> added: https://user-images.githubusercontent.com/82843871/121772332-6faea880-cb7d-11eb-837a-4c2135f227bd.mp4 thx @JoseGithubFNF
> 
> link v3.5:https://url-x.it/hPYAr14
> link v3.2:https://cntr.click/9GVtVGv (no #1270)
> link v3.0:https://url-x.it/FDG9fdf (no secret song, non-kade and no #1270)
> 
> versions:Custom Week (4.0) Tankman (3.5)
> 
> enjoy!

>:c Credit Toadchet To His The One That Made The NoteSplash I Just Found The File From Zachiver >:c

**Comment by JoseGithubFNF** [comment]
> Ni

> kade engine mobile support and botplay!
> https://youtu.be/v-I8Fdxrma0
> 
> bf and tankman
> ![B.jpeg](https://user-images.githubusercontent.com/82843871/121689569-6b2ab700-cacd-11eb-9ece-4215c65e3ee3.jpeg)
> 
> bf holding gf
> ![C.jpg](https://user-images.githubusercontent.com/82843871/121689689-98776500-cacd-11eb-8cd3-5c687aa86e69.jpg)
> 
> added: https://user-images.githubusercontent.com/82843871/121772332-6faea880-cb7d-11eb-837a-4c2135f227bd.mp4 thx @JoseGithubFNF
> 
> link v3.5:https://url-x.it/hPYAr14
> link v3.2:https://cntr.click/9GVtVGv (no #1270)
> link v3.0:https://url-x.it/FDG9fdf (no secret song, non-kade and no #1270)
> 
> versions:Custom Week (4.0) Tankman (3.5)
> 
> enjoy!

>:c Don't Forget Toadchet His The One That Made The NoteSplash From The Tankman Port I Just Found It From The Files On Zachiver >:c

**Comment by JoseGithubFNF** [comment]
>:c Hey Don't Forget Toadchet Credit Him To He Made The Tankman Mod And I Saw It Has NoteSplash Cuz I Went To The Apk And So NoteSplash So Don't Forget About Him Here Is His Channel https://youtube.com/channel/UCHesIeGc_qZ0CUDLnRJSaIg Credit Him To Cuz I Just When To The Apk And Saw The NoteSplash PNG Ok Now Credit Him To!

**Comment by DabKnight** [comment]
HOW THE FUCK ARE YOU SO UNDERRATED,THIS IS EPIC!

**Comment by JoseGithubFNF** [comment]
> HOW THE FUCK ARE YOU SO UNDERRATED,THIS IS EPIC!

You Forgot To Credit Toadchet :c I Sent The Files From Toadchet Mod

**Comment by Pogsher** [comment]
Lets get on the bed and funk

**Comment by FridayNightSans** [comment]
Man, credits
Prime
Akki
Cowhat
(SHOUTOUT)
Me! (no horni keirth allowed)
NeonSus
Iwasgt
Cronix

**Comment by mcagabe19** [comment]
> Man, credits
> Prime
> Akki
> Cowhat
> (SHOUTOUT)
> Me! (no horni keirth allowed)
> NeonSus
> Iwasgt
> Cronix

what is horni keirth? (I am turkish)

**Comment by FridayNightSans** [comment]
Dont mind, that my name. KEIRTH! And im horny 👉👈
