### ISSUE TITLE
Hey how do I export json file

### ISSUE THREAD

**Issue by GDHatdaug1992** [luckydog7/Funkin-android#1275]
I'm charting okay

**Comment by mcagabe19** [comment]
note charts?

**Comment by GDHatdaug1992** [comment]
> note charts?

Yes I'm charting

**Comment by mcagabe19** [comment]
https://user-images.githubusercontent.com/82843871/121780544-82d76d80-cba9-11eb-9021-d6c7908c1b1f.mp4 watch

**Comment by GDHatdaug1992** [comment]
thanks brb

**Comment by mcagabe19** [comment]
close issue :/
