### ISSUE TITLE
Can you add a like another control that its like its four tiles are just colored rectangle that catch from the bottom of the screen to the top of the screen
Basically i mean that left,down,up,right are just colored tiles that take over the screen
I mean again like those ports on roblox that have those 4 colored tiles
By that will make the game easier than the custom controls

### ISSUE THREAD

**Issue by Zizoplays1** [luckydog7/Funkin-android#128]
Heres what i mean
![Screenshot_20210323-000853.jpg](https://user-images.githubusercontent.com/80594096/112065293-19792d00-8b6d-11eb-95a5-1c78f204b855.jpg)

**Comment by Zizoplays1** [comment]
![Screenshot_20210323-000853.jpg](https://user-images.githubusercontent.com/80594096/112065155-d74feb80-8b6c-11eb-8c31-c3a251f46be1.jpg)
Heres what i mean

**Comment by DanisLixo** [comment]
> Can you add a like another control that its like its four tiles are just colored rectangle that catch from the bottom of the screen to the top of the screen Basically i mean that left,down,up,right are just colored tiles that take over the screen I mean again like those ports on roblox that have those 4 colored tiles By that will make the game easier than the custom controls 
Use the funkin comment

**Comment by nattangomes** [comment]
LMAO WHAT
I saw this yestarday, im just leaving a comment here. I wanted to post the same thing but your the first lol

**Comment by Zizoplays1** [comment]
> LMAO WHAT
> I saw this yestarday, im just leaving a comment here. I wanted to post the same thing but your the first lol

Lol

**Comment by Zizoplays1** [comment]
> > Can you add a like another control that its like its four tiles are just colored rectangle that catch from the bottom of the screen to the top of the screen Basically i mean that left,down,up,right are just colored tiles that take over the screen I mean again like those ports on roblox that have those 4 colored tiles By that will make the game easier than the custom controls 
> 
> Use the funkin comment

Heres a use for the funkin comment
![Screenshot_20210323-000853.jpg](https://user-images.githubusercontent.com/80594096/112181559-38c39900-8c05-11eb-9975-3152c29184fe.jpg)

**Comment by DanisLixo** [comment]
no, u used the title to suggest: I want tiles controls but with a giant text
one comment was enough

**Comment by DanisLixo** [comment]
wait, is that a joke?

**Comment by iggnaT** [comment]
luckydog70 released this function few hours ago
