### ISSUE TITLE
FNF Monika Mod V2 (low end)

### ISSUE THREAD

**Issue by mcagabe19** [luckydog7/Funkin-android#1283]
(I am turkish)
monika v2 low end version
ported by luckydog7 low end by me

but unfortunately cutscenes were deleted why?
I did the low end version of the cutscenes, but it always crashed.

link:https://cntr.click/L68ndfY

enjoy!

**Comment by HatsuneMiku-github** [comment]
I did a low end one too-
I guess it isn't a problem because I will update mine when there is an issue with it?

**Comment by mcagabe19** [comment]
> I did a low end one too-
> I guess it isn't a problem because I will update mine when there is an issue with it?

You can download what I made. This version is designed for 1gb ram
