### ISSUE TITLE
Pause menu?

### ISSUE THREAD

**Issue by pressenterreal** [luckydog7/Funkin-android#13]
Is there any way you can code a pause button into the game that opens the pause menu? You said press "back" to go to the pause menu but the B and A buttons hide when the battle starts. My suggestion would be to put the B button on the left side and code it to open the menu. Also, if you can, please make a way for the debug mode to work!

**Comment by ElPeppyWall** [comment]
you have to press this back button 
![Screenshot_20210226-092423_Chrome](https://user-images.githubusercontent.com/79715656/109333566-760a5600-7814-11eb-858b-d45c036d646a.jpg)

**Comment by luckydog7** [comment]
it seems to me that the answer is given

**Comment by pressenterreal** [comment]
I'm dumb

**Comment by pressenterreal** [comment]
Lol
