### ISSUE TITLE
The Week 7... (BIG Update)

### ISSUE THREAD

**Issue by mcagabe19** [luckydog7/Funkin-android#1305]
OG:
bf and tankman
![B.jpeg](https://user-images.githubusercontent.com/82843871/121689569-6b2ab700-cacd-11eb-9ece-4215c65e3ee3.jpeg)

bf holding gf
![C.jpg](https://user-images.githubusercontent.com/82843871/121689689-98776500-cacd-11eb-8cd3-5c687aa86e69.jpg)

no gf
![Capture 2021-06-13 20.20.09.jpg](https://user-images.githubusercontent.com/82843871/121816707-cdc6b300-cc85-11eb-928d-b49aadf616e2.jpg)
gf file received by high effort v2.2

changes:
BF death animation completely deleted
Tankman miss completely deleted 
performance improvement

COLOR:
start screen
![Screenshot_2021-06-14-12-13-14-262.jpeg](https://user-images.githubusercontent.com/82843871/121870232-7ff48e00-cd0b-11eb-860a-2b59faa8bae8.jpeg)

bf and tankman
![Capture 2021-06-14 12.10.44.jpg](https://user-images.githubusercontent.com/82843871/121870090-5dfb0b80-cd0b-11eb-9cf9-42e04c718768.jpg)

bf holding gf
![Screenshot_2021-06-14-12-14-59-138.jpeg](https://user-images.githubusercontent.com/82843871/121870143-68b5a080-cd0b-11eb-8400-c6365039ec81.jpeg)

note assets
![Adsız_1080p.gif](https://user-images.githubusercontent.com/82843871/121872016-7704bc00-cd0d-11eb-9054-8a9988a54b5e.gif)

changes:
First version

link and other mods:https://cntr.click/zk8JWVd

versions:Custom Week (4.0)

Credits
Prime
Akki
Cowhat
(SHOUTOUT)
NeonSus
Iwasgt
Cronix

enjoy!

**Comment by JoseGithubFNF** [comment]
> OG:
> bf and tankman
> ![B.jpeg](https://user-images.githubusercontent.com/82843871/121689569-6b2ab700-cacd-11eb-9ece-4215c65e3ee3.jpeg)
> 
> bf holding gf
> ![C.jpg](https://user-images.githubusercontent.com/82843871/121689689-98776500-cacd-11eb-8cd3-5c687aa86e69.jpg)
> 
> no gf
> ![Capture 2021-06-13 20.20.09.jpg](https://user-images.githubusercontent.com/82843871/121816707-cdc6b300-cc85-11eb-928d-b49aadf616e2.jpg)
> gf file received by high effort v2.2
> 
> changes:
> BF death animation completely deleted
> Tankman miss completely deleted
> performance improvement
> 
> COLOR:
> start screen
> ![Screenshot_2021-06-14-12-13-14-262.jpeg](https://user-images.githubusercontent.com/82843871/121870232-7ff48e00-cd0b-11eb-860a-2b59faa8bae8.jpeg)
> 
> bf and tankman
> ![Capture 2021-06-14 12.10.44.jpg](https://user-images.githubusercontent.com/82843871/121870090-5dfb0b80-cd0b-11eb-9cf9-42e04c718768.jpg)
> 
> bf holding gf
> ![Screenshot_2021-06-14-12-14-59-138.jpeg](https://user-images.githubusercontent.com/82843871/121870143-68b5a080-cd0b-11eb-8400-c6365039ec81.jpeg)
> 
> note assets
> ![Adsız_1080p.gif](https://user-images.githubusercontent.com/82843871/121872016-7704bc00-cd0d-11eb-9054-8a9988a54b5e.gif)
> 
> changes:
> First version
> 
> link and other mods:https://cntr.click/zk8JWVd
> 
> versions:Custom Week (4.0)
> 
> Credits
> Prime
> Akki
> Cowhat
> (SHOUTOUT)
> NeonSus
> Iwasgt
> Cronix
> 
> enjoy!

AY! You Got If Back Great Job!

**Comment by JoseGithubFNF** [comment]
> > OG:
> > bf and tankman
> > ![B.jpeg](https://user-images.githubusercontent.com/82843871/121689569-6b2ab700-cacd-11eb-9ece-4215c65e3ee3.jpeg)
> > bf holding gf
> > ![C.jpg](https://user-images.githubusercontent.com/82843871/121689689-98776500-cacd-11eb-8cd3-5c687aa86e69.jpg)
> > no gf
> > ![Capture 2021-06-13 20.20.09.jpg](https://user-images.githubusercontent.com/82843871/121816707-cdc6b300-cc85-11eb-928d-b49aadf616e2.jpg)
> > gf file received by high effort v2.2
> > changes:
> > BF death animation completely deleted
> > Tankman miss completely deleted
> > performance improvement
> > COLOR:
> > start screen
> > ![Screenshot_2021-06-14-12-13-14-262.jpeg](https://user-images.githubusercontent.com/82843871/121870232-7ff48e00-cd0b-11eb-860a-2b59faa8bae8.jpeg)
> > bf and tankman
> > ![Capture 2021-06-14 12.10.44.jpg](https://user-images.githubusercontent.com/82843871/121870090-5dfb0b80-cd0b-11eb-9cf9-42e04c718768.jpg)
> > bf holding gf
> > ![Screenshot_2021-06-14-12-14-59-138.jpeg](https://user-images.githubusercontent.com/82843871/121870143-68b5a080-cd0b-11eb-8400-c6365039ec81.jpeg)
> > note assets
> > ![Adsız_1080p.gif](https://user-images.githubusercontent.com/82843871/121872016-7704bc00-cd0d-11eb-9054-8a9988a54b5e.gif)
> > changes:
> > First version
> > link and other mods:https://cntr.click/zk8JWVd
> > versions:Custom Week (4.0)
> > Credits
> > Prime
> > Akki
> > Cowhat
> > (SHOUTOUT)
> > NeonSus
> > Iwasgt
> > Cronix
> > enjoy!
> 
> AY! You Got It Back Great Job!

**Comment by DabKnight** [comment]
Nice!

**Comment by mcagabe19** [comment]
> Nice!

thx :)

**Comment by FridayNightSans** [comment]
NEWS!!!!
IPrime say with me and team on discord that he and Akki will make WEEK 7 for Custom Week Port!!
Ok bye .___.

**Comment by FridayNightSans** [comment]
Wait a minute, where is me :((

**Comment by mcagabe19** [comment]
> Wait a minute, where is me :((

what??

**Comment by FridayNightSans** [comment]
Lol nvm
