### ISSUE TITLE
EHM...

### ISSUE THREAD

**Issue by mcagabe19** [luckydog7/Funkin-android#1314]
https://github.com/luckydog7/Funkin-android/issues/1296#issue-919962575
let's try

**Comment by mcagabe19** [comment]
i can't sorry

**Comment by mcagabe19** [comment]
i can't sorry

**Comment by JoseGithubFNF** [comment]
> i can't sorry

Same As me Go Icons Are A Mess My Phone Freeze For A Sec When Go The PNG So It's The Biggest Mess And Hard one Out There
