### ISSUE TITLE
What the dog doin

### ISSUE THREAD

**Issue by ZzayedD0129** [luckydog7/Funkin-android#1336]
What the dog doin

**Comment by lolvan06** [comment]
Everybody ask what da dog doin

But no one ask how the dog doin :(

**Comment by ZzayedD0129** [comment]
> Everybody ask what da dog doin
> 
> But no one ask how the dog doin :(

What the dog doin?

**Comment by Joshuaj970** [comment]
> > Everybody ask what da dog doin
> > But no one ask how the dog doin :(
> 
> What the dog doin?

Nothing And Shut The F0## Up

**Comment by ZzayedD0129** [comment]
> > > Everybody ask what da dog doin
> > > But no one ask how the dog doin :(
> > 
> > What the dog doin?
> 
> Nothing And Shut The F0## Up

What the dog doin??????

**Comment by EyadTaher** [comment]
what the dog doin

**Comment by ZzayedD0129** [comment]
Wait no one say how the dog doin?
