### ISSUE TITLE
I can't save Json file or Copied to My Clipboard

### ISSUE THREAD

**Issue by TailsGithub** [luckydog7/Funkin-android#135]
I have this problem i Enter Debug Mode I DO MY SONG 
AAAAAAAND I PUT. S A V E. And it just DOSENT SAVE And i'm sorry if i became a little too Expressive i just Rage beacuse it dosent Save

**Comment by DanisLixo** [comment]
I already reported this bug #99

**Comment by TailsGithub** [comment]
Ima closet the issue

**Comment by TailsGithub** [comment]
Close
