### ISSUE TITLE
Can you port this please

### ISSUE THREAD

**Issue by Debob54** [luckydog7/Funkin-android#1371]
https://mega.nz/file/kNcXUIpJ#UlE_efyh-O2lGmwWt1ozn5V93Y4qSTvPOojdVD1qbuI

**Comment by kffwlp** [comment]
What is that mod?

**Comment by Debob54** [comment]
https://youtu.be/MRKbsf2Oxa8

**Comment by kffwlp** [comment]
Sorry, it's too hard for me to port.

**Comment by Debob54** [comment]
Ok
