### ISSUE TITLE
About Tabi Mod from GwebDev....

### ISSUE THREAD

**Issue by Kris6528** [luckydog7/Funkin-android#1410]
For those who want tabi mod original,
Join tis discord srrevr first:

Expired

Then,find the channel: -

**Comment by funk303** [comment]
It say's the folder was trashed

**Comment by netonero** [comment]
> For those who want tabi mod original,
> Join tis discord srrevr first:
> 
> https://discord.gg/v7CQ9pye
> 
> Then,find the channel:tabi links of shame

bruh you really dont get what happened, dont you
