### ISSUE TITLE
The Week 7... (New Mode)

### ISSUE THREAD

**Issue by mcagabe19** [luckydog7/Funkin-android#1417]
Info (OG):#1356
Info (COLOR):#1357

:link:(OG)https://cntr.click/92gJBy7
:link:(COLOR)https://cntr.click/H2r1t7W
:link:Mods:https://cntr.click/34Dwpz8
:link:(Bruh 7):https://cntr.click/JZt1bXN
(Week 7 Mod)
Used Mode + Video:https://youtu.be/WGJ6MBP92RU
:link:(Brugh Windows Port):https://cntr.click/5rWy4D1
[Not Tested]

versions:Custom Week (4.0)

Credits
Prime
Akki
Cowhat
(SHOUTOUT)
FridayNightSans
NeonSus
Iwasgt
Cronix

enjoy!

**Comment by POKO-dev** [comment]
> المعلومات (OG): [# 1356](https://github.com/luckydog7/Funkin-android/issues/1356)
> المعلومات (اللون): [# 1357](https://github.com/luckydog7/Funkin-android/issues/1357)
> 
> 🔗(OG) https://cntr.click/92gJBy7
> 🔗(لون) https://cntr.click/H2r1t7W
> 🔗تعديل: https://cntr.click/34Dwpz8
> 🔗(Bruh 7): https://cntr.click/JZt1bXN
> (الأسبوع 7 Mod)
> الوضع المستخدم + الفيديو: https://youtu.be/WGJ6MBP92RU
> 🔗(Brugh Windows Port): https://cntr.click/5rWy4D1
> [لم يتم اختباره]
> 
> الإصدارات: Custom Week (4.0)
> 
> الاعتمادات
> Prime
> Akki
> Cowhat
> (SHOUTOUT)
> FridayNightSans
> NeonSus
> Iwasgt
> Cronix
> 
> التمتع!

Peace be upon you . This is a very good job, thank you

**Comment by mcagabe19** [comment]
> > المعلومات (OG): [# 1356](https://github.com/luckydog7/Funkin-android/issues/1356)
> > المعلومات (اللون): [# 1357](https://github.com/luckydog7/Funkin-android/issues/1357)
> > 🔗(OG) https://cntr.click/92gJBy7
> > 🔗(لون) https://cntr.click/H2r1t7W
> > 🔗تعديل: https://cntr.click/34Dwpz8
> > 🔗(Bruh 7): https://cntr.click/JZt1bXN
> > (الأسبوع 7 Mod)
> > الوضع المستخدم + الفيديو: https://youtu.be/WGJ6MBP92RU
> > 🔗(Brugh Windows Port): https://cntr.click/5rWy4D1
> > [لم يتم اختباره]
> > الإصدارات: Custom Week (4.0)
> > الاعتمادات
> > Prime
> > Akki
> > Cowhat
> > (SHOUTOUT)
> > FridayNightSans
> > NeonSus
> > Iwasgt
> > Cronix
> > التمتع!
> 
> Peace be upon you . This is a very good job, thank you

thx
