### ISSUE TITLE
Why do the sprites show black rectangles?

### ISSUE THREAD

**Issue by NailyFromBFB** [luckydog7/Funkin-android#146]
![Screenshot_20210325-185024](https://user-images.githubusercontent.com/79092777/112553502-0350b400-8d9b-11eb-894f-beaf1f2519fa.jpg)

**Comment by DanisLixo** [comment]
low end phones problem

**Comment by NailyFromBFB** [comment]
Ok :>

**Comment by DanisLixo** [comment]
oh yeah, I forgot
#86
