### ISSUE TITLE
MY VERSION IS DEAD

### ISSUE THREAD

**Issue by mcagabe19** [luckydog7/Funkin-android#1484]
This time the real luckydog7 released it as a demo.
NO ;(
link:https://youtu.be/EN7Y7BAAM-I

**Comment by CreatorOlixter** [comment]
Don't feel bad abuot this, You're doing a really good job :)

**Comment by JoseGithubFNF** [comment]
> This time the real luckydog7 released it as a demo.
> NO ;(
> link:https://youtu.be/EN7Y7BAAM-I

Don't Just Throw Your Work Keep Continue It Plus The Full Version Hasn't Been Released So Keep Up The Good Work My Guy!

**Comment by mcagabe19** [comment]
> > This time the real luckydog7 released it as a demo.
> > NO ;(
> > link:https://youtu.be/EN7Y7BAAM-I
> 
> Don't Just Throw Your Work Keep Continue It Plus The Full Version Hasn't Been Released So Keep Up The Good Work My Guy!

r-Really?

**Comment by JoseGithubFNF** [comment]
> > > This time the real luckydog7 released it as a demo.
> > > NO ;(
> > > link:https://youtu.be/EN7Y7BAAM-I
> > 
> > 
> > Don't Just Throw Your Work Keep Continue It Plus The Full Version Hasn't Been Released So Keep Up The Good Work My Guy!
> 
> r-Really?

Yes! Your Mods Are Great Even Tho I Don't Play Them You Still Make The Greatest Mod My Guy!
