### ISSUE TITLE
It crashes with mods i put in there

### ISSUE THREAD

**Issue by blazingcody** [luckydog7/Funkin-android#1487]
**this issue has duplicates?**
Black textures - https://github.com/luckydog7/Funkin-android/issues/12 (max texture size problem)
Crash - https://github.com/luckydog7/Funkin-android/issues/10 (ram problem)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by TikyPhase3** [comment]
Idk bro
