### ISSUE TITLE
gamerbross' reaction to luckydog7 and Zack'sGamerz' week 7 demo video

### ISSUE THREAD

**Issue by sonicyt1234** [luckydog7/Funkin-android#1489]
https://youtu.be/SzATUDlECL8

I translated the title, And apparently, He hates you now, Zack'sGamerz

**Comment by TikyPhase3** [comment]
https://user-images.githubusercontent.com/83379021/123717005-8d4c6500-d841-11eb-817d-6b2f6422e647.mp4

**Comment by CreatorOlixter** [comment]
I'm Spanish, and he doesn't hate Zack, he only said that the Zack's apk isn't the same that the gamerbross apk. And also Zack and gamerbross are Friends Actually

**Comment by zacksgamerz** [comment]
> https://youtu.be/SzATUDlECL8
> 
> I translated the title, And apparently, He hates you now, Zack'sGamerz

Ok man you're straight up lying.

**Comment by CreatorOlixter** [comment]
Omg Zack :0

**Comment by Goldie5fnf** [comment]
Bruh

**Comment by alanm31** [comment]
> https://youtu.be/SzATUDlECL8
> 
> I translated the title, And apparently, He hates you now, Zack'sGamerz

Broski I'm Mexican and no your being dumb there was nothing in there of gamerbross hating on zack

**Comment by CreatorOlixter** [comment]
> > https://youtu.be/SzATUDlECL8
> > I translated the title, And apparently, He hates you now, Zack'sGamerz
> 
> Broski I'm Mexican and no your being dumb there was nothing in there of gamerbross hating on zack

Que pedo wey xD

**Comment by JoseGithubFNF** [comment]
> https://youtu.be/SzATUDlECL8
> 
> I translated the title, And apparently, He hates you now, Zack'sGamerz

Bruh Moments And Gamerbross Does Not Hate Zack I Still Haven't Translated But I Know He Does Not Hate Zack Cuz The Comment Said So.

**Comment by sonicyt1234** [comment]
> I'm Spanish, and he doesn't hate Zack, he only said that the Zack's apk isn't the same that the gamerbross apk. And also Zack and gamerbross are Friends Actually

Ok, sorry
