### ISSUE TITLE
FNF girlfriend date mod port pls

### ISSUE THREAD

**Issue by adlolzo** [luckydog7/Funkin-android#1498]

**Comment by TikyPhase3** [comment]
Ok!

**Comment by adlolzo** [comment]
> Ok!

Thanks!

**Comment by TikyPhase3** [comment]
mega.nz/file/h6gHxYpK#OnnV2fDhXGE8I-KJPKIAU×17pfUd2yTS7a2nFjXxYs

**Comment by TikyPhase3** [comment]
mega.nz/file/HxYpK#OnnV2fDhXGE8I-KJPKIAU×17pfUd2yTS7a2nFjXxYs

**Comment by TikyPhase3** [comment]
> > Ok!
> 
> Thanks!

I can't do mega download

**Comment by TikyPhase3** [comment]
Wait a bit longer I'll set up the mediafire

**Comment by adlolzo** [comment]
> Wait a bit longer I'll set up the mediafire

Ok

**Comment by TikyPhase3** [comment]
You want the link now? Not coding in the link until you replie

**Comment by adlolzo** [comment]
> You want the link now? Not coding in the link until you replie

Sure!

**Comment by TikyPhase3** [comment]
> > You want the link now? Not coding in the link until you replie
> 
> Sure!

Ok! Link: www.mediafire.com/file/zm6nsjjo0n20way/FNF_Date_With_GF%255BAndroid_Port%255D.apk/file

**Comment by TikyPhase3** [comment]
Please reply for more mods I really am bored

**Comment by adlolzo** [comment]
> > > You want the link now? Not coding in the link until you replie
> > 
> > 
> > Sure!
> 
> Ok! Link: [www.mediafire.com/file/zm6nsjjo0n20way/FNF_Date_With_GF%255BAndroid_Port%255D.apk/file](http://www.mediafire.com/file/zm6nsjjo0n20way/FNF_Date_With_GF%255BAndroid_Port%255D.apk/file)

Thanks!

**Comment by TikyPhase3** [comment]
I just wanna code ok?

**Comment by adlolzo** [comment]
> I just wanna code ok?

Ok let's see..

**Comment by adlolzo** [comment]
Cheese mod?

**Comment by TikyPhase3** [comment]
Sure!

**Comment by adlolzo** [comment]
Yk the blue guy

**Comment by TikyPhase3** [comment]
But.

**Comment by TikyPhase3** [comment]
You gotta send me a screenshot of the thumbnail of the mod

**Comment by TikyPhase3** [comment]
``or I can't do it

**Comment by adlolzo** [comment]
Ok

**Comment by TikyPhase3** [comment]
Nvm I'll send YOU screenshots and tell me the right one

**Comment by adlolzo** [comment]
K

**Comment by TikyPhase3** [comment]
![Screenshot_2021-06-29-08-26-35](https://user-images.githubusercontent.com/83379021/123805826-07b5cd00-d8b4-11eb-810f-64461ade9769.jpg)

**Comment by TikyPhase3** [comment]
That one?

**Comment by adlolzo** [comment]
Yes

**Comment by TikyPhase3** [comment]
K

**Comment by TikyPhase3** [comment]
drive.google.com/file/d/1Dd2gCj5H3o2TPSZ10HQBT6uIDM0aWGDL/view

**Comment by TikyPhase3** [comment]
Darn it

**Comment by adlolzo** [comment]
> Darn it

?

**Comment by TikyPhase3** [comment]
Alright bout to code in

**Comment by TikyPhase3** [comment]
mediafire.com/file/r4uwnbna26im9hx/Cheese+-+No+Kade+Engine+-+FNF+ANDROID.apk/file

**Comment by TikyPhase3** [comment]
Click on the Mediafire then wait then click open in chrome and enjoy

**Comment by TikyPhase3** [comment]
Anything else??

**Comment by adlolzo** [comment]
> Anything else??

No it's ok thank you very much tho!

**Comment by TikyPhase3** [comment]
Will u be my frien?

**Comment by adlolzo** [comment]
> Will u be my frien?

Oke

**Comment by TikyPhase3** [comment]
•.•

**Comment by TikyPhase3** [comment]
:D

**Comment by TikyPhase3** [comment]
![images](https://user-images.githubusercontent.com/83379021/123811122-96c4e400-d8b8-11eb-81e2-59c96d5843fd.png)

**Comment by adlolzo** [comment]
💸💸💸💸💸💸

**Comment by TikyPhase3** [comment]
![images (1)](https://user-images.githubusercontent.com/83379021/123811473-e3102400-d8b8-11eb-8c16-24f3929d25a3.jpeg)

**Comment by TikyPhase3** [comment]
![images](https://user-images.githubusercontent.com/83379021/123811530-f1f6d680-d8b8-11eb-98fc-5a29e652db5b.jpeg)

**Comment by TikyPhase3** [comment]
The first thing I did was to be a part of the world and the other is a great way to get the best out of the way and I have to say that I am not a fan of the most important things to do in the future and the other is a great way to get the best out of the way and I have to say that I am not a fan of the most important things to do in the future.

**Comment by TikyPhase3** [comment]
> The cause of the day time to get a chance to look at the campfire and s'mores I am not sure if you have any questions or concerns please visit the plug-in settings and make sure if you have any questions or concerns please visit the plug-in settings and make sure you are you still have the same and let you know that I have a great day time to get a chance to look at the campfire and s'mores I am not sure if you have any questions or concerns please visit the plug-in settings

Spam bro :D

**Comment by adlolzo** [comment]
Can you please visit the plug-in settings and make sure you are not the intended recipient you are not the intended recipient you are not the intended recipient you are not the intended recipient you are not the intended recipient you are not the intended recipient you are not the intended recipient you are not the intended recipient you are not the intended recipient you are not the intended recipient you are not the intended recipient you are not the intended recipient you are not the same you are no more options I will be able I am a bit of hell of me and my family and I want you

**Comment by TikyPhase3** [comment]
Wanna face reveal?

**Comment by adlolzo** [comment]
The budget for the intended recipient you are not in a meme generator for the use that to you soon love you and the girls and I will have a great time in a new issue of me and my birthday is coming from Morocco Mozambique I am a very good at all times I am looking for an appointment with the following the link for the intended recipients and I am a bit of me for a few weeks back and forth to hear from the dead in the day time im I am looking for an hour or so if I say the whole time to meet with you and your family and friends I have a good one for me please reply back from you and I will be able to make a new one for me to do you want the same and send me a call at all possible to get a chance to look at it again and again and again I apologize I didn't get to know what you think so but I am not the named recipients or otherwise protected from disclosure under applicable law and gives consumers the right to ask you to know if you have a good time for a long term business relation to your family are well and you can see the attached file is scanned image in PDF format I am not sure if you have any questions or concerns please visit the plug-in settings and make sure you are not the intended recipient you are not the intended recipient you are not in a new one and the other side the same the same you can I have a great weekend I have to do you have a nice time to time but I am a little more than happy I have a good day and I want the crown so that we can make the intended recipient please contact me if you have any questions or concerns please visit the plug-in settings and make sure you are not the intended recipient you are interested please contact us if I can I get back from you and the other day time and I will be able to make sure you are not the intended recipient you are not the intended recipient you are not the intended recipient you are not the intended recipient you are not the intended recipient you are not the intended recipient you are not the intended recipient you are not the intended recipient you are no more than a few weeks back from the intended recipients please visit our website and it was pink Floyd the wall and floor plan with a new issue of me for a long term relationship between I have been a long term business relation to your account we have finals week and the other side the intended recipients please contact us for any inconvenience I miss the opportunity of working experience I would love your work is it done ✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅

**Comment by TikyPhase3** [comment]
I will go first

**Comment by TikyPhase3** [comment]
![IMG_20210629_092458671](https://user-images.githubusercontent.com/83379021/123815370-0c7e7f00-d8bc-11eb-9d95-d1848c761265.jpg)

**Comment by TikyPhase3** [comment]
That's me

**Comment by TikyPhase3** [comment]
Ur turn

**Comment by adlolzo** [comment]
Ok

**Comment by adlolzo** [comment]
![IMG-20210618-WA0014](https://user-images.githubusercontent.com/82825874/123815775-a9f2a680-d8ee-11eb-9753-8a8e96a22374.jpg)

**Comment by TikyPhase3** [comment]
WTF YOUR ACTUAL FACE XDDDDD

**Comment by adlolzo** [comment]
That's me tho

**Comment by TikyPhase3** [comment]
No it's not

**Comment by TikyPhase3** [comment]
No it's not..

**Comment by adlolzo** [comment]
Ok fine

**Comment by TikyPhase3** [comment]
D O. I T.

**Comment by adlolzo** [comment]
Ok look. I'm sorry, I'm doing this for your safety. Please delete the picture.

I'm super sorry

**Comment by TikyPhase3** [comment]
> Ok look. I'm sorry, I'm doing this for your safety. Please delete the picture.
> 
> I'm super sorry

Ogeh that was google searches mine was

**Comment by OOOboyfriend2835** [comment]
Just to let u know everyone of my vids has my face so don't worry :P
