### ISSUE TITLE
Restored mod

### ISSUE THREAD

**Issue by briannewmc** [luckydog7/Funkin-android#15]
Hey can you do restored mod of friday night funkin it puts more cutscenes on every week in the girlfriend unused cheer is at the mid heres the mod link btw:https://gamebanana.com/gamefiles/download/14810
Sorry i dont know how to put the mod on mobile

**Comment by luckydog7** [comment]
maybe if I have nothing to do

**Comment by briannewmc** [comment]
Oh ok i will wait
