### ISSUE TITLE
fnf lite question 2

### ISSUE THREAD

**Issue by MatheusPanda** [luckydog7/Funkin-android#150]
how i decrease gf christmas resolution (for another mod)

**Comment by DanisLixo** [comment]
a Photo editor called literally Photo Editor.

**Comment by MatheusPanda** [comment]
> a Photo editor called literally Photo Editor.

when i download what its the resolution i need to stop crash?

**Comment by DanisLixo** [comment]
at least 7500x3000

**Comment by MatheusPanda** [comment]
> at least 7500x3000

https://play.google.com/store/apps/details?id=com.iudesk.android.photo.editor this photo editor? And i dumb to know where i find decrease resolution

**Comment by DanisLixo** [comment]
****yes****

**Comment by MatheusPanda** [comment]
> ****Yes.****

i think the last question where i find decrease resolution

**Comment by MatheusPanda** [comment]
again is as dumb i thinked resolution is quality but is the size right?

**Comment by DanisLixo** [comment]
yes, but it depends a little on the quality as well.

**Comment by MatheusPanda** [comment]
> yes, but it depends a little on the quality as well.

i decreased the image and i gonna see if work now

**Comment by MatheusPanda** [comment]
![20210326_220901](https://user-images.githubusercontent.com/70347822/112705990-f9ed4780-8e7f-11eb-9083-d82c6c068f00.png)
Danis?

**Comment by DanisLixo** [comment]
beautiful, I think you forgot the .xml file right?

**Comment by MatheusPanda** [comment]
> beautiful, I think you forgot the .xml file right?

no when the xml glitch the character is more easy to see but when the size change it shows as a character idk how to fix without back to normal size and crash the game

**Comment by MatheusPanda** [comment]
can you make the lite sprite for me? or i need to remove gf christmas

**Comment by DanisLixo** [comment]
I'm lazy, maybe later

**Comment by DanisLixo** [comment]
It's 10 o'clock at night, I'll have to sleep in a little while

**Comment by MatheusPanda** [comment]
> It's 10 o'clock at night, I'll have to sleep in a little while

il give the sprite thats its not mine and you see what you il do ok?
![Uploading gfChristmas.png…]()

**Comment by DanisLixo** [comment]
done
![gfChristmas](https://user-images.githubusercontent.com/58278276/112706832-a8e05200-8e85-11eb-9c1a-0607bf778980.png)

**Comment by DanisLixo** [comment]
we will continue on Discord, of course, if u have

**Comment by MatheusPanda** [comment]
> we will continue on Discord, of course, if u have

pandinho8205#7641 bad name lol
