### ISSUE TITLE
lite version : fnfps+ / 0.2.7.1 ver2

### ISSUE THREAD

**Issue by softonicblip** [luckydog7/Funkin-android#151]
i made a lite version for low-end devices.

Link (99mb): https://www.mediafire.com/file/5cy439t0d98mviz/fnfps++0.2.7.1+ver2.apk/file

Alt (139mb): https://www.mediafire.com/file/vq3quhkvdj3c7rv/fnfps++0.2.7.1+ver2+(alt).apk/file
***this alternative will probably be less laggy***

- I tried to don't delete any image

that means it basically looks like the game doesn't have any visual changes, only everything is compressed (images, audio)

sorry for my bad english and thanks for your attention xd

**Comment by DanisLixo** [comment]
what a coincidence, i also did, it will probably be the next issue

**Comment by DanisLixo** [comment]
bro, I think it's doesn't work, in fact I venture to say that it got worse

**Comment by softonicblip** [comment]
@DanisLixo oh yeah i noticed that and i'm currently fixing it, so don't worry
