### ISSUE TITLE
Lite Version (help) (fixed issue)

### ISSUE THREAD

**Issue by DanisLixo** [luckydog7/Funkin-android#152]
Funk Low End Phones: https://www.mediafire.com/download/2gut4lcwrm5mll5

Bugs:
game crashes (sometimes on week 4, and Cocoa and Eggnog 100%)
Black texture (rare)
I'm still alive (buuuuug)

Warning: The characters (BF, GF, Dad, Spooky kids and pico) are too small, And the GF does nothing, she just dances :|

friday nights at funkin: https://www.mediafire.com/download/p7jfrv12kou842o

Changed: 
Week 5 is now working (I just deleted the Mom and Dad)
GF Xmas event still without quality 👍

Bugs:
Game crashes (sometimes)
Black texture (maybe)
Im alive (Yes, this is a bug)
The BF doesn't have his Death animation (idle BF)
The train never existed
yaaaaaaaaaay

added:
Hitbox

FNF Minus Lite: https://www.mediafire.com/download/hq3y1siby9w29to

Changed:
just deleted the GF and the parents
Week 5 is now working
Week 6 too

Bugs:
week 4 (still playable)
game crashes
black Textures (rare)

Special Thanks:
Hadobedo (FunkiniOS): For the sprites of the Low End version.
Ninjamuffin99: For leaving the source code of the old versions still available.
Luckydog7: for the port sent it well man, keep up the good work!
Ibis Paint: Mods.
P.S.: cara do tijolinho.

**Comment by BoyfriendFNF** [comment]
can you make bside lite???

**Comment by Crunchyyy456** [comment]
Goodjob guys!

**Comment by Caco-o-sapo** [comment]
Thanks for this! Your version is the only that worked in my phone so far! Here are some screenshots.

![Screenshot_20210327-212454.png](https://user-images.githubusercontent.com/57275984/112738780-dd671300-8f44-11eb-8d37-b879e475deb3.png)
![Screenshot_20210327-213454.png](https://user-images.githubusercontent.com/57275984/112738784-e22bc700-8f44-11eb-960a-d726b2c2a01c.png)

**Comment by DanisLixo** [comment]
> Thanks for this! Your version is the only that worked in my phone so far! Here are some screenshots.
> 
> Valeu cara, vc é top.
> 
> ![Screenshot_20210327-212454.png](https://user-images.githubusercontent.com/57275984/112738780-dd671300-8f44-11eb-8d37-b879e475deb3.png)
> ![Screenshot_20210327-213454.png](https://user-images.githubusercontent.com/57275984/112738784-e22bc700-8f44-11eb-960a-d726b2c2a01c.png)

lixo feliz :)

**Comment by DanisLixo** [comment]
@luckydog7 label this issue as enhancement

**Comment by Caco-o-sapo** [comment]
Oi cara, só pra avisar, o link do FNF minha Lite tá quebrado aqui...

**Comment by DanisLixo** [comment]
corrigindo bugs

**Comment by NailyFromBFB** [comment]
When I try to download the minus mod, it shows this:
![Screenshot_20210328-150811](https://user-images.githubusercontent.com/79092777/112764640-865e4e00-8fd7-11eb-9be9-d7717faef6c9.jpg)

**Comment by NeonNotFound** [comment]
Thanks bro my game is not crashing anymore

**Comment by ILoveFnF** [comment]
> Funk (Outdated): https://www.mediafire.com/download/znir293cd4zlcpv
> 
> Bugs:
> Game crashes (sometimes)
> Black texture (maybe)
> Cocoa and Eggnog is not working (I'll solve it in a little while)
> In the selection of weeks, the BF is all there
> Im alive (Yes, this is a bug)
> The BF doesn't have his Death animation (idle BF)
> The train never existed
> gfChristmas.png now it's in Low Quality (aaaaaaaaaa)
> Added:
> Your mom (not really)
> Deleted:
> the incredible unnecessary files
> 
> Funk Low End Phones: https://www.mediafire.com/download/2gut4lcwrm5mll5
> 
> Bugs:
> game crashes (sometimes on week 4, and Cocoa and Eggnog 100%)
> Black texture (rare)
> I'm still alive (buuuuug)
> 
> Warning: The characters (BF, GF, Dad, Spooky kids and pico) are too small, And the GF does nothing, she just dances :|
> 
> Funkied (outdated): https://www.mediafire.com/download/yws6rkr202ahvyo
> 
> Changed:
> Week 5 is now working (I just deleted the Mom and Dad)
> GF Xmas event still without quality 👍
> 
> Bugs:
> Game crashes
> yaaaaaaaaaay
> 
> FNF Minus Lite: https://www.mediafire.com/download/hq3y1siby9w29to
> 
> Changed:
> just deleted the GF and the parents
> Week 5 is now working
> Week 6 too
> 
> Bugs:
> week 4 (still playable)
> game crashes
> black Textures (rare)
> 
> Special Thanks:
> Hadobedo (FunkiniOS): For the sprites of the Low End version.
> Ninjamuffin99: For leaving the source code of the old versions still available.
> Luckydog7: for the port sent it well man, keep up the good work!
> Ibis Paint: Mods.
> P.S.: cara do tijolinho.

Oofs (minus mod lite version) 
![Screenshot_20210330_135836_com ninjamuffin99 funkinminus](https://user-images.githubusercontent.com/81518836/112978644-4676a280-9160-11eb-965b-216b9536d9bd.jpg)

**Comment by BoyfriendFNF** [comment]
can you update the lite version to the hitbox update?

**Comment by BoyfriendFNF** [comment]
> Lite version update
> 
> https://www.mediafire.com/file/3fqxt4jkncnffbc/funked.apk/file
> @BoyfriendFNF

yeah I found out a few hours ago that it got updated, but I still am waiting for the lite bside version

**Comment by zamirdaguer** [comment]
Here is the apk editor homie!
https://apk-editor.uptodown.com/android
B sides.
https://gamebanana.com/gamefiles/13686

Al you need to do is replace the folder un the file and Presto! B sides installed!

**Comment by zamirdaguer** [comment]
There is no other way

**Comment by zamirdaguer** [comment]
I searched fnf b sides apk in google AND nothing

**Comment by NoobJsPerson** [comment]
Can u make a seperate repository for this version it'll be better for future updates (if you're planning on making them)

**Comment by DanisLixo** [comment]
how do I do that?

**Comment by NoobJsPerson** [comment]
Fork the repository and then commit the changes u did

**Comment by DanisLixo** [comment]
but I only modify the assets

**Comment by NoobJsPerson** [comment]
Oke makes sense :)

**Comment by Caco-o-sapo** [comment]
But still, it makes more sense, since you're doing different versions and it can be used as base for the FNF android modded apks

**Comment by DanisLixo** [comment]
fuck

**Comment by DanisLixo** [comment]
> But still, it makes more sense, since you're doing different versions and it can be used as base for the FNF android modded apks

but I prefer to leave it here just as an issue, it would help if Luckydog labels it as an enhancement

**Comment by ILoveFnF** [comment]
Is it possible to make the port lite version of minus mod? Because the lite shows black sprites for me

**Comment by zamirdaguer** [comment]
@Boyfriendfnf here is apk file https://mega.nz/file/U0xiUC6B#EMs5UxzR1yZGcD3RPUE8gqmqplvmSErU_merLKMZSFk

**Comment by BoyfriendFNF** [comment]
> @BoyfriendFNF here is apk file https://mega.nz/file/U0xiUC6B#EMs5UxzR1yZGcD3RPUE8gqmqplvmSErU_merLKMZSFk
is that the lite version of bside

**Comment by ZzayedD0129** [comment]
i made b3 remixed mod fnf of lite version


(https://www.mediafire.com/file/08ppm689dc4bd8k/B3_remixed_fnf.apk/file)

**Comment by Caco-o-sapo** [comment]
> i made b3 remixed mod fnf of lite version
> 
> 
> (https://www.mediafire.com/file/08ppm689dc4bd8k/B3_remixed_fnf.apk/file)

Man, idk if it's something but I found that the spooky month week songs are switched with the senpai ones. But the rest seems fine.

**Comment by BoyfriendFNF** [comment]
> i made b3 remixed mod fnf of lite version
> 
> (https://www.mediafire.com/file/08ppm689dc4bd8k/B3_remixed_fnf.apk/file)

cool

**Comment by ZzayedD0129** [comment]
Ok everyone i fixed b3 remixed the spooky month week songs are switched with the senpai
https://www.mediafire.com/file/8mp3y31g42qom8z/B3_remixed_fnf_fixed.apk/file

**Comment by woaa12** [comment]
> @BoyfriendFNF here is apk file https://mega.nz/file/U0xiUC6B#EMs5UxzR1yZGcD3RPUE8gqmqplvmSErU_merLKMZSFk

Every week but not week 6 isn't working

**Comment by kffwlp** [comment]
Is this the newest version?

**Comment by BoyfriendFNF** [comment]
> Is this the newest version?

yes it was updated to have hitbox control

**Comment by Crunchyyy456** [comment]
> > Is this the newest version?
> 
> yes it was updated to have hitbox control 

I think he meant the base low end version not yours

**Comment by Ralphy999** [comment]
> Funk Low End Phones: https://www.mediafire.com/download/2gut4lcwrm5mll5
> 
> Bugs:
> game crashes (sometimes on week 4, and Cocoa and Eggnog 100%)
> Black texture (rare)
> I'm still alive (buuuuug)
> 
> Warning: The characters (BF, GF, Dad, Spooky kids and pico) are too small, And the GF does nothing, she just dances :|
> 
> friday nights at funkin: https://www.mediafire.com/download/p7jfrv12kou842o
> 
> Changed:
> Week 5 is now working (I just deleted the Mom and Dad)
> GF Xmas event still without quality 👍
> 
> Bugs:
> Game crashes (sometimes)
> Black texture (maybe)
> Im alive (Yes, this is a bug)
> The BF doesn't have his Death animation (idle BF)
> The train never existed
> yaaaaaaaaaay
> 
> added:
> Hitbox
> 
> FNF Minus Lite: https://www.mediafire.com/download/hq3y1siby9w29to
> 
> Changed:
> just deleted the GF and the parents
> Week 5 is now working
> Week 6 too
> 
> Bugs:
> week 4 (still playable)
> game crashes
> black Textures (rare)
> 
> Special Thanks:
> Hadobedo (FunkiniOS): For the sprites of the Low End version.
> Ninjamuffin99: For leaving the source code of the old versions still available.
> Luckydog7: for the port sent it well man, keep up the good work!
> Ibis Paint: Mods.
> P.S.: cara do tijolinho.

The minus mod lite doesn't work boyfriend is still black square

**Comment by ILoveFnF** [comment]
Same

**Comment by Ralphy999** [comment]
> Funk Low End Phones: https://www.mediafire.com/download/2gut4lcwrm5mll5
> 
> Bugs:
> game crashes (sometimes on week 4, and Cocoa and Eggnog 100%)
> Black texture (rare)
> I'm still alive (buuuuug)
> 
> Warning: The characters (BF, GF, Dad, Spooky kids and pico) are too small, And the GF does nothing, she just dances :|
> 
> friday nights at funkin: https://www.mediafire.com/download/p7jfrv12kou842o
> 
> Changed:
> Week 5 is now working (I just deleted the Mom and Dad)
> GF Xmas event still without quality 👍
> 
> Bugs:
> Game crashes (sometimes)
> Black texture (maybe)
> Im alive (Yes, this is a bug)
> The BF doesn't have his Death animation (idle BF)
> The train never existed
> yaaaaaaaaaay
> 
> added:
> Hitbox
> 
> FNF Minus Lite: https://www.mediafire.com/download/hq3y1siby9w29to
> 
> Changed:
> just deleted the GF and the parents
> Week 5 is now working
> Week 6 too
> 
> Bugs:
> week 4 (still playable)
> game crashes
> black Textures (rare)
> 
> Special Thanks:
> Hadobedo (FunkiniOS): For the sprites of the Low End version.
> Ninjamuffin99: For leaving the source code of the old versions still available.
> Luckydog7: for the port sent it well man, keep up the good work!
> Ibis Paint: Mods.
> P.S.: cara do tijolinho.

In the low end funk i dont crash in any week its just black squares on week 5

**Comment by DanisLixo** [comment]
next update, lite versions of mods already ported :)

**Comment by Ralphy999** [comment]
Is the new update already here

**Comment by DanisLixo** [comment]
no im joking lol

**Comment by Ralphy999** [comment]
Ow ok:(

**Comment by Ralphy999** [comment]
> next update, lite versions of mods already ported :)

Uhh what mods

**Comment by ILoveFnF** [comment]
Bruh

**Comment by Ralphy999** [comment]
> Bruh

Wat

**Comment by BoyfriendFNF** [comment]
I'm still waiting for bside lite

**Comment by Ralphy999** [comment]
> I'm still waiting for bside lite

Same

**Comment by kffwlp** [comment]
In the lite version gf is missing (but appears in week 4)

**Comment by DanisLixo** [comment]
> In the lite version gf is missing (but appears in week 4)

no, Friday Nights at Funkin' has gf every week

**Comment by kffwlp** [comment]
> > In the lite version gf is missing (but appears in week 4)
> 
> no, Friday Nights at Funkin' has gf every week

I guess my phone isn't strong enough

**Comment by wafflemaster13** [comment]
i give this a seal of approval because i was able to play on my tablet thats soo slow it cant even play the normal version it crashs when i go to storymode but not this this works better on my tablet now

**Comment by BoyfriendFNF** [comment]
> i give this a seal of approval because i was able to play on my tablet thats soo slow it cant even play the normal version it crashs when i go to storymode but not this this works better on my tablet now

that's exactly why lite version exists and it probably makes everyone's day better without the crashing

**Comment by wafflemaster13** [comment]
> Funk Low End Phones: https://www.mediafire.com/download/2gut4lcwrm5mll5
> 
> Bugs:
> game crashes (sometimes on week 4, and Cocoa and Eggnog 100%)
> Black texture (rare)
> I'm still alive (buuuuug)
> 
> Warning: The characters (BF, GF, Dad, Spooky kids and pico) are too small, And the GF does nothing, she just dances :|
> 
> friday nights at funkin: https://www.mediafire.com/download/p7jfrv12kou842o
> 
> Changed:
> Week 5 is now working (I just deleted the Mom and Dad)
> GF Xmas event still without quality 👍
> 
> Bugs:
> Game crashes (sometimes)
> Black texture (maybe)
> Im alive (Yes, this is a bug)
> The BF doesn't have his Death animation (idle BF)
> The train never existed
> yaaaaaaaaaay
> 
> added:
> Hitbox
> 
> FNF Minus Lite: https://www.mediafire.com/download/hq3y1siby9w29to
> 
> Changed:
> just deleted the GF and the parents
> Week 5 is now working
> Week 6 too
> 
> Bugs:
> week 4 (still playable)
> game crashes
> black Textures (rare)
> 
> Special Thanks:
> Hadobedo (FunkiniOS): For the sprites of the Low End version.
> Ninjamuffin99: For leaving the source code of the old versions still available.
> Luckydog7: for the port sent it well man, keep up the good work!
> Ibis Paint: Mods.
> P.S.: cara do tijolinho.

uhm you said youve added the hitbox why is it not showing as an option ive tested out on both used my chromebook too see if it would work on the normal mobile mode and ya it works and i can see the hitbox controls but they wont show on both minus and normal mods

**Comment by DanisLixo** [comment]
the low end version is an outdated version, I don't want to update it until I can use textureDownsize.py.
the Minus mod, it was done before the hitbox update.
