### ISSUE TITLE
Can someone make high effort ugh tankman over pico? 

### ISSUE THREAD

**Issue by DzGithub2805** [luckydog7/Funkin-android#1528]
Here is the steps
1. Download high effort ugh 2.0
2. Drag the tankman image and xml
3. Edit the xml to pico (no need ugh animation) 
4. Test it if it worked
5. If it worked, give it to me

Please guys, i really need it

**Comment by JoseGithubFNF** [comment]
😌 Here https://youtu.be/hFthnj67HWk Also This Isn't My Mod Someone Made This!

**Comment by DzGithub2805** [comment]
No, this used tankman over pico

**Comment by DzGithub2805** [comment]
I wanted high effort tankman over pico

**Comment by JoseGithubFNF** [comment]
> I wanted high effort tankman over pico

> I wanted high effort tankman over pico

Bruh Well Mostly That Is Impossible Unless If Someone Smarter Well Uh Yeah
