### ISSUE TITLE
Does someone have a Zardy Foolhardy mod they can share, or is it really hard to do?

### ISSUE THREAD

**Issue by Adzen927** [luckydog7/Funkin-android#153]
Would really like a Zardy FoolHardy Mod! (also not to be picky but can there be one with latest version so I can change controls?) if not that's fine, I'll take any version.

**Comment by DanisLixo** [comment]
Okay, I do it and see if it is passable

**Comment by woaa12** [comment]
https://youtu.be/d3ML5235o8w

**Comment by Adzen927** [comment]
> nevermind :)

Thank you so much! Have a great day!

**Comment by Adzen927** [comment]
Another problem, whenever trying to open the mod Zardy Foolhardy, and atleast play it it crashes instantly so I can't play it, can someone delete all the files except for the Zardy Foolhardy or make it somewhat playable?

**Comment by woaa12** [comment]
Delete the backround it crashes because of that

**Comment by Adzen927** [comment]
> Delete the backround it crashes because of that

Worked, thanks!
