### ISSUE TITLE
DO YOU WANT A CHANGED MOD

### ISSUE THREAD

**Issue by ZzayedD0129** [luckydog7/Funkin-android#1539]
WARNING: Please upload mod into discussion
https://github.com/luckydog7/Funkin-android/discussions 
On here

**Comment by ZzayedD0129** [comment]
BITCHYBITCH123 IF YOU WANT THE CHANGED MOD

**Comment by dufuw** [comment]
BITCHYBITCH123

**Comment by ZzayedD0129** [comment]
> BITCHYBITCH123

@LukeyKing123
