### ISSUE TITLE
How to add custom weeks/songs to main menu

### ISSUE THREAD

**Issue by CCGameing** [luckydog7/Funkin-android#156]
I was using @DanisLixo 's lite version of the game (#86) and wanted to try to make a custom song. The only problem is I don't know how to add the song to the menu. And I couldn't find the right tutorial on yt so I figured I'd ask here. Example: in the whitty mod they add a bonus week button at the end of the story mode (instead of replacing a week). That's basically what I'm trying to do.

**Comment by Rs232k** [comment]
Weeks hardcoded, it means you need to compile fnf with added week.

**Comment by CCGameing** [comment]
> Weeks hardcoded, it means you need to compile fnf with added week.

How do I do that? I know how to add the files and stuff if that's what you mean.

**Comment by CCGameing** [comment]
> Weeks hardcoded, it means you need to compile fnf with added week.

Oh you mean the code. Yeah I don't know how to do that.

**Comment by CCGameing** [comment]
I found the files the code is in, but how do I code it?

**Comment by Rs232k** [comment]
> I found the files the code is in, but how do I code it?

Use tutorials on youtube. I found "How to add weeks in fnf"

**Comment by CCGameing** [comment]
> Use tutorials on youtube. I found "How to add weeks in fnf"

Can u link it?

**Comment by Rs232k** [comment]
> > Use tutorials on youtube. I found "How to add weeks in fnf"
> 
> Can u link it?

Tried https://youtu.be/lIIDceOC9fw

**Comment by CCGameing** [comment]
> Tried https://youtu.be/lIIDceOC9fw

I don't have the exact same files as they do, but I found similar files.

![Screenshot_20210327-135416](https://user-images.githubusercontent.com/81330047/112729668-c94ef180-8f03-11eb-94ae-a0a6c6e520b2.png)
![Screenshot_20210327-135602](https://user-images.githubusercontent.com/81330047/112729669-c9e78800-8f03-11eb-860d-1060e00ddf67.png)

Beep

**Comment by Rs232k** [comment]
Download source code, edit, use pc for compile

**Comment by CCGameing** [comment]
> Download source code, edit, use pc for compile
> 
> * Watch first video in description.

I no have pc :(
But I think I can work around it.

**Comment by CCGameing** [comment]
I give up, I tried to add stuff and mod it and it screwed it all up. It took me a while just to get it back to the original.
