### ISSUE TITLE
Just a question from some peep who wants to code and program from android

### ISSUE THREAD

**Issue by Yoshiakidemi10** [luckydog7/Funkin-android#1563]
As the title, I was questioning if the people on android or ect... Can program code and ect... In the own device?

**Comment by mcagabe19** [comment]
türkmüsün sen sjsjsjs

**Comment by HighFlyer-222** [comment]
i'm a coder with only a phone and yes you can actually code on android, but the possibilities are very limited compared to what you can do on a pc (i had a pc before so i can safely say that)

actually, why are you asking this question

**Comment by Yoshiakidemi10** [comment]
Well, because I was curious about it
