### ISSUE TITLE
Week 5 black screen (new bug)

### ISSUE THREAD

**Issue by lilpichu** [luckydog7/Funkin-android#1583]
**Describe the bug**
Ok, look. The Week 5 now opens, but every time it's turn of gf's mom, then happens the obviously black screen. I can play with this, of course! It's a challenge complete week 5 without seeing. But I really want to have a answer with this.
My phone is Xiaomi Redmi 8A, 2 GB RAM, all day haves 900+ MB of RAM, so I think this is not the problem :c

**To Reproduce**
1. Go to 'Story Mode'
2. Click on 'Week 5'
3. Play with Daddy Dearest and bf
4. See error when it's turn of gf's mom

**Screenshots**

**Additional context**
Hmm, it haves some lag, but I think it's normal.

**Comment by NeonNotFound** [comment]
Thats a ram problem and your phone is not strong enough to play fnf android

**Comment by Luc4s-adv** [comment]
> **Descreva o bug**
> Ok, olhe. A Semana 5 agora abre, mas toda vez que é a vez da mãe de gf, aparece a tela obviamente preta. Posso brincar com isso, é claro! É um desafio completo na semana 5 sem ver. Mas eu realmente quero ter uma resposta com isso.
> Meu telefone é Xiaomi Redmi 8A, 2 GB de RAM, o dia todo tem mais de 900 MB de RAM, então acho que esse não é o problema: c
> 
> **Para reproduzir as**
> etapas para reproduzir o comportamento:
> 
> 1. Vá para 'Modo História'
> 2. Clique em 'Semana 5'
> 3. Brinque com o querido papai e bf
> 4. Veja o erro quando for a vez da mãe da gf
> 
> **Capturas de tela**
> Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.
> 
> **Contexto adicional**
> Hmm, tem algum atraso, mas acho que é normal.

this is not a bug, this is your ram, you must have at least 3 GB RAM, to play week 5, or look for an Optimized version for low end
