### ISSUE TITLE
Suggest any mod to optimize

### ISSUE THREAD

**Issue by HatsuneMiku-github** [luckydog7/Funkin-android#1595]
I'm bored so please suggest any mod I could optimize

Also should I make a YouTube channel for the mods I Optimize

**To do list:**

Tiky over boyfriend optimized

Tricky v2 but bad

**Comment by OOOboyfriend2835** [comment]
Ooooooohhh i want tiny of bg

**Comment by HatsuneMiku-github** [comment]
> Ooooooohhh i want tiky over bf

Sure

**Comment by OOOboyfriend2835** [comment]
TRicky v2 but bad

**Comment by HatsuneMiku-github** [comment]
> TRicky v2 but bad

Sure

**Comment by OOOboyfriend2835** [comment]
> > TRicky v2 but bad
> 
> Sure

Yooooooooooooo

**Comment by OOOboyfriend2835** [comment]
FNB (Friday night bloxxin)

**Comment by OOOboyfriend2835** [comment]
Pls it's my favorite mod

**Comment by OOOboyfriend2835** [comment]
I'm taking a break so u r do it for me pls

**Comment by HatsuneMiku-github** [comment]
> FNB (Friday night bloxxin)

Ok

**Comment by OOOboyfriend2835** [comment]
Neo + b sides (separate apps)

**Comment by OOOboyfriend2835** [comment]
> > FNB (Friday night bloxxin)
> 
> Ok

Tank you U G H (tankman meme lol)

**Comment by OOOboyfriend2835** [comment]
> I'm bored so please suggest any mod I could optimize
> 
> Also should I make a YouTube channel for the mods I Optimize
> 
> **To do list:**
> 
> Tiky over boyfriend optimized
> 
> Tricky v2 but bad
Friday night bloxxin
I made it in cuz u didnt

**Comment by OOOboyfriend2835** [comment]
> > I'm bored so please suggest any mod I could optimize
> > Also should I make a YouTube channel for the mods I Optimize
> > **To do list:**
> > Tiky over boyfriend optimized
> > Tricky v2 but bad
> > Friday night bloxxin
> 

🗡️

**Comment by HatsuneMiku-github** [comment]
> > > I'm bored so please suggest any mod I could optimize
> > > Also should I make a YouTube channel for the mods I Optimize
> > > **To do list:**
> > > Tiky over boyfriend optimized
> > > Tricky v2 but bad
> > > Friday night bloxxin
> 
> 🗡️

????

**Comment by OOOboyfriend2835** [comment]
> > > > I'm bored so please suggest any mod I could optimize
> > > > Also should I make a YouTube channel for the mods I Optimize
> > > > **To do list:**
> > > > Tiky over boyfriend optimized
> > > > Tricky v2 but bad
> > > > Friday night bloxxin
> > 
> > 
> > 🗡️
> 
> ????

U didn't add fnb to the to do list so I did

**Comment by HatsuneMiku-github** [comment]
> > > > > I'm bored so please suggest any mod I could optimize
> > > > > Also should I make a YouTube channel for the mods I Optimize
> > > > > **To do list:**
> > > > > Tiky over boyfriend optimized
> > > > > Tricky v2 but bad
> > > > > Friday night bloxxin
> > > 
> > > 
> > > 🗡️
> > 
> > 
> > ????
> 
> U didn't add fnb to the to do list so I did

Ohhhh

**Comment by HatsuneMiku-github** [comment]
Issues with life might reopen this because I'm taking a break

**Comment by OOOboyfriend2835** [comment]
> Issues with life might reopen this because I'm taking a break

:(
