### ISSUE TITLE
Error: ".../Android/libextension-webm-v7.so" does not exist

### ISSUE THREAD

**Issue by codingwatching** [luckydog7/Funkin-android#1598]
I just follow readme and run 
 lime build android -final
But have error:
Error: Source path "/usr/local/lib/haxe/lib/extension-webm/git/ndll/Android/libextension-webm-v7.so" does not exist

Please help!
Thank you very much!

**Comment by mcagabe19** [comment]
lib file must be deleted or corrupt

**Comment by codingwatching** [comment]
Hi @mcagabe19 
I can not find any document to build libextension-webm-v7.so for android again.
Could you please send me the file or document that shows how to compile it?
Thank you so much!

**Comment by mcagabe19** [comment]
I don't know anything about haxeflixel or lime sorry :(

**Comment by VelocityK9** [comment]
Try  "lime rebuild extension-webm android"

**Comment by codingwatching** [comment]
@VelocityK9 thank you for the help
When running that command I get this error:
```
Error: Please set one of the architectures, eg HXCPP_ARM64, HXCPP_X86, ...
```

**Comment by codingwatching** [comment]
@VelocityK9 Thank you so much I fix above error by changing ndk to android-ndk-r15c
