### ISSUE TITLE
Vs Sunday Optimized

### ISSUE THREAD

**Issue by mcagabe19** [luckydog7/Funkin-android#1599]
let's go

link:https://cntr.click/18rwLAR
gameplay:https://youtu.be/ZoospcX1Zq0

enjoy!

Screenshots
![Screenshot_2021-07-05-10-28-55-706.jpeg](https://user-images.githubusercontent.com/82843871/124438073-6c739a80-dd80-11eb-8c7b-39593fe43f73.jpeg)
![Screenshot_2021-07-05-10-29-20-213.jpeg](https://user-images.githubusercontent.com/82843871/124438094-71d0e500-dd80-11eb-947e-0ba43e8e0a68.jpeg)

**Comment by Kappandrew** [comment]
POV:Boyfriend has Schizophrenia

**Comment by mcagabe19** [comment]
> POV:Boyfriend has Schizophrenia

XD

**Comment by kffwlp** [comment]
Is it possible to optimize the sprites without removing them?

**Comment by AGuyLucky** [comment]
Yes

**Comment by mcagabe19** [comment]
yea

**Comment by kffwlp** [comment]
nice i might try to make that

**Comment by AGuyLucky** [comment]
You need create a xml and optimized Sprite

**Comment by CreatorOlixter** [comment]
VS Sunday but There's no Sunday

**Comment by mcagabe19** [comment]
> You need create a xml and optimized Sprite 

yeah
