### ISSUE TITLE
What the...

### ISSUE THREAD

**Issue by mcagabe19** [luckydog7/Funkin-android#1600]
![Screenshot_2021-07-05-15-50-25-505.jpeg](https://user-images.githubusercontent.com/82843871/124474109-cf792780-dda8-11eb-85e6-7cdd0c7d4785.jpeg)

**Comment by zacksgamerz** [comment]
So you're basically saying that your antivirus detected that pretty much EVERY ANTIVIRUS YOU HAVE has a trojan. This doesn't have any connections to the port. Closing

**Comment by mcagabe19** [comment]
> So you're basically saying that your antivirus detected that pretty much EVERY ANTIVIRUS YOU HAVE has a trojan. This doesn't have any connections to the port. Closing

okey
