### ISSUE TITLE
BUG!

### ISSUE THREAD

**Issue by ANIMEXartwork** [luckydog7/Funkin-android#1636]
**Describe the bug**
When selecting Down Scroll the down arrow is pointing up

**To Reproduce**
1. Go to settings
2. Click on preferences 
3. Scroll down to down scroll 
4. Down arrow points up instead of down

**Expected behavior**
The arrow is supposed to point down not up lol

![Screenshot_20210708-153402](https://user-images.githubusercontent.com/87150885/124987030-faaa8380-e001-11eb-9595-06aea1a8c4e1.jpg)

**Comment by OOOboyfriend2835** [comment]
READ THE DESCRIPTION

**Comment by ANIMEXartwork** [comment]
> READ THE DESCRIPTION
> ![Screenshot_2021-07-08-16-17-30](https://user-images.githubusercontent.com/83379021/124992158-4102e100-e008-11eb-81ab-d2f12485dbb3.jpg)
> A L I T T L E B R O K E N

Ok thx

**Comment by OOOboyfriend2835** [comment]
Can you post the link for your health icons pls

**Comment by Gamich228** [comment]
Wat
