### ISSUE TITLE
Kapi mod

### ISSUE THREAD

**Issue by Sushi435** [luckydog7/Funkin-android#1646]
does anyone have the kapi mod? (preferably a port just like the PC)

**Comment by Kappandrew** [comment]
The mod request tag exists for a reason

**Comment by Sushi435** [comment]
> Uma tag de solicitação do mod existe por um motivo

Sorry..

**Comment by Sushi435** [comment]
> A tag de solicitação do mod existe por um motivo

This label is not appearing for me :(

**Comment by lilpichu** [comment]
https://www.mediafire.com/file/7ohktne9whurabk/Vs+Kapi+By+Kaique62+Bug+fixed.apk/file
Here is it!

**Comment by zamirdaguer** [comment]
> https://www.mediafire.com/file/7ohktne9whurabk/Vs+Kapi+By+Kaique62+Bug+fixed.apk/file
> Here is it!

it crashes bruh

**Comment by DiosDonutSlave** [comment]
> https://www.mediafire.com/file/7ohktne9whurabk/Vs+Kapi+By+Kaique62+Bug+fixed.apk/file
> Here is it!

yeah but its basically trash on base engine, needs kade or gamerbross engine
