### ISSUE TITLE
Vs Sketchy mod full week

### ISSUE THREAD

**Issue by Tonate12** [luckydog7/Funkin-android#1654]
https://drive.google.com/file/d/1g--Bap5MHtOwnJ0K1PB5N-1En90578U-/view

**Comment by FridayNightSans** [comment]
Bro, credit the maker. I already knew you are stolen this mod

**Comment by FridayNightSans** [comment]
https://youtu.be/XIhXNbV0rFc
Here and credit him

**Comment by Tonate12** [comment]
Sorry

**Comment by Tonate12** [comment]
Idk how to make a mod tho on android:(
