### ISSUE TITLE
I found the PERFECT port of kapi mod but...

### ISSUE THREAD

**Issue by Sushi435** [luckydog7/Funkin-android#1655]
It didn't work properly on my cell phone (2 gb RAM and 32 bit) can anyone make the optimized version to work in this config? Here's the link: https://drive.google.com/file/d/1rgR7as7NIOPri5slMCqmTe7qRaCNq7dU/view?usp=drivesdk

**Comment by FridayNightSans** [comment]
Credits it, i already knew u just take from Daninocent

**Comment by ItzLiquid** [comment]
> Credits it, i already knew u just take from Daninocent

He/She might have forgot to credit it-

**Comment by Sushi435** [comment]
> > Créditos isso, eu já sabia que você acabou de tirar do Daninocent
> 
> Ele / ela pode ter esquecido de dar crédito a isso-

i didn't know who did it, i just found the download

**Comment by Sushi435** [comment]
But, can anyone make the optimized version? (Please)

**Comment by Sushi435** [comment]
> > Créditos isso, eu já sabia que você acabou de tirar do Daninocent
> 
> Ele / ela pode ter esquecido de dar crédito a isso-

anyway, can anyone do? (please)
