### ISSUE TITLE
e

### ISSUE THREAD

**Issue by MrClogsworthYT** [luckydog7/Funkin-android#1675]
#1

**Comment by ZzayedD0129** [comment]
![٢٠٢١٠٧١١_٢١٠٤٣٦](https://user-images.githubusercontent.com/80968258/125452483-f9f26105-0a8c-4cc3-b064-314fac6b34c8.jpg)

**Comment by nattangomes** [comment]
https://user-images.githubusercontent.com/80545941/125463434-150d6ab8-4047-4949-b5ae-e182a35efa7f.mp4

**Comment by ZzayedD0129** [comment]
> 
> https://user-images.githubusercontent.com/80545941/125463434-150d6ab8-4047-4949-b5ae-e182a35efa7f.mp4
> 
> 

![تنزيل (1).jpeg](https://user-images.githubusercontent.com/80968258/125683713-4c5cf7ba-100e-423d-8df5-45e2cdb852aa.jpeg)

**Comment by Gamich228** [comment]
Привет

**Comment by nattangomes** [comment]
n
