### ISSUE TITLE
Better Button Placements Mock-Up (Suggestion and Improvement)

### ISSUE THREAD

**Issue by superguyoffa** [luckydog7/Funkin-android#17]
I really dislike the default button layout, its very uncomfortable to play with. If there was a way to change them or have an options menu would be really nice. I made a mock-up of what would be a way better control layout, was too lazy to make the arrows transparent but that would be needed as well.

![image](https://user-images.githubusercontent.com/78882471/109391692-a6d3b380-7918-11eb-88f6-33ccf9ef6fce.png)

With this control layout, you could easily press 2 arrows at once with both hands that are at either side. And it's a lot more comfortable. Especially helpful in tracks like Thorns.

**Comment by HikariError** [comment]
Yoooo that's better!

**Comment by luckydog7** [comment]
https://github.com/luckydog7/Funkin-android/issues/16
check last comment
