### ISSUE TITLE
Request any mod and I will make a android port of it | Mod Being Created: Vs Camellia | Choosen by https://wheelgenerator.com/

### ISSUE THREAD

**Issue by Alec025** [luckydog7/Funkin-android#1727]
I would love to make more fnf mods for android I will only do the mods when I have time one of the mods I have done is the [garcello mod](https://github.com/luckydog7/Funkin-android/issues/1676) please suggest mods for me to do! If i can.
I will be fair and choose it by spin the wheel it will go by first to 3
Mod Being Created: Vs Camellia

**Comment by DiosDonutSlave** [comment]
The HD mod with week 5

**Comment by DabKnight** [comment]
Vs Camellia:
https://gamebanana.com/mods/290601
Or Vs. King:
https://gamebanana.com/mods/293158

**Comment by HatsuneMiku-github** [comment]
The kapi mod?

**Comment by Goaisim** [comment]
Starecrown full week

**Comment by blazingcody** [comment]
VS Cassandra
https://gamebanana.com/mods/286853

**Comment by HatsuneMiku-github** [comment]
Vs. FC demo?

**Comment by MrClogsworthYT** [comment]
what about fnf parapa the rapper?

**Comment by CalibriLight** [comment]
https://gamebanana.com/mods/309446 rly insteresting thing for low end phones

**Comment by Darrylebat228** [comment]
> Vs Camellia:
> https://gamebanana.com/mods/290601
> Or Vs. King:
> https://gamebanana.com/mods/293158

Vs. king.
