### ISSUE TITLE
Can Someone Add Down Scroll to Tricky Mod V2 Android Port Pls 

### ISSUE THREAD

**Issue by AnSmileyFace** [luckydog7/Funkin-android#1801]
For some reason luckydog removed it (it's on the pc version) 
It's my preferred way to play if it's easy to add can someone add it pls

Thx in advance

**Comment by DabKnight** [comment]
1.open a song in the tricky mod
2.flip your phone upside down
There you go.

**Comment by Hurbmoment** [comment]
> 1.open a song in the tricky mod
> 2.flip your phone upside down
> There you go.

when id use downscroll its self itd go to upscroll.
