### ISSUE TITLE
BUG! black screen at start (nothing happens ) but the music plays

### ISSUE THREAD

**Issue by tposejank** [luckydog7/Funkin-android#1822]
**this issue has duplicates?**
Black textures - https://github.com/luckydog7/Funkin-android/issues/12 (max texture size problem)
Crash - https://github.com/luckydog7/Funkin-android/issues/10 (ram problem)

**Describe the bug**

**To Reproduce**

**Expected behavior**

I expected the game to start

**Screenshots**

Just a black screen with the music

**Additional context**

I compiled the game and followed all the steps but when It finished compiling after 1 hour and 20 minutes and I installed the apk in my phone nothing happened

**Comment by koteelok** [comment]
same for me.
