### ISSUE TITLE
Can someone PLEASE help me with this error.

### ISSUE THREAD

**Issue by AwesomeDlind** [luckydog7/Funkin-android#1846]
I don't know if this falls under compiling help or not but umm I have an issue, I do lime rebuild extension-webm android but get this error: ' Error: Please set one of the architectures, eg HXCPP_ARM64, HXCPP_X86, ... '
Could I have some help working this issue out.
![image](https://user-images.githubusercontent.com/89957764/132174067-add5bd5a-9c36-4bed-bac2-1f96bfac2a9b.png)

**Comment by zzahkaboom24** [comment]
Make sure your Ndk is revision 15c, i had the same problem and it was cuz i have properly read that one small part. it has to be revision 15c

**Comment by zzahkaboom24** [comment]
https://dl.google.com/android/repository/android-ndk-r15c-windows-x86_64.zip

youll need this version

**Comment by zzahkaboom24** [comment]
after you unzipped that, type lime setup android in your cmd and change the Path to Android NDK to the unzipped one now

**Comment by AwesomeDlind** [comment]
Very late time to close it but this was solved by zzahkaboom24.
Thanks for the support.
