### ISSUE TITLE
Notes lagging while Bluetooth headphones are connected

### ISSUE THREAD

**Issue by D3MONSLAY3R101** [luckydog7/Funkin-android#1907]
**this issue has duplicates?**
Black textures - https://github.com/luckydog7/Funkin-android/issues/12 (max texture size problem)
Crash - https://github.com/luckydog7/Funkin-android/issues/10 (ram problem)

**Describe the bug**
When I play FNF while I have Bluetooth headphones connected the notes lag.

**To Reproduce**
1. Connect Bluetooth headphones
2. Play any song
3. The notes will be lagging

**Expected behavior**
The notes moving smoothly

**Screenshots**
NONE
**Additional context**
NONE

**Comment by OOOboyfriend2835** [comment]
Solution: disconnect. Break them. Waste $500 on wired headphones. Enjoy!

**Comment by D3MONSLAY3R101** [comment]
I fixed the problem... I got a new phone and FNF works fine with Bluetooth headphones now :)
