### ISSUE TITLE
Uhhh....

### ISSUE THREAD

**Issue by zsidebf** [luckydog7/Funkin-android#1914]
![Untitled1_20211202194844](https://user-images.githubusercontent.com/83379021/144530884-bb5bb90b-f109-493b-9b47-15be8698ef46.png)
What?

**Comment by OOOboyfriend2835** [comment]
I have no idea how this is legal......

**Comment by Hurbmoment** [comment]
illegal, how the fuck would you get a "PS5" for free

**Comment by Hurbmoment** [comment]
> illegal, how the fuck would you get a "PS5" for free

Wait a minute.

**Comment by zsidebf** [comment]
> > illegal, how the fuck would you get a "PS5" for free
> 
> Wait a minute.

Bruh its a joke. I used a inspect element

**Comment by zsidebf** [comment]
So yeah
