### ISSUE TITLE
It crashed when i play

### ISSUE THREAD

**Issue by Noobandguestgang** [luckydog7/Funkin-android#1919]
It worked fine months hao but now it just showing the fnf x newgrounds and crashed

**Comment by Noobandguestgang** [comment]
Also this is when i compile to add character

**Comment by luckydog7** [comment]
Fixed, i think

**Comment by Noobandguestgang** [comment]
Ok ill go try now

**Comment by luckydog7** [comment]
Yeah

**Comment by luckydog7** [comment]
Fixed

**Comment by luckydog7** [comment]
I think

**Comment by Noobandguestgang** [comment]
Thank you luckydog ill go try it now

**Comment by Noobandguestgang** [comment]
TYSM LUCKYDOG IT WOKED TY TY TY!!!
