### ISSUE TITLE
FNF' Megamix Mod Port (April Fools)

### ISSUE THREAD

**Issue by DanisLixo** [luckydog7/Funkin-android#193]
Megamix kk: https://www.mediafire.com/download/ocz69guxxxewbu9

is in Beta, so it is very small, for now there are some remixes of the bsides I will update and put more remixes on the future.

Bugs:
Game Crashes (REALLY rare)
Black Texture
the tutorial is not working for some reason

enjoy :)

**Comment by woaa12** [comment]
Game crashes because of images being very strong sized, black textures because idk and I also idk about tutorial tho.
