### ISSUE TITLE
Updated multiplayer mod and kade engine? 

### ISSUE THREAD

**Issue by zacksgamerz** [luckydog7/Funkin-android#199]
These two mods will be much needed in terms of people porting their mods or other mods. If you  would kindly make these 2, things will go much more smoothly for people demanding mods. 
Anyways thats just my opinion. If you dont to make it thats fine.

**Comment by BoyfriendFNF** [comment]
the 1st one is because luckydog7 lost the source code to the multiplayer mod

**Comment by zacksgamerz** [comment]
> the 1st one is because luckydog7 lost the source code to the multiplayer mod

Damn.

**Comment by zacksgamerz** [comment]
#312
