### ISSUE TITLE
Is there an Whitty port already?

### ISSUE THREAD

**Issue by ChickenHat23** [luckydog7/Funkin-android#205]
Um i just wanna know that is there already an FNF apk that is full whitty that has cutscenes and its an costume week( didnt replace any weeks).

**If you guys have any links on the apk pls share it here it would be appreciated**

_Thanks_

**Comment by Zizoplays1** [comment]
I actually asked for this, but like we extract mods from the phone files DIRECTLY from the app
(basically what i mean like those nintendo snes, nes, n64 emulator things) and trying it out
I hope @luckydog7 see it

**Comment by ChickenHat23** [comment]
Yeah i tried doing that too but it just crashes after title menu.

I hope @luckydog7  sees it too.
