### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by pressenterreal** [luckydog7/Funkin-android#22]
This isn't really an issue but since github doesn't have any places I can talk to you other than here (at least I don't think) I'm gonna have to write this here. How did you change the version text to have your username on it? I am making a mod and I want to add my name (but keep yours as well) if this is possible without some insane operation of opening, converting, and compressing, then just leave a reply. Thank you!

**Comment by DanisLixo** [comment]
well, it's even simple:
Download the engine;
Download the Android port source code;
Extract the source code;
Import;
Go to source/TitleState.hx;
Go to line 368 (or line 382);
Put " , ' YourName ' ]);
Export the game;
Create an apk with the Android Studio;
Done :)
It's really easy, but it takes a while.

**Comment by AlphawolfXD** [comment]
This guy below me or above me is smart lol

**Comment by pressenterreal** [comment]
> well, it's even simple:
> Download the engine;
> Download the Android port source code;
> Extract the source code;
> Import;
> Go to source/TitleState.hx;
> Go to line 368 (or line 382);
> Put " , ' YourName ' ]);
> Export the game;
> Create an apk with the Android Studio;
> Done :)
> It's really easy, but it takes a while.

Well damn I have a chromebook so it won't work. I will try a d extract the source code and try and find a way to do it on mobile.

**Comment by pressenterreal** [comment]
Am am closing this as of now. If you have a comment, please put it here.
