### ISSUE TITLE
tricky mod on HARD MODE AND NORMAL MODE ONLY!!! 

### ISSUE THREAD

**Issue by mohamed5236** [luckydog7/Funkin-android#220]
the mod https://www.mediafire.com/file/54148q37108molx/tricky+mod.apk/file
Credit to who made the tricky mod
https://youtube.com/channel/UCzMuuQYYYnqif3UTeTyJ3xQ
not made by me

**Comment by woaa12** [comment]
Peppy verison

**Comment by ElPeppyWall** [comment]
> Peppy verison the epic guy who made the mobild verisons lol

Lol i am
