### ISSUE TITLE
Fnf Holonight Funkin' mod

### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#230]
If you guys interested, you can download from here :
https://mega.nz/file/98A21DRB#JFv4pRYb8U_yWX6Bix0fGY5BA0AckFiIN3HGfBlejXY
Have fun :-D

**Comment by Ralphy999** [comment]
> If you guys interested, you can download from here :
> https://mega.nz/file/98A21DRB#JFv4pRYb8U_yWX6Bix0fGY5BA0AckFiIN3HGfBlejXY
> Have fun :-D

Can you make a b side vibe lite version pls

**Comment by MrTks216** [comment]
> > If you guys interested, you can download from here :
> > https://mega.nz/file/98A21DRB#JFv4pRYb8U_yWX6Bix0fGY5BA0AckFiIN3HGfBlejXY
> > Have fun :-D
> 
> Can you make a b side vibe lite version pls

Sorry, idk how to do the lite version

**Comment by DanisLixo** [comment]
I'll do it, relax

**Comment by Ralphy999** [comment]
> I'll do it, relax

Can ypu teach me how

**Comment by MrTks216** [comment]
Well, i guess I will try do b side vibe mod the normal one

**Comment by Ralphy999** [comment]
> Well, i guess I will try do b side vibe mod the normal one

I already have it but i need no black squares lmao nvm dont do it im just gonna wait for the next update of fnf low end

**Comment by MrTks216** [comment]
> > Well, i guess I will try do b side vibe mod the normal one
> 
> I already have it but i need no black squares lmao nvm dont do it im just gonna wait for the next update of fnf low end

Oh ok lol
