### ISSUE TITLE
Someone conver this into a spooky kids .png 

### ISSUE THREAD

**Issue by woaa12** [luckydog7/Funkin-android#234]
PLEASE I NEED MATT 
![Pico_FNF_assetss](https://user-images.githubusercontent.com/78597960/113630118-619c5300-9635-11eb-8516-48abbc3bf091.png)

**Comment by ThatGuyW** [comment]
Alright I'll try

**Comment by woaa12** [comment]
> Alright I'll try

Also the guys have two spite things so it chould be possible
![Pico_FNF_assetss (2)](https://user-images.githubusercontent.com/78597960/113639259-bdbba300-9646-11eb-8b63-5d394c4fffdc.png)
![spooky_kids_assets](https://user-images.githubusercontent.com/78597960/113639267-c14f2a00-9646-11eb-82ba-1f7a79c82b77.png)

**Comment by woaa12** [comment]
> Alright I'll try

Never mind,pepy made a verison and i used my edited backround to make it look better 
![Screenshot_2021-04-06-01-01-46](https://user-images.githubusercontent.com/78597960/113661567-5c122d80-9674-11eb-9c27-680bed948b28.png)
