### ISSUE TITLE
LUCKYDOG PLEASE READ THIS

### ISSUE THREAD

**Issue by PlanetaArthur** [luckydog7/Funkin-android#243]
luckydog i can send friday night funkin to the play store i may or may not

**Comment by mohamed5236** [comment]
do it do it plzz

**Comment by superkuzia15** [comment]
Y E S

**Comment by DanisLixo** [comment]
> luckydog i can send friday night funkin to the play store i may or may not

no, don't do it **eu tô falando sério não faz**

**Comment by woaa12** [comment]
Yea i dont think MILF,dads funni hair,moms looks,lemon demon songs,ROSES DIALOGUE LOL and shit literally in the files idnt gonna get past google play.

**Comment by woaa12** [comment]
But there was gonna be a cerson verison option so idk

**Comment by PlanetaArthur** [comment]
Guys

**Comment by PlanetaArthur** [comment]
can I send friday night funkin to aptoide?

**Comment by DanisLixo** [comment]
> can I send friday night funkin to aptoide?

now I see no problem

**Comment by DanisLixo** [comment]
just put the port website (https://github.com/luckydog7/Funkin-android/) in the description.

**Comment by DanisLixo** [comment]
he didn't put... problem solved
