### ISSUE TITLE
Game, when i install this mod:

### ISSUE THREAD

**Issue by CalibriLight** [luckydog7/Funkin-android#248]
![Screenshot_2021-04-07-12-30-45](https://user-images.githubusercontent.com/59058076/113843446-a0045000-97a4-11eb-89d1-c12abd15990b.jpg)
Black cubes, on pc this mod normal working

**Comment by FridayNightSans** [comment]
This is about ur device! Its doesnt strong too play 64 bit chartacter. Idk about this but someone said that lite version could fix those black

**Comment by mohamed5236** [comment]
i play on 64 bits nah not strong enough

**Comment by CalibriLight** [comment]
> This is about ur device! Its doesnt strong too play 64 bit chartacter. Idk about this but someone said that lite version could fix those black

Sad :(

**Comment by Rs232k** [comment]
Your GPU max texture size is lower than game texture size. Or just your gpu is weak.

**Comment by DanisLixo** [comment]
> i play on 64 bits nah not strong enough

there is nothing to do with 32 bits and 64 bits, it works on both equally, the problem is the CPU and RAM, if someone else says _ 32 bit version_ I will be depressed

**Comment by DanisLixo** [comment]
> > i play on 64 bits nah not strong enough
> 
> there is nothing to do with 32 bits and 64 bits, it works on both equally, the problem is the CPU and RAM, if someone else says _32 bit version_ I will be depressed

**Comment by BoyfriendFNF** [comment]
#152 use this
