### ISSUE TITLE
I just got this after i died

### ISSUE THREAD

**Issue by briannewmc22a** [luckydog7/Funkin-android#249]
What does this mean
![Screenshot_20210407-173743](https://user-images.githubusercontent.com/82090352/113848052-a9a0ae80-97ca-11eb-979d-2a2d385bc1e1.jpg)

**Comment by kffwlp** [comment]
It's a pretty rare easter egg

**Comment by mohamed5236** [comment]
that is rare

**Comment by briannewmc22a** [comment]
Oh okay

**Comment by DanisLixo** [comment]
oh, you got the easter egg too
![Screenshot_20210331-185905](https://user-images.githubusercontent.com/58278276/113860040-f4dfa080-977b-11eb-8f42-403829c8c72d.png)

**Comment by DanisLixo** [comment]
_the screenshot is literally the same_

**Comment by briannewmc22a** [comment]
The left button is kinda more bright on my screenshot idk why

**Comment by Ralphy999** [comment]
I got that too but i thought its a new pause menu and it restarts my week lol
