### ISSUE TITLE
I need help [CRASH] 

### ISSUE THREAD

**Issue by BestNameInHistory** [luckydog7/Funkin-android#261]
Please anyone help me 
Every week crashing 
But week 6 working perfectly without any problems
I don't know why 
maybe my phone weak ???
My phone is 2GB ram
Android 8
I want Fix that 
Respond fast

**Comment by LunaWalker** [comment]
on such a phone, it obviously wont work if u have the full version, here is a channel that uploads optimized versions for low-end cell phones

https://youtube.com/c/Dekar-Rowe

**Comment by BestNameInHistory** [comment]
Thank you very mush and If it worked well I will put comment (✷‿✷)

**Comment by DanisLixo** [comment]
> Thank you very mush and If it worked well I will put comment (✷‿✷)

bruh

**Comment by BoyfriendFNF** [comment]
#152

**Comment by BestNameInHistory** [comment]
It worked !!!!!!

**Comment by BoyfriendFNF** [comment]
> It worked !!!!!!

cool, it works for me too
