### ISSUE TITLE
Fnf Hatsune Miku mod

### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#264]
Hey, I put Hatsune Miku mod into latest version with hitbox 
Replace week 1 and 2 
Week 1:
Bopeebo = Popipo
Fresh = Ashite
Dadbattle = SIU (Suck it Up) 
Week 2:
Spookeez = Disappearance  (miku sprites didn't work, I will fix it soon)  
South = Chug Jug With You
![Screenshot_2021-04-09-07-05-54-761_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114108149-161fc880-9905-11eb-9702-8b2baaf74059.jpg)
![Screenshot_2021-04-09-07-06-27-489_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114108163-2172f400-9905-11eb-8247-93fe393d6072.jpg)

Link : https://mega.nz/file/A9hzDaoL#OSsDGzV8pCuERO1NN1aP82BuOGUtaWrTYS3X_VMivac

And i also make the lite version of this mod 
Here:
https://mega.nz/file/p5o3kYxb#ybjMsPeNdbrNTC6h6bTVDAGEdYQmrwDidITDRYGs6gk

**Comment by DanisLixo** [comment]
put disapperence on week 5

**Comment by MrTks216** [comment]
> put disapperence on week 5

Which one?  Dad and mom or monster?

**Comment by MrTks216** [comment]
Nevermind, i know how to do

**Comment by MrTks216** [comment]
Ah...don't know how to coding ev_miku_mad.xml to mom_dad_christmas_assets.xml...
