### ISSUE TITLE
Bopeebo but everyone is bored mod

### ISSUE THREAD

**Issue by briannewmc22a** [luckydog7/Funkin-android#268]
Here ya go for the mobile version!
https://mega.nz/file/aRcDDCoQ#rvGyChQeImlWLTKswMQkp2mw6-qoQFOImersRJZZZFg
![Screenshot_20210409-185049](https://user-images.githubusercontent.com/82090352/114169743-8b6eb600-9964-11eb-95a8-cfe8494c527c.jpg)
Hope it works

**Comment by Ralphy999** [comment]
Can you make a low end version?

**Comment by briannewmc22a** [comment]
Ok ima try later

**Comment by briannewmc22a** [comment]
Should i do it with other weeks the mod only change bopeebo thats all?

**Comment by BoyfriendFNF** [comment]
> Should i do it with other weeks the mod only change bopeebo thats all?

other weeks sound good so please do that

**Comment by Ralphy999** [comment]
> Should i do it with other weeks the mod only change bopeebo thats all?

Do all weeks pls

**Comment by briannewmc22a** [comment]
Ok i will try im finished with bf

**Comment by briannewmc22a** [comment]
Btw i meant for the low end version sorry i dont know how to edit audios

**Comment by briannewmc22a** [comment]
But is it okay if i didnt edit the audio but all weeks

**Comment by briannewmc22a** [comment]
Nvm i learn how to edit it but it just remove the voices when i put it ima try fixing it

**Comment by briannewmc22a** [comment]
Yaaay i fixed it but the insts more louder ima try fixing it again
