### ISSUE TITLE
Keyboard Controls?

### ISSUE THREAD

**Issue by AxemaVales** [luckydog7/Funkin-android#27]
I connected a keyboard onto my phone and tried to play with it on the android port, but it's completely non-functional.

Could it be possible to allow keyboard controls for the game?

**Comment by ElPeppyWall** [comment]
Octopus

**Comment by pearlbits64** [comment]
Just let me tell you stop with the keyboard shit its not even a good idea while the game has bugs and it always crashs here is tje group of people that want keyboard controllers no just dont ask NOW

**Comment by AxemaVales** [comment]
> Use Octopus

Doesn't work. Tried both 32x and 64x plugins, still doesn't launches the game.

**Comment by pearlbits64** [comment]
Why do we need keyboard controllers

**Comment by luckydog7** [comment]
Added
