### ISSUE TITLE
New week 7 leaked songs

### ISSUE THREAD

**Issue by Zizoplays1** [luckydog7/Funkin-android#276]
https://youtu.be/BXSlrb_L84E

**Comment by Zizoplays1** [comment]
And here it is with gameplay, ignore 2nd song https://youtu.be/HaHeKq5tctw

**Comment by DanisLixo** [comment]
WHAT THE FUCK, IS THIS SPOILER, WHY DID YOU POST HERE? WHY?

**Comment by Zizoplays1** [comment]
> WHAT THE FUCK, IS THIS SPOILER? WHY DID YOU POST HERE? WHY?

Idk

**Comment by DanisLixo** [comment]
but it is really spoiler, it is better to delete this issue so as not to spoil the experience of new mobile players.

**Comment by wllpwr** [comment]
This isn't even an issue...

**Comment by DanisLixo** [comment]
> but it is really spoiler, it is better to delete this issue so as not to spoil the experience of new mobile players.

he didn't deleted... AAAAAAAAA
