### ISSUE TITLE
Fnf Henry Stickmin full week, Charles Calvin and Ellie Rose mod

### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#280]
I put 3 mod into fnf with hitbox

Week 1 (3 New Song) (Third song fix) 
(Dad replace Henry Stickmin)

Week 2 (Skid and Pump = Angry Henry Stickmin)

Week 3 (Second song Philly Remix) 
(Pico replace Charles Calvin)

Week 4  (Mom replace Ellie Rose)

Week 5 (Santa replace Charles Calvin)

Week 6 (Boyfriend replace Charles Calvin)

![Screenshot_2021-04-10-13-46-19-836_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114264079-6a1cd100-9a1b-11eb-96d2-7d834a011c74.jpg)
![Screenshot_2021-04-10-16-23-40-955_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114264094-8587dc00-9a1b-11eb-8b0e-f15edd247a1d.jpg)
![Screenshot_2021-04-10-13-48-16-013_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114264104-95072500-9a1b-11eb-869f-620197e9a333.jpg)
![Screenshot_2021-04-10-13-49-12-266_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114264128-b2d48a00-9a1b-11eb-898e-9a9506eba095.jpg)
![Screenshot_2021-04-10-16-24-15-358_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114264146-ce3f9500-9a1b-11eb-81db-fe3b3337a584.jpg)

Here the link:
https://mega.nz/file/Q4wSAaba#heELVzzX4lNX4zltt3aYQ6nmST7hWv2gfuayvo4GESc
Have fun :-)

**Comment by Ralphy999** [comment]
> I put 3 mod into fnf with hitbox
> 
> Week 1 (3 New Song)
> (Dad replace Henry Stickmin)
> 
> Week 2 (Skid and Pump = Angry Henry Stickmin)
> 
> Week 3 (Second song Philly Remix)
> (Pico replace Charles Calvin)
> 
> Week 4 (Mom replace Ellie Rose)
> 
> Week 5 (Santa replace Charles Calvin)
> 
> Week 6 (Boyfriend replace Charles Calvin)
> 
> ![Screenshot_2021-04-10-13-46-19-836_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114264079-6a1cd100-9a1b-11eb-96d2-7d834a011c74.jpg)
> ![Screenshot_2021-04-10-16-23-40-955_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114264094-8587dc00-9a1b-11eb-8b0e-f15edd247a1d.jpg)
> ![Screenshot_2021-04-10-13-48-16-013_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114264104-95072500-9a1b-11eb-869f-620197e9a333.jpg)
> ![Screenshot_2021-04-10-13-49-12-266_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114264128-b2d48a00-9a1b-11eb-898e-9a9506eba095.jpg)
> ![Screenshot_2021-04-10-16-24-15-358_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114264146-ce3f9500-9a1b-11eb-81db-fe3b3337a584.jpg)
> 
> Here the link:
> https://mega.nz/file/AgYgCRBR#fCsqq03kMTmjyR3B6YBKP35qf040fsq1IrtU0IEnT7U
> Have fun :-)

Can you make a low end version of this?

**Comment by MrTks216** [comment]
Sorry, idk how to make low end version fnf.

**Comment by Ralphy999** [comment]
Oh its ok

**Comment by NeonNotFound** [comment]
Nice modding port can i use this for low end phones?

**Comment by NeonNotFound** [comment]
I just wanna help for people has low end phones and has a black textures problem

**Comment by MrTks216** [comment]
> Nice modding port can i use this for low end phones?

Sure go ahead

**Comment by NeonNotFound** [comment]
> > Nice modding port can i use this for low end phones?
> 
> Sure go ahead

Ty

**Comment by MrTks216** [comment]
> > > Nice modding port can i use this for low end phones?
> > 
> > Sure go ahead
> 
> Ty

You're welcome

**Comment by NeonNotFound** [comment]
Ill be posting the low end version on my yt channel credits in the description 😁

**Comment by MrTks216** [comment]
> Ill be posting the low end version on my yt channel credits in the description 😁
> 
> 

Oh nice, what is your youtube channel name?

**Comment by NeonNotFound** [comment]
> > Ill be posting the low end version on my yt channel credits in the description 😁
> 
> Oh nice, what is your youtube channel name?

Here is my channel link https://youtube.com/channel/UCVxzZ-dg7cyUWo0PbWzZkPA

**Comment by MrTks216** [comment]
> > > Ill be posting the low end version on my yt channel credits in the description 😁
> > 
> > Oh nice, what is your youtube channel name?
> 
> Here is my channel link https://youtube.com/channel/UCVxzZ-dg7cyUWo0PbWzZkPA

I gonna subscribe you. Good luck👍

**Comment by NeonNotFound** [comment]
> > > > Ill be posting the low end version on my yt channel credits in the description 😁
> > > 
> > > 
> > > Oh nice, what is your youtube channel name?
> > 
> > 
> > Here is my channel link https://youtube.com/channel/UCVxzZ-dg7cyUWo0PbWzZkPA
> 
> I gonna subscribe you. Good luck👍

Im adding the fnf lite sprites in apk editor now 😁

**Comment by NeonNotFound** [comment]
The low end version is out im gonna record it only one game im full storage 👀

**Comment by NeonNotFound** [comment]
![Uploading Screenshot_2021-04-10-23-41-39-49_d041af62a2d22fd7fcc1e7e386524cd6.jpg…]()

**Comment by NeonNotFound** [comment]
The mod is exported now 👀

**Comment by MrTks216** [comment]
> The mod is exported now 👀

Great job!

**Comment by MrTks216** [comment]
> ![Uploading Screenshot_2021-04-10-23-41-39-49_d041af62a2d22fd7fcc1e7e386524cd6.jpg…]()
> 

I can't see it

**Comment by NeonNotFound** [comment]
> I can't see it

Check out the new issue i made 👀
