### ISSUE TITLE
Friday Night Funkin x RincewindUniversity skin mod 

### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#282]
This mod is very high quality (Week 1 to 3)
 
![Screenshot_2021-04-10-17-39-37-374_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114266332-604d9a80-9a28-11eb-83af-ae547f59e435.jpg)
![Screenshot_2021-04-10-17-44-40-756_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114266361-85daa400-9a28-11eb-8e88-7ec001425610.jpg)
![Screenshot_2021-04-10-17-45-51-730_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114266370-91c66600-9a28-11eb-8a9e-cf7cf6ad7120.jpg)
![Screenshot_2021-04-10-17-37-31-979_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114266381-9be86480-9a28-11eb-877d-d6cb1d304d92.jpg)
![Screenshot_2021-04-10-17-38-14-661_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114266572-87589c00-9a29-11eb-8ff5-8aaf2ff9a6f9.jpg)
![Screenshot_2021-04-10-17-38-52-330_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114266462-16b17f80-9a29-11eb-8c3b-3c1908856fca.jpg)

You need better phone to play this mod
Here the link:
https://mega.nz/file/NkxSwaBR#BrZSgicqIMPphsV9KQJK4rp7gnOSgEyzgee2Sy1X_4I

**Comment by FridayNightSans** [comment]
AMAZING! How the funk- ur phone can handle this? .-.

**Comment by MrTks216** [comment]
> AMAZING! How the funk- ur phone can handle this? .-.

Yes, my phone have 4gb ram

**Comment by FridayNightSans** [comment]
.-. 1Ram

**Comment by MrTks216** [comment]
> .-. 1Ram

Oof

**Comment by ROBIKALIVE13** [comment]
I LOVE THIS MOD

**Comment by Ralphy999** [comment]
> > AMAZING! How the funk- ur phone can handle this? .-.
> 
> Yes, my phone have 4gb ram

Lmao im 3 gb ram only frick
