### ISSUE TITLE
B-side with hitbox pls

### ISSUE THREAD

**Issue by Tigedraglon10** [luckydog7/Funkin-android#287]
If you can try modding it to b-side with hitbox thanks and please

**Comment by sonicyt1234** [comment]
Here you go: https://www.mediafire.com/file/rcvxx2c1z7rjq6k/B+Sides.apk/file

**Comment by Tigedraglon10** [comment]
Thanks Your Nicd

**Comment by Tigedraglon10** [comment]
> Here you go: https://www.mediafire.com/file/rcvxx2c1z7rjq6k/B+Sides.apk/file

Thx

**Comment by DanisLixo** [comment]
close

**Comment by Tigedraglon10** [comment]
> close

kk

**Comment by sonicyt1234** [comment]
> > Here you go: https://www.mediafire.com/file/rcvxx2c1z7rjq6k/B+Sides.apk/file
> 
> Thx

You're welcome
