### ISSUE TITLE
Someone port Shadow Mario's multiplayer mod version 3.1 to mobile.

### ISSUE THREAD

**Issue by CalypsoTH** [luckydog7/Funkin-android#288]
I watched gameplay of the mod, and it was really great and I really wanted to play it myself, but it will be a while until I my pc hooked up soon so please, someone port the mod to mobile.

**Comment by DanisLixo** [comment]
I am so angry with this type of person, but I will be straight here, without source code = without port

**Comment by DanisLixo** [comment]
I would love to port the mod, but I can't, I don't have the source code, much less a PC

**Comment by CalypsoTH** [comment]
> I am so angry with this type of person, but I will be straight here, without source code = without port

I'm sorry I'm being like this, and also I do have laptops, but I'm scared that I might've broke them, and even if they weren't broken, I wouldn't know where the chargers are at.

**Comment by DanisLixo** [comment]
ok, but why has a period, at least ask if you can do it right?

**Comment by BoyfriendFNF** [comment]
it technically would happen if shadow mario would give the source code to luckydog7, but that won't happen so rip
