### ISSUE TITLE
Fnf The X-Event (Vs Ink!Sans) with hitbox 

### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#294]
Week 1
(Dad replace X-Chara) 
(Bopeebo replace Overwrite)

Week 2
(skid and pump replace Ink) 
(Spookeez replace inkingmistake)

![Screenshot_2021-04-11-12-02-01-590_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114292213-6e9ac580-9abf-11eb-9662-db2472bfb9a6.jpg)
![Screenshot_2021-04-11-12-02-30-295_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114292216-75293d00-9abf-11eb-9a80-060bd3c8f07d.jpg)
![Screenshot_2021-04-11-12-02-56-675_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114292221-7ce8e180-9abf-11eb-8dd2-c1f3b4949dbe.jpg)

Here the link:
(Delete)

Have fun👍

**Comment by FridayNightSans** [comment]
inkbigmistake is the real name of songs ink

**Comment by MrTks216** [comment]
> inkbigmistake is the real name of songs ink

Lol

**Comment by hatechara19** [comment]
My dads and fucking pussy:from selver
Me:WHY IS THIS IN MIDFIGHTMASSES
