### ISSUE TITLE
Need some help to fix this character (matt) (mod)

### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#307]
Idk how to fix this, matt sprites is flying. Pls help. 

![Screenshot_2021-04-12-21-42-07-349_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114404979-cd079700-9bd8-11eb-8e80-cf02f07a6e5e.jpg)

**Comment by Rs232k** [comment]
> Idk how to fix this, matt sprites is flying. Pls help.
> 
> ![Screenshot_2021-04-12-21-42-07-349_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114404979-cd079700-9bd8-11eb-8e80-cf02f07a6e5e.jpg)

Change to other week

**Comment by MrTks216** [comment]
> > Idk how to fix this, matt sprites is flying. Pls help.
> > 
> > ![Screenshot_2021-04-12-21-42-07-349_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114404979-cd079700-9bd8-11eb-8e80-cf02f07a6e5e.jpg)
> 
> Change to other week

Which week?

**Comment by FridayNightSans** [comment]
Which week u r using?

**Comment by FridayNightSans** [comment]
Week 2 is the best 4 this

**Comment by MrTks216** [comment]
> Which week u r using?

Week1

**Comment by MrTks216** [comment]
> > > > Idk how to fix this, matt sprites is flying. Pls help.
> > > > ![Screenshot_2021-04-12-21-42-07-349_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114404979-cd079700-9bd8-11eb-8e80-cf02f07a6e5e.jpg)
> > > 
> > > 
> > > Change to other week
> > 
> > Which week?
> 
> °-°

What?

**Comment by DanisLixo** [comment]
I think week 2 is better, cuz Spooky kids. u know, spook month

**Comment by MrTks216** [comment]
> I think week 2 is better, cuz Spooky kids. u know, spook month

Ok lol

**Comment by woaa12** [comment]
> Idk how to fix this, matt sprites is flying. Pls help.
> 
> ![Screenshot_2021-04-12-21-42-07-349_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114404979-cd079700-9bd8-11eb-8e80-cf02f07a6e5e.jpg)

thats how its supposed to be

**Comment by MrTks216** [comment]
![Screenshot_2021-04-12-23-35-17-516_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114421496-efed7780-9be7-11eb-8f2f-8eef578cd04c.jpg)
Bruh still same

**Comment by MrTks216** [comment]
You know what, i gonna change it back to week 1

**Comment by woaa12** [comment]
> ![Screenshot_2021-04-12-23-35-17-516_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114421496-efed7780-9be7-11eb-8f2f-8eef578cd04c.jpg)
> Bruh still same,
> Matt sprites move even worse

THATS HOW ITS SUPPORTED TO BE THERES NOTHING WRONG

**Comment by Rs232k** [comment]
> > ![Screenshot_2021-04-12-23-35-17-516_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114421496-efed7780-9be7-11eb-8f2f-8eef578cd04c.jpg)
> > Bruh still same,
> > Matt sprites move even worse
> 
> THATS HOW ITS SUPPORTED TO BE THERES NOTHING WRONG

![Screenshot_20210412-220352~01](https://user-images.githubusercontent.com/14124680/114425728-2e306a00-9bdb-11eb-8d81-afd173b58354.jpg)
Are you sure?

**Comment by MrTks216** [comment]
> > ![Screenshot_2021-04-12-23-35-17-516_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114421496-efed7780-9be7-11eb-8f2f-8eef578cd04c.jpg)
> > Bruh still same,
> > Matt sprites move even worse
> 
> THATS HOW ITS SUPPORTED TO BE THERES NOTHING WRONG

I know, okay. Sorry, Don't need to mad.

**Comment by woaa12** [comment]
> > > ![Screenshot_2021-04-12-23-35-17-516_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114421496-efed7780-9be7-11eb-8f2f-8eef578cd04c.jpg)
> > > Bruh still same,
> > > Matt sprites move even worse
> > 
> > 
> > THATS HOW ITS SUPPORTED TO BE THERES NOTHING WRONG
> 
> ![Screenshot_20210412-220352~01](https://user-images.githubusercontent.com/14124680/114425728-2e306a00-9bdb-11eb-8d81-afd173b58354.jpg)
> Are you sure?

In the port,not the actualy one lol

**Comment by Rs232k** [comment]
K

**Comment by MrTks216** [comment]
![Screenshot_2021-04-13-00-44-56-183_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114430968-8f633800-9bf1-11eb-83ae-faf2b0abc43f.jpg)

Well I'm done
