### ISSUE TITLE
Fnf Wii Funkin' VSMatt FULL WEEK mod (old)

### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#308]
Week 1 (No Dialogue)
(Dad replace Matt) 
Song
Bopeebo = light it up
Fresh = ruckus
Dadbattle = target practice
![Screenshot_2021-04-13-00-58-36-182_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114433124-0994bc00-9bf4-11eb-831e-5c244f200054.jpg)
![Screenshot_2021-04-13-00-58-57-813_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114433148-11546080-9bf4-11eb-8896-82b087b12394.jpg)

Here the link :
(Go to #975 download new version)
Have fun 👍

**Comment by MrTks216** [comment]
That will be the last mod i port in Android. I'm done

**Comment by FridayNightSans** [comment]
> That will be the last mod i port in Android. I'm done, i will do port mod again when week 7 came out.

Which?

**Comment by DanisLixo** [comment]
> Week 1
> (Dad replace Matt)
> Song
> Bopeebo = light it up
> Fresh = ruckus
> Dadbattle = target practice
> ![Screenshot_2021-04-13-00-58-36-182_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114433124-0994bc00-9bf4-11eb-831e-5c244f200054.jpg)
> ![Screenshot_2021-04-13-00-58-57-813_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114433148-11546080-9bf4-11eb-8896-82b087b12394.jpg)
> 
> Here the link :
> https://mega.nz/file/E4AzFQ7A#IlSQAUR-UnXUNYBxR7Yuiq9q4IFMAwFxb-fD0aSb_5o
> Have fun 👍

hes in a table, cute

**Comment by NeonNotFound** [comment]
Ok guess ill be making a lite version again 👍

**Comment by MrTks216** [comment]
> Ok guess ill be making a lite version again 👍

Sure

**Comment by MrTks216** [comment]
> > That will be the last mod i port in Android. I'm done, i will do port mod again when week 7 came out.
> 
> Which?

This mod

**Comment by Zizoplays1** [comment]
Does it crash, this is the main question?

**Comment by MrTks216** [comment]
> Does it crash, this is the main question? 

Mine didn't crash, it work very well

**Comment by Zizoplays1** [comment]
Cool
