### ISSUE TITLE
Lite versions (Oh no)

### ISSUE THREAD

**Issue by DanisLixo** [luckydog7/Funkin-android#313]
Bye.
Original:

Friday Night Funkin' (Lite Boyfriend) by Luckydog7: https://www.mediafire.com/download/p7jfrv12kou842o

Friday Night Funkin' (Default Boyfriend) by Luckydog7: https://www.mediafire.com/download/lyosafapjbfuv3q

Friday Night Funkin' Low end (No hitbox) by Luckydog7 (assets by Hadobedo): https://www.mediafire.com/download/2gut4lcwrm5mll5

Kade Engine (Unofficial) by KEDev Android Project Team (Original Engine by Kadedev): https://www.mediafire.com/download/cmtuz4dqn6xwbt4

Mods (No Low end):

Friday Night Funkin' B-sides by ??? (Mod by Rozebud and JADS): https://www.mediafire.com/download/ehdqqgxjy6k4xpq

hard

- Kade Engine Version by me (Mod by ^^^): https://www.mediafire.com/download/y5l7gfr7nz5hnfo

Friday Night Funkin' NEO mod by ??? (Mod by Cval and Jellyfishedm): https://www.mediafire.com/download/mc4oubxajbtgvyi

week 5 crash kek

Friday Night Funkin' Minus by Luckydog7 (Mod by IagoAnims): https://www.mediafire.com/download/9do1iylr3m8nc1l

Friday Night Funkin' Corruption mod (Early Access) by ??? (Mod by Phantom Fear): https://www.mediafire.com/download/e489xubr3cmpj7k

High Effort B3 Blammed by me (Mod by BrightFrye): https://www.mediafire.com/download/rmkr83fu3xemqnw

High Effort UGH 2.0 by #@* (Mod by Rozebud): Coming Soon

Friday Night Funkin' Mid-Fight Masses by Rs232k (Mod and Engine by kuroao_anomal): https://www.mediafire.com/download/p67aeicyoxoq6wt

- Recharted version by RidinglnTheRed: https://www.mediafire.com/download/0wapzterscahaku

note: the notes hitbox at Gospel is bugged, you can use the OBAN trick (One Button, All Notes) to pass.

Low End Mods: Never

I deleted the gf in all mods except Corruption and Mid-Fight Masses.

**Comment by Ralphy999** [comment]
> I will update and bring a lite of all versions of the game that I can get (including mods). I will try to complete my homework as soon as possible and bring as many lite versions of mods and the original game (Low End Included). I will gradually bring the mods completed with lite, and I will try to bring a low end version of the mods too (I promise, but I will not finish the low end versions until next week, this week is for lite versions). Please, let me know who made the original mods port and put the link to the port issue in the comments, I don’t want to get all the work done for something I didn’t do alone.
> 
> Friday Nights at Funkin' (Lite Boyfriend) by Luckydog7: https://www.mediafire.com/download/p7jfrv12kou842o
> 
> it's still crash :(
> 
> Original:
> 
> Friday Day Funkin' (Default Boyfriend) by Luckydog7: https://www.mediafire.com/download/lyosafapjbfuv3q
> 
> Crash
> 
> Friday Night Funkin' Low end (No hitbox) by Luckydog7 (assets by Hadobedo): https://www.mediafire.com/download/2gut4lcwrm5mll5
> 
> crash (week 4 and 5)
> 
> Kade Engine (Unofficial) by ??? (Original Engine by Kadedev): Coming Soon
> 
> Mods (No Low end):
> 
> Friday Night Funkin' Be-sides by ??? (Mod by Rozebud and JADS): https://www.mediafire.com/download/ehdqqgxjy6k4xpq
> 
> Friday Night Funkin' NEO mod by ??? (Mod by Cval and Jellyfishedm): https://www.mediafire.com/download/mc4oubxajbtgvyi
> 
> Friday Night Funkin' Minus ur mom by Luckydog7 (Mod by IagoAnims): https://www.mediafire.com/download/9do1iylr3m8nc1l
> 
> Friday Night Funkin' with unstable _hacks_ (Corruption mod Early Access) by ??? (Mod by Phantom Fear): https://www.mediafire.com/download/e489xubr3cmpj7k
> 
> Friday Night Funkin' Megamix (April Fools Mod) by me: https://www.mediafire.com/download/ocz69guxxxewbu9
> 
> More Mods: Soon
> 
> Low End Mods: Soon
> 
> I deleted the gf in all mods except Corruption, Megamix (April Fools Mod) and Low End Mods

The low end version is new?

**Comment by DanisLixo** [comment]
> > I will update and bring a lite of all versions of the game that I can get (including mods). I will try to complete my homework as soon as possible and bring as many lite versions of mods and the original game (Low End Included). I will gradually bring the mods completed with lite, and I will try to bring a low end version of the mods too (I promise, but I will not finish the low end versions until next week, this week is for lite versions). Please, let me know who made the original mods port and put the link to the port issue in the comments, I don’t want to get all the work done for something I didn’t do alone.
> > Friday Nights at Funkin' (Lite Boyfriend) by Luckydog7: https://www.mediafire.com/download/p7jfrv12kou842o
> > it's still crash :(
> > Original:
> > Friday Day Funkin' (Default Boyfriend) by Luckydog7: https://www.mediafire.com/download/lyosafapjbfuv3q
> > Crash
> > Friday Night Funkin' Low end (No hitbox) by Luckydog7 (assets by Hadobedo): https://www.mediafire.com/download/2gut4lcwrm5mll5
> > crash (week 4 and 5)
> > Kade Engine (Unofficial) by ??? (Original Engine by Kadedev): Coming Soon
> > Mods (No Low end):
> > Friday Night Funkin' Be-sides by ??? (Mod by Rozebud and JADS): https://www.mediafire.com/download/ehdqqgxjy6k4xpq
> > Friday Night Funkin' NEO mod by ??? (Mod by Cval and Jellyfishedm): https://www.mediafire.com/download/mc4oubxajbtgvyi
> > Friday Night Funkin' Minus ur mom by Luckydog7 (Mod by IagoAnims): https://www.mediafire.com/download/9do1iylr3m8nc1l
> > Friday Night Funkin' with unstable _hacks_ (Corruption mod Early Access) by ??? (Mod by Phantom Fear): https://www.mediafire.com/download/e489xubr3cmpj7k
> > Friday Night Funkin' Megamix (April Fools Mod) by me: https://www.mediafire.com/download/ocz69guxxxewbu9
> > More Mods: Soon
> > Low End Mods: Soon
> > I deleted the gf in all mods except Corruption, Megamix (April Fools Mod) and Low End Mods
> 
> The low end version is new?

wat? no. it's literally a motorola moto g2 compatible version (not specifically)

**Comment by Ralphy999** [comment]
> > > I will update and bring a lite of all versions of the game that I can get (including mods). I will try to complete my homework as soon as possible and bring as many lite versions of mods and the original game (Low End Included). I will gradually bring the mods completed with lite, and I will try to bring a low end version of the mods too (I promise, but I will not finish the low end versions until next week, this week is for lite versions). Please, let me know who made the original mods port and put the link to the port issue in the comments, I don’t want to get all the work done for something I didn’t do alone.
> > > Friday Nights at Funkin' (Lite Boyfriend) by Luckydog7: https://www.mediafire.com/download/p7jfrv12kou842o
> > > it's still crash :(
> > > Original:
> > > Friday Day Funkin' (Default Boyfriend) by Luckydog7: https://www.mediafire.com/download/lyosafapjbfuv3q
> > > Crash
> > > Friday Night Funkin' Low end (No hitbox) by Luckydog7 (assets by Hadobedo): https://www.mediafire.com/download/2gut4lcwrm5mll5
> > > crash (week 4 and 5)
> > > Kade Engine (Unofficial) by ??? (Original Engine by Kadedev): Coming Soon
> > > Mods (No Low end):
> > > Friday Night Funkin' Be-sides by ??? (Mod by Rozebud and JADS): https://www.mediafire.com/download/ehdqqgxjy6k4xpq
> > > Friday Night Funkin' NEO mod by ??? (Mod by Cval and Jellyfishedm): https://www.mediafire.com/download/mc4oubxajbtgvyi
> > > Friday Night Funkin' Minus ur mom by Luckydog7 (Mod by IagoAnims): https://www.mediafire.com/download/9do1iylr3m8nc1l
> > > Friday Night Funkin' with unstable _hacks_ (Corruption mod Early Access) by ??? (Mod by Phantom Fear): https://www.mediafire.com/download/e489xubr3cmpj7k
> > > Friday Night Funkin' Megamix (April Fools Mod) by me: https://www.mediafire.com/download/ocz69guxxxewbu9
> > > More Mods: Soon
> > > Low End Mods: Soon
> > > I deleted the gf in all mods except Corruption, Megamix (April Fools Mod) and Low End Mods
> > 
> > 
> > The low end version is new?
> 
> wat? no. it's literally a motorola moto g2 compatible version (not specifically)

Ok

**Comment by DanisLixo** [comment]
Kade Engine is now for 3/4 GB RAM Phones

**Comment by DanisLixo** [comment]
b-sides for kade Engine :)

**Comment by BoyfriendFNF** [comment]
> Kade Engine is now for 3/4 GB RAM Phones

great because I have 3gb ram

**Comment by DanisLixo** [comment]
high effort mods? 🤔

**Comment by DanisLixo** [comment]
High Effort B3 Blammed is out LESS GO (the mod is awesome)

**Comment by DanisLixo** [comment]
Mid-Fight Masses is out

**Comment by Ralphy999** [comment]
> Mid-Fight Masses is out

Why

**Comment by DanisLixo** [comment]
?

**Comment by DanisLixo** [comment]
:/

**Comment by mcagabe19** [comment]
#424 please add sjsjsjjs

**Comment by VannyTheBunny09** [comment]
Where is High Effort Ugh 2.0 its been weeks. did you trolled us?

**Comment by DanisLixo** [comment]
> Where is High Effort Ugh 2.0 its been weeks. did you trolled us?

week 7 is already out

**Comment by kffwlp** [comment]
Is week 5 mom and dad fixed?

**Comment by VannyTheBunny09** [comment]
> > Where is High Effort Ugh 2.0 its been weeks. did you trolled us?
> 
> week 7 is already out

what do you mean week 7 is already out. luckydog7 is a frickin lazy ass dude. he didnt port a single frickin week (week 7)

**Comment by Ralphy999** [comment]
> > > Where is High Effort Ugh 2.0 its been weeks. did you trolled us?
> > 
> > 
> > week 7 is already out
> 
> what do you mean week 7 is already out. luckydog7 is a frickin lazy ass dude. he didnt port a single frickin week (week 7)

Bruh how bout you port it yourself ninja muffin isn't realising the source code yet

**Comment by mcagabe19** [comment]
#742 can you add?

**Comment by Maisha732** [comment]
Ummm can somebody give lite mod link plzzzz
