### ISSUE TITLE
Fun sized whitty help

### ISSUE THREAD

**Issue by ILoveFnF** [luckydog7/Funkin-android#316]
Can someone give me a fun sized whitty lite version file so i can put it in my mod?
(As the boyfriend). Thank you!

**Comment by Lstrk** [comment]
🙂👉https://gamebanana.com/dl/528718

**Comment by ILoveFnF** [comment]
Thanks but its still a black sprite

**Comment by Zizoplays1** [comment]
Wait until danislixo sees this

**Comment by DanisLixo** [comment]
_maybe_

**Comment by ILoveFnF** [comment]
Lol

**Comment by Narutoopm** [comment]
Tysm

**Comment by ILoveFnF** [comment]
Nobody helped so i am closing this
