### ISSUE TITLE
Combining mid fight masses and hex mod in fnf (if possible)

### ISSUE THREAD

**Issue by Ruv-lol** [luckydog7/Funkin-android#323]
Can you guys combine the mid fight masses and hex mod togethger? (If possible) I would really appericiate it if one of you people that have big brains able to do it cause their are my fav mods in fnf :)))).........I'm talking to FridayNightSans and Rs232k, u guys made the mid fight masses and hex mod so can u guys like maybe adding week x and week *cross* to the game so it won't be to confusing  instead of replacing the dad and the other people as sarvente and hex

**Comment by Ruv-lol** [comment]
I'm talking to FridayNightSans and Rs232k, u guys made the mid fight masses and hex mod so can u guys like maybe adding week x and week *cross* to the game so it won't be to confusing  instead of replacing the dad and the other people as sarvente and hex

**Comment by FridayNightSans** [comment]
Sorry but this is doesnt possible! Because we cant have an soure code and computer(maybe he have it) to make these! If you want then i can do it for you but ONLY 3 first songs of those week (NO SKIN)

**Comment by ILoveFnF** [comment]
Oof
