### ISSUE TITLE
CG5 Edition Mod

### ISSUE THREAD

**Issue by LightningCreeper381** [luckydog7/Funkin-android#326]
Would it be possible for someone to port the CG5 Edition mod? It's an executable file so you can't just use an APK Editor to play it.
Mod link: https://gamebanana.com/gamefiles/14966

**Comment by MrTks216** [comment]
> Would it be possible for someone to port the CG5 Edition mod? It's an executable file so you can't just use an APK Editor to play it.
> Mod link: https://gamebanana.com/gamefiles/14966

Here:
https://youtu.be/rNH-zTbPydU

**Comment by Zizoplays1** [comment]
You can make it, everyone can make if you watched tutorials on youtube
And i love the fnf cg5 songs btw

**Comment by MrTks216** [comment]
Yeah, cg5 song are pretty good

**Comment by LightningCreeper381** [comment]
> > Would it be possible for someone to port the CG5 Edition mod? It's an executable file so you can't just use an APK Editor to play it.
> > Mod link: https://gamebanana.com/gamefiles/14966
> 
> Here:
> https://youtu.be/rNH-zTbPydU

Oh cool, thanks!
