### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by BoyfriendFNF** [luckydog7/Funkin-android#331]
Will someone make a sky mod that dosent change the characters? because every time I try the sky mod port (even optimized one) it crashes because it changes the character (which in the hitbox update crashes) basically what I'm asking for is sky mod but only music and charts

**Comment by FridayNightSans** [comment]
Im going to port sky mod now, waiting pls

**Comment by FridayNightSans** [comment]
> Will someone make a sky mod that dosent change the characters? because every time I try the sky mod port (even optimized one) it crashes because it changes the character (which in the hitbox update crashes) basically what I'm asking for is sky mod but only music and charts

And did you edited the .xml file of the character you want to mod?

**Comment by BoyfriendFNF** [comment]
> > Will someone make a sky mod that dosent change the characters? because every time I try the sky mod port (even optimized one) it crashes because it changes the character (which in the hitbox update crashes) basically what I'm asking for is sky mod but only music and charts
> 
> And did you edited the .xml file of the character you want to mod?

I didint want any image assets just the charts and audio
