### ISSUE TITLE
FnF Electro Funkin Mod (All weeks Update) with Kade Engine

### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#333]
I kinda bored, so i put this mod in latest fnf with kade engine.
Preview:
![Screenshot_2021-04-16-00-27-03-630_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114906513-b0739500-9e4c-11eb-8d24-a6becf2d1465.jpg)
![Screenshot_2021-04-16-00-25-51-550_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114906545-b79aa300-9e4c-11eb-84ed-7b65f78afbe7.jpg)
[Week 1]
![Screenshot_2021-04-16-00-27-34-626_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114906569-bf5a4780-9e4c-11eb-915f-b9b3f14efd1e.jpg)
[Week 2] [monster nothing change]
![Screenshot_2021-04-16-00-28-16-898_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114906909-1c55fd80-9e4d-11eb-8400-11a4a0382d66.jpg)
[Week 3]
![Screenshot_2021-04-16-00-28-55-240_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114906945-27109280-9e4d-11eb-80b1-66de773fae05.jpg)
[Week 4]
![Screenshot_2021-04-16-00-29-35-846_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114906987-3263be00-9e4d-11eb-8592-f35627617a59.jpg)
[Week 5] 
![Screenshot_2021-04-16-00-31-37-328_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114907059-44456100-9e4d-11eb-94ac-5152145dcf0a.jpg)
[Christmas Monster]
![Screenshot_2021-04-16-00-32-48-692_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114907148-5aebb800-9e4d-11eb-8266-415e94b9ecfd.jpg)
[Week 6]
![Screenshot_2021-04-16-00-33-11-270_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114907194-6939d400-9e4d-11eb-86fa-9698c87e3739.jpg)
[Spirit]
![Screenshot_2021-04-16-00-33-23-847_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114907489-b158f680-9e4d-11eb-8315-44626896ca24.jpg)

Here the link:
https://mega.nz/file/V5I1QaYA#86Xkx4e1rgwcHDBu4dPstxMJ3LqKYi-XeJhjAPYA6vw
Have fun👏

**Comment by MrTks216** [comment]
> Okay why did you post this here, luckydog just probably got jealous and broke the source code.

Huh, wdym? i just want share the mod that i port in Android to let everyone to play.

**Comment by KlavierGayming** [comment]
yeah he broke the source code

**Comment by KlavierGayming** [comment]
it doesn't work anymore, it's completely broken.

**Comment by MrTks216** [comment]
> it doesn't work anymore, it's completely broken.

bruh, why do you think is luckydog broke the source code?

**Comment by ROBIKALIVE13** [comment]
> > it doesn't work anymore, it's completely broken.
> 
> bruh, why do you think is luckydog broke the source code?

he thinks that luckydog saw the kade engine then broke the source code

**Comment by MrTks216** [comment]
> > > it doesn't work anymore, it's completely broken.
> > 
> > bruh, why do you think is luckydog broke the source code?
> 
> he thinks that luckydog saw the kade engine then broke the source code

I'm very confused rn

**Comment by ROBIKALIVE13** [comment]
> > > > it doesn't work anymore, it's completely broken.
> > > 
> > > bruh, why do you think is luckydog broke the source code?
> > 
> > he thinks that luckydog saw the kade engine then broke the source code
> 
> I'm very confused rn

same
idk why he thinks that

**Comment by accountwithnousername** [comment]
> it doesn't work anymore, it's completely broken.

But it works ошо
