### ISSUE TITLE
Source Code Completely Broken. (You won't fool us, Lucky!)

### ISSUE THREAD

**Issue by KlavierGayming** [luckydog7/Funkin-android#334]
I know you probably did this intentionally to make us copy your code and break our Kade Engine build. You almost fooled me, but i tried the code for safety.

**Comment by Rs232k** [comment]
Hmm, idk it's buildable. And new functions not released in builds=testing.

**Comment by luckydog7** [comment]
its buildable, just type `lime build android -final`

**Comment by zacksgamerz** [comment]
Klav try it again

**Comment by KlavierGayming** [comment]
https://cdn.discordapp.com/attachments/813412759928438804/832285405801742396/unknown.png
I use windows for playtesting cuz it's easier for me, check the link and you'll see what i was going off of

**Comment by KlavierGayming** [comment]
but now it works, i'm a fucking dumbass.

**Comment by KlavierGayming** [comment]
Okay, i'm closing this issue now cuz i'm a fucking dumbass. I'm sorry for annoying anyone with this.

**Comment by zacksgamerz** [comment]
Bruh

**Comment by zacksgamerz** [comment]
Klav you dumbfuck.

**Comment by luckydog7** [comment]
Ok I fix this, just give me a couple of minutes

**Comment by KlavierGayming** [comment]
nah it works

**Comment by zacksgamerz** [comment]
I think there's nothing wrong with your code bud. Im sorry man

**Comment by KlavierGayming** [comment]
it seems to

**Comment by KlavierGayming** [comment]
sorry for annoying you

**Comment by zacksgamerz** [comment]
Oh my god..

**Comment by zacksgamerz** [comment]
Im posting this as a blooper just so we could laugh it off

**Comment by MrTks216** [comment]
Bruh

**Comment by KlavierGayming** [comment]
i am extremely sorry

**Comment by luckydog7** [comment]
i fix this, (i use web for test)

**Comment by MrTks216** [comment]
> i am extremely sorry

it alright, everyone have mistakes.

**Comment by KlavierGayming** [comment]
I'm so fucking dumb, i'm so sorry man.

**Comment by MrTks216** [comment]
> I'm so fucking dumb, i'm so sorry man.

Next time be careful okay?

**Comment by zacksgamerz** [comment]
Luckydog7. Its ok, you didnt make anything wrong

**Comment by zacksgamerz** [comment]
Just go take a break man.
