### ISSUE TITLE
LuckyDog7, please read.

### ISSUE THREAD

**Issue by ThatGuyW** [luckydog7/Funkin-android#335]
I know this would be kinda impossible but can you try port in next update a easy way to change game data (assets)? Like to not use Apk Editor and change assets in Android/data/com.ninjamuffin99.fnf

Also can you try add in controls a way to change buttons transparency? (Like make it invisible)

**Comment by zacksgamerz** [comment]
That will be tougher. Cuz that will destroy every youtube channel there is and fill your gallery with sprite sheets. So yeah

**Comment by luckydog7** [comment]
I tried to do it, but I couldn't

**Comment by ThatGuyW** [comment]
It's ok

**Comment by ThatGuyW** [comment]
done closed
