### ISSUE TITLE
Fnf vs. Neon (Full Week) with Kade Engine



### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#336]
Bored again, i put another one mod in latest fnf with kade engine

Preview:
![Screenshot_2021-04-16-02-38-58-126_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114922132-ea996280-9e5d-11eb-830f-1ebf617296cf.jpg)
![Screenshot_2021-04-16-02-24-24-800_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114922196-fbe26f00-9e5d-11eb-9162-b35c494f0adf.jpg)
[Week 6]
![Screenshot_2021-04-16-02-23-16-164_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114922269-0f8dd580-9e5e-11eb-8b09-5007011d5e8d.jpg)
![Screenshot_2021-04-16-02-22-51-831_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114922305-187ea700-9e5e-11eb-9503-92621edb63bf.jpg)
![Screenshot_2021-04-16-02-23-45-987_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/114922335-1ddbf180-9e5e-11eb-9dd2-17378af18960.jpg)

That all, here the link:
https://mega.nz/file/dgwgRThS#6sh681rR36F4k1VwUUE5qkQs6NO--bpQHZSl2W7e-EU
Have Fun 😊

**Comment by russellFun** [comment]
Ty so much!
