### ISSUE TITLE
Friday Night Defending skin mod

### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#345]
Preview:
![Screenshot_2021-04-17-00-19-20-453_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115055521-1aa33d00-9f14-11eb-8044-74e4681a2f3b.jpg)
![Screenshot_2021-04-17-00-19-33-584_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115055552-2989ef80-9f14-11eb-9c6c-e6d757134a4b.jpg)
[Week 1]
![Screenshot_2021-04-17-00-19-56-500_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115055598-3b6b9280-9f14-11eb-8eee-fda9e56a9055.jpg)
[Week2] (Monster nothing change)
![Screenshot_2021-04-17-00-20-39-112_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115055685-5c33e800-9f14-11eb-8b4e-48da55d8ba76.jpg)
[Week3]
![Screenshot_2021-04-17-00-22-56-912_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115055719-6e158b00-9f14-11eb-85d2-89879b9820dd.jpg)
[Week4]
![Screenshot_2021-04-17-00-23-36-490_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115055776-84234b80-9f14-11eb-9ec6-482a96487265.jpg)
[Week5]
![Screenshot_2021-04-17-00-26-08-990_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115055820-97ceb200-9f14-11eb-9213-5d102d713d9a.jpg)
[Christmas Monster] (scary)
![Screenshot_2021-04-17-00-27-07-945_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115055902-b6cd4400-9f14-11eb-83fc-d1128de74b23.jpg)
[Week6]
![Screenshot_2021-04-17-00-27-31-610_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115055949-c9477d80-9f14-11eb-9601-a4da9b6dafd4.jpg)
[Spirit]
![Screenshot_2021-04-17-00-27-51-821_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115056006-dcf2e400-9f14-11eb-9d1a-f344d37cebb2.jpg)

That all if you interested here the link:
https://mega.nz/file/gpQBkaCB#DHL0UrmzcDoQTowrzAnKHQ4nu_HExfb58fAjr1bwZgc
Well, have a good day 👍

**Comment by MistyFisty** [comment]
![Screenshot_2021-06-30-20-51-05-64_d041af62a2d22fd7fcc1e7e386524cd6](https://user-images.githubusercontent.com/84491613/123963369-f6b8a900-d9e4-11eb-8d39-d2067a25367f.jpg)

**Comment by MistyFisty** [comment]
so nice boyfriend tuened into this cool skin! ( son of a bich fix this)

**Comment by MrTks216** [comment]
> so nice boyfriend tuened into this cool skin! ( son of a bich fix this)
> 

sry, can't do it ¯\_(ツ)_/¯
and you're so rude.
