### ISSUE TITLE
Can someone make the Moony over gf mod compatible?

### ISSUE THREAD

**Issue by SpaceMoroto** [luckydog7/Funkin-android#347]
When i put it the game crashes and only Week 4, 5 and 6 works, i believe it's because the resolution of the gf assets is 8192 x 8192.

Mod link: https://gamebanana.com/skins/189630

**Comment by MrTks216** [comment]
wait, This skin only works for week 1-3, wdym didn't work?

**Comment by SpaceMoroto** [comment]
> wait, This skin only works for week 1-3, wdym didn't work?

i was kinda nervous and didn't know how to explain at that moment, I meant that Moony makes the game crash and i think that it's because of the resolution of gf assets being 8192 x 8192, So i asked if someone could make her compatible.

And the other 3 weeks just have their gf (week 4 gf car, week 5 gf christmas and week 6 gf pixel) since that for now the mod doesn't have sprites for them.

**Comment by SpaceMoroto** [comment]
Okay nvm i think i found a way
I will close this rn
