### ISSUE TITLE
i need some help with the starchatcher mod

### ISSUE THREAD

**Issue by ROBIKALIVE13** [luckydog7/Funkin-android#355]
i need someone to edit the 6th song named "sugar rush"
heres the mod: 
https://gamebanana.com/gamefiles/17474
 i just need the "sugar rush" json files
i will put it in as the monster song

**Comment by MrTks216** [comment]
Let me help, send file to me

**Comment by ROBIKALIVE13** [comment]
https://drive.google.com/file/d/1BpCbzt1ZqSYKdhYcQKDXN2O9Tedvrsfq/view?usp=drivesdk

**Comment by MrTks216** [comment]
here:
https://mega.nz/folder/llQRUAhI#dUVMnKKmVZZOtDVShNdrPA

**Comment by ROBIKALIVE13** [comment]
it work tysm

**Comment by MrTks216** [comment]
> it work tysm

you're welcome

**Comment by MrTks216** [comment]
and thx for the monster file, i need it too for your mod

**Comment by ROBIKALIVE13** [comment]
no problem

**Comment by MrTks216** [comment]
oh i forgot about the monster song, could you send to me? i too lazy to download the mod.

**Comment by MrTks216** [comment]
> oh i forgot about monster (suger-rush)song, could you send to me? i too lazy to download the mod.

**Comment by ROBIKALIVE13** [comment]
the original or the mod one?

**Comment by MrTks216** [comment]
> the original or the mod one?

oh sry, i mean suger-rush song

**Comment by ROBIKALIVE13** [comment]
u need the inst and the voice right?

**Comment by MrTks216** [comment]
> u need the inst and the voice right?

Yes, both

**Comment by ROBIKALIVE13** [comment]
gimme a sec

**Comment by MrTks216** [comment]
> gimme a sec

okay, thx again

**Comment by ROBIKALIVE13** [comment]
link:
https://drive.google.com/file/d/1CBDpmsNA1rZ33rnaAQC20yZhh3jZ8hQF/view?usp=drivesdk
here it is

**Comment by ROBIKALIVE13** [comment]
i put everything that u need

**Comment by MrTks216** [comment]
Alright 👍
