### ISSUE TITLE
Kade dev demo2 + B3 AND B SIDES

### ISSUE THREAD

**Issue by woaa12** [luckydog7/Funkin-android#357]
b sides screenshots (from #349):
![115098934-6d591500-9f65-11eb-9756-e0013a6f5b1c](https://user-images.githubusercontent.com/78597960/115128442-c5b30580-9fab-11eb-9110-a006613c1423.jpg)
![115098937-6fbb6f00-9f65-11eb-8289-677c2b380765](https://user-images.githubusercontent.com/78597960/115128445-ca77b980-9fab-11eb-84f3-2fb47a7765aa.jpg)
![115098940-70540580-9f65-11eb-9d3f-2183dd54a0e1](https://user-images.githubusercontent.com/78597960/115128448-cf3c6d80-9fab-11eb-8627-9d2d952985da.jpg)
B3 screenshots:
![Screenshot_2021-04-17-17-08-56](https://user-images.githubusercontent.com/78597960/115128461-eaa77880-9fab-11eb-8347-6c29343545ee.png)
![Screenshot_2021-04-17-17-07-19](https://user-images.githubusercontent.com/78597960/115128479-06ab1a00-9fac-11eb-8894-0e8293b185e5.png)
![Screenshot_2021-04-17-17-09-32](https://user-images.githubusercontent.com/78597960/115128484-0f035500-9fac-11eb-8457-a9e02bf0f1ba.png)
ALSO icons for hitbox (theres b side verisons dont worry b side players):
![Screenshot_2021-04-17-18-32-48](https://user-images.githubusercontent.com/78597960/115128501-31956e00-9fac-11eb-8cf5-2df843ccc2eb.png)
![Screenshot_2021-04-17-18-33-18](https://user-images.githubusercontent.com/78597960/115128505-3c500300-9fac-11eb-9f4d-fddc2ae7e128.png)
B sides link:
https://www.mediafire.com/file/8mn42pe4zkruvd4/more+like+twist+side.apk/file
B3 link https://www.mediafire.com/file/z6vo3rcfvw2j7lo/b3+b3+b3+b3.apk/file
Demo 2 itself (lite):
https://www.mediafire.com/file/6hwewedeyl7pa8v/fnf+kade+dev+demo+2+finally.apk/file

**Comment by kadeable** [comment]
Did you fix downscroll

**Comment by woaa12** [comment]
> Did you fix downscroll

Sadly no, im not a coder
