### ISSUE TITLE
FNF VS. KAPI mod with K-Dev 

### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#362]
Three new song on week 1 and 2
Week 1:
bopeebo = wocky
fresh = beathoven
Week 2
spookeez = flatzone
Preview:
![Screenshot_2021-04-18-19-18-24-441_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115144258-4e01db00-a07e-11eb-9bc2-c0bf54102cd6.jpg)
Week 1 and 2 
![Screenshot_2021-04-18-19-18-36-675_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115144262-578b4300-a07e-11eb-9f87-bc139cd98c0d.jpg)
Week 1 (Dad replace kapi, no cutscenes)
![Screenshot_2021-04-18-19-19-04-694_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115144316-a1742900-a07e-11eb-9980-8c71c102d9ca.jpg)
Week 2 (Skid and Pump replace Mr. Game)
![Screenshot_2021-04-18-19-19-51-549_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115144410-0cbdfb00-a07f-11eb-9be3-4a218a99704d.jpg)

That all, here the link:
(Delete)
Have a good day :-)

**Comment by FridayNightSans** [comment]
Gg

**Comment by woaa12** [comment]
Call me "lite it up" guy
https://www.mediafire.com/file/ggmakrdvtukfphf/discord+lite+theme.apk/file

**Comment by DanisLixo** [comment]
> Call me "lite it up" guy
> https://www.mediafire.com/file/ggmakrdvtukfphf/discord+lite+theme.apk/file

:-/
