### ISSUE TITLE
Mod request 

### ISSUE THREAD

**Issue by BoyfriendFNF** [luckydog7/Funkin-android#364]
can anyone port Boyfriend Must Die mod?

**Comment by VitalieW0WKid** [comment]
Why you can't do it yourself? Just watch a tutorial

**Comment by BoyfriendFNF** [comment]
> Why you can't do it yourself? Just watch a tutorial

I don't have a laptop to compile the game.

**Comment by woaa12** [comment]
> can anyone port Boyfriend Must Die mod?

You need a source code thingy to do that

**Comment by BoyfriendFNF** [comment]
> > can anyone port Boyfriend Must Die mod?
> 
> You need a source code thingy to do that

I know

**Comment by BoyfriendFNF** [comment]
please???
