### ISSUE TITLE
I GOT A WEEK 7 ZIP FILE

### ISSUE THREAD

**Issue by Alessio2010** [luckydog7/Funkin-android#406]
But idk how to share the files

**Comment by Alessio2010** [comment]
Can someone help me?

**Comment by Gabriel194150** [comment]
I don't know either, search for a tutorial

**Comment by Alessio2010** [comment]
I GOT AN IDEA

**Comment by Alessio2010** [comment]
https://www.mediafire.com/file/cqv9fym189mr4hb/1528775_alternate_113347_r86.zip.zip/file here

**Comment by Gabriel194150** [comment]
Good 👏

**Comment by FridayNightSans** [comment]
Zip? Bruh that not help nothin

**Comment by Gabriel194150** [comment]
I know that and it's very difficult to do week 7 on Android, and tab the cutsenes

**Comment by kadeable** [comment]
WHAT THE HELL ARE WE SUPPOSED TO DO WITH THAT WOW THANKS FOR NOTHING YOU USELESS SHIT

**Comment by Gabriel194150** [comment]
o-o calm down

**Comment by DabKnight** [comment]
I'll try to add this mod to the game.
root for me bois

**Comment by kadeable** [comment]
DABKKIGHT

**Comment by Alessio2010** [comment]
> WHAT THE HELL ARE WE SUPPOSED TO DO WITH THAT WOW THANKS FOR NOTHING YOU USELESS SHIT

woah calm down i was trying to help

**Comment by Alessio2010** [comment]
In the zip there are the files

**Comment by Alessio2010** [comment]
I thought maybe the files could be useful

**Comment by DabKnight** [comment]
WELL SHIT BISCUITS I CANT DO IT.

**Comment by kadeable** [comment]
Ok sorry  I meant to say that you can't add files in apk editor

**Comment by DabKnight** [comment]
> Ok sorry I meant to say that you can't add files in apk editor

WELL SHIT :)
RIP.

**Comment by Alessio2010** [comment]
> WELL SHIT BISCUITS I CANT DO IT.

Ok

**Comment by DabKnight** [comment]
I tried to do it again then this showed up:
![Screenshot_20210420_172657](https://user-images.githubusercontent.com/82740118/115373419-71539400-a1fe-11eb-8be0-37cd89b02501.jpg)

**Comment by Alessio2010** [comment]
> I tried to do it again then this showed up:
> ![Screenshot_20210420_172657](https://user-images.githubusercontent.com/82740118/115373419-71539400-a1fe-11eb-8be0-37cd89b02501.jpg)

Ok

**Comment by Alessio2010** [comment]
I will close this issue

**Comment by DabKnight** [comment]
Aw

**Comment by Alessio2010** [comment]
If the zip will be useful maybe I open again the issue

**Comment by softonicblip** [comment]
I will take a look at it

**Comment by softonicblip** [comment]
so, it worked for me, but the problem is that it freezes at 0%

![Screenshot_20210424-135612](https://user-images.githubusercontent.com/66886545/115966788-87669a80-a505-11eb-9461-bd8c98dc939a.png)
