### ISSUE TITLE
fnf rapper gf mod for android

### ISSUE THREAD

**Issue by mcagabe19** [luckydog7/Funkin-android#424]
low end link (2 or 3gb ram):https://bit.ly/3gnDn7D

lite (4gb ram and above):https://bit.ly/3emIJNA

changes (valid for all links)
removed: week 5 mom and dad, week 5 santa, week 6 girls, girlfriend (all weeks)

bugs: rapper girlfriend black textures (valid for tutorial and week 1 2 3 4 2gb ram phone or tab)

changed to: week 6 dialogs (xd)

enjoy :)
(I uploaded mega mediafire is too bad)

**Comment by yassir1186** [comment]
Hey dude pls can you make it the apk mediafıre before I have some problems on this link

**Comment by mcagabe19** [comment]
oh :( I'll wait too long again
