### ISSUE TITLE
FNF RTX:ON (Android/Optimized)

### ISSUE THREAD

**Issue by FridayNightSans** [luckydog7/Funkin-android#444]
Lol, this is a new update from gamebanana for fnf vibe. Check it out, and ye. It optimized
Link:
Like always, still uploading
Week 4(Mom road, bg update)
![Screenshot_20210421-174550](https://user-images.githubusercontent.com/81144896/115551693-a1ba3180-a2d5-11eb-8e99-b44c1c36e2de.png)
Week 6:
![Screenshot_20210421-174503](https://user-images.githubusercontent.com/81144896/115551729-ae3e8a00-a2d5-11eb-8370-2dddaa0c9e59.png)
BonusBonus!Sky also in here lol :))

**Comment by StrawRetro** [comment]
> Lol, this is a new update from gamebanana for fnf vibe. Check it out, and ye. It optimized
> Link:
> Like always, still uploading
> Week 4(Mom road, bg update)
> ![Screenshot_20210421-174550](https://user-images.githubusercontent.com/81144896/115551693-a1ba3180-a2d5-11eb-8e99-b44c1c36e2de.png)
> Week 6:
> ![Screenshot_20210421-174503](https://user-images.githubusercontent.com/81144896/115551729-ae3e8a00-a2d5-11eb-8370-2dddaa0c9e59.png)
> BonusBonus!Sky also in here lol :))

Hitboc ?

**Comment by FridayNightSans** [comment]
> > Lol, this is a new update from gamebanana for fnf vibe. Check it out, and ye. It optimized
> > Link:
> > Like always, still uploading
> > Week 4(Mom road, bg update)
> > ![Screenshot_20210421-174550](https://user-images.githubusercontent.com/81144896/115551693-a1ba3180-a2d5-11eb-8e99-b44c1c36e2de.png)
> > Week 6:
> > ![Screenshot_20210421-174503](https://user-images.githubusercontent.com/81144896/115551729-ae3e8a00-a2d5-11eb-8370-2dddaa0c9e59.png)
> > BonusBonus!Sky also in here lol :))
> 
> Hitboc ?

Hitbox too

**Comment by StrawRetro** [comment]
> > > Lol, this is a new update from gamebanana for fnf vibe. Check it out, and ye. It optimized
> > > Link:
> > > Like always, still uploading
> > > Week 4(Mom road, bg update)
> > > ![Screenshot_20210421-174550](https://user-images.githubusercontent.com/81144896/115551693-a1ba3180-a2d5-11eb-8e99-b44c1c36e2de.png)
> > > Week 6:
> > > ![Screenshot_20210421-174503](https://user-images.githubusercontent.com/81144896/115551729-ae3e8a00-a2d5-11eb-8370-2dddaa0c9e59.png)
> > > BonusBonus!Sky also in here lol :))
> > 
> > 
> > Hitboc ?
> 
> Hitbox too

men I love ur mods

**Comment by FridayNightSans** [comment]
> > > > Lol, this is a new update from gamebanana for fnf vibe. Check it out, and ye. It optimized
> > > > Link:
> > > > Like always, still uploading
> > > > Week 4(Mom road, bg update)
> > > > ![Screenshot_20210421-174550](https://user-images.githubusercontent.com/81144896/115551693-a1ba3180-a2d5-11eb-8e99-b44c1c36e2de.png)
> > > > Week 6:
> > > > ![Screenshot_20210421-174503](https://user-images.githubusercontent.com/81144896/115551729-ae3e8a00-a2d5-11eb-8370-2dddaa0c9e59.png)
> > > > BonusBonus!Sky also in here lol :))
> > > 
> > > 
> > > Hitboc ?
> > 
> > 
> > Hitbox too
> 
> men I love ur mods

Ok, i will close this and reupload new issue, bye

**Comment by ChickenHat23** [comment]
Ayo where link?

**Comment by BoyfriendFNF** [comment]
> Ayo where link?

uploading
