### ISSUE TITLE
Another Friday Night fnf mod (Tutorial,Week 1-3)

### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#446]
New colour design and New song
Preview:
![Screenshot_2021-04-21-20-45-46-984_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115558627-82c39b80-a2e5-11eb-8e9d-62924d7439f9.jpg)
![Screenshot_2021-04-21-20-45-17-907_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115558661-89eaa980-a2e5-11eb-90f0-5f389f8443d3.jpg)
[Week 1]
![Screenshot_2021-04-21-20-44-56-685_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115558712-966f0200-a2e5-11eb-8bd1-3ec84698d2db.jpg)
[Week 2] (Monster song nothing change)
![Screenshot_2021-04-21-20-44-26-129_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115558773-a4bd1e00-a2e5-11eb-9caf-945ae1c044ce.jpg)
[Week 3]
![Screenshot_2021-04-21-20-46-20-392_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115558895-c4544680-a2e5-11eb-986d-15803673dc23.jpg)

That all, here the link:
(Go to #754 download new version)
Have fun :-)

**Comment by ROBIKALIVE13** [comment]
its a great mod i like it

**Comment by MrTks216** [comment]
> its a great mod i like it

Yeah, i love this mod song, it good.
