### ISSUE TITLE
fnf rapper gf mod (this is end)

### ISSUE THREAD

**Issue by mcagabe19** [luckydog7/Funkin-android#453]
download with chrome
low end link (2 or 3gb ram):https://bit.ly/3gnDn7D

lite (4gb ram and above):https://bit.ly/3emIJNA

changes (valid for all links)
removed: week 5 mom and dad, week 5 santa, week 6 girls, girlfriend (all weeks)

bugs: rapper girlfriend black textures (valid for tutorial and week 1 2 3 4 2gb ram phone or tablet)

changed: week 6 dialogs with translate (xd)

enjoy :)
(I uploaded mega. Mediafire is too bad)
[I am Turkish, I hope you will understand what I wrote]

**Comment by StrawRetro** [comment]
> download with chrome
> low end link (2 or 3gb ram):https://bit.ly/3gnDn7D
> 
> lite (4gb ram and above):https://bit.ly/3emIJNA
> 
> changes (valid for all links)
> removed: week 5 mom and dad, week 5 santa, week 6 girls, girlfriend (all weeks)
> 
> bugs: rapper girlfriend black textures (valid for tutorial and week 1 2 3 4 2gb ram phone or tablet)
> 
> changed: week 6 dialogs with translate (xd)
> 
> enjoy :)
> (I uploaded mega. Mediafire is too bad)
> [I am Turkish, I hope you will understand what I wrote]

skinti yok ingilizcen de :d

**Comment by mcagabe19** [comment]
xd
