### ISSUE TITLE
Kade engine Android port 3.0 with original FNF assets

### ISSUE THREAD

**Issue by sonicyt1234** [luckydog7/Funkin-android#454]
Can someone make that for me? Also please do not remove the gfcheer animation

**Comment by woaa12** [comment]
"Original FNF assets"?

**Comment by WyxosYT** [comment]
Lol I'm already doing that![Screenshot_20210421_220440_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/82682892/115643119-1744f280-a314-11eb-8839-b7c61ce94e22.jpg)
![Screenshot_20210420_201707_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/82682892/115643142-20ce5a80-a314-11eb-8af0-7db9194ec189.jpg)

**Comment by WyxosYT** [comment]
It's gonna take a while but yes.

**Comment by DabKnight** [comment]
> Lol I'm already doing that![Screenshot_20210421_220440_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/82682892/115643119-1744f280-a314-11eb-8839-b7c61ce94e22.jpg)
> ![Screenshot_20210420_201707_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/82682892/115643142-20ce5a80-a314-11eb-8af0-7db9194ec189.jpg)

I think he meant replace the assets from the kade engine with the original assets.
Not week 7.
But sure gl with that

**Comment by WyxosYT** [comment]
> > Lol I'm already doing that![Screenshot_20210421_220440_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/82682892/115643119-1744f280-a314-11eb-8839-b7c61ce94e22.jpg)
> > ![Screenshot_20210420_201707_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/82682892/115643142-20ce5a80-a314-11eb-8af0-7db9194ec189.jpg)
> 
> I think he meant replace the assets from the kade engine with the original assets.
> Not week 7.
> But sure gl with that

Yeah thx and I'm kinda close lol![Screenshot_20210422_214429_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/82682892/115783059-5034a400-a3b4-11eb-9c28-6333fa59b9d3.jpg)
I might be able to upload the apk file when week 7 fully drops (I think)
(Pls don't tell me it's tommorow or something zhzhzsb)

**Comment by WyxosYT** [comment]
https://youtu.be/X5J-5K0GxY8
First preview of my port out lol

**Comment by WyxosYT** [comment]
Here's a week 7 preview;
![Screenshot_20210424_163920_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/82682892/115969516-2f478c80-a535-11eb-98fc-6146475a758b.jpg)
https://youtu.be/Kpr2uJB231Y

**Comment by TheMinero14** [comment]
#538  I'm make this

**Comment by sonicyt1234** [comment]
Thanks
