### ISSUE TITLE
Fnf Wii Funkin' VSMatt 2.0 FULL WEEK mod (old)

### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#461]
New ver #975
New update vs Matt 2.0
Add Wiik 2 Two New Song
Skid and Pump replace Mad Matt
Spookeez = sporting
South = boxing-match
Preview:
![Screenshot_2021-04-22-20-30-52-759_com.ninjamuffin29.funkin.jpg](https://user-images.githubusercontent.com/81964285/115715464-bcaaa580-a3aa-11eb-8e4e-0b1b2c8cbd7f.jpg)
![Screenshot_2021-04-22-20-31-01-383_com.ninjamuffin29.funkin.jpg](https://user-images.githubusercontent.com/81964285/115715653-efed3480-a3aa-11eb-97fe-8fbd55ef8c85.jpg)
Wiik 1 and Wiik 2
![Screenshot_2021-04-22-20-31-24-474_com.ninjamuffin29.funkin.jpg](https://user-images.githubusercontent.com/81964285/115715748-0a271280-a3ab-11eb-8d17-82f6a4e7a246.jpg)
Wiik 2 ( madmatt still flying) (No Dialogue)
![Screenshot_2021-04-22-20-31-47-470_com.ninjamuffin29.funkin.jpg](https://user-images.githubusercontent.com/81964285/115715787-1612d480-a3ab-11eb-9fd9-310e6c80b965.jpg)

Here the link:
Mediafire:
(Already Delete. Go to #975 Download New Version)
Mega:
(Already Delete. Go to #975 Download New Version)

That all, bye lol

**Comment by FridayNightSans** [comment]
Ok, this is time to break my fingers

**Comment by MrTks216** [comment]
> Ok, this is time to break my fingers

Good luck, i still can't pass third song 😅

**Comment by ROBIKALIVE13** [comment]
its time to probably break my fingers and let matt punch the h*ll out of me

**Comment by MrTks216** [comment]
> its time to probably break my fingers and let matt punch the h*ll out of me

oof, good luck with that, i will pass third song in wiik 1. (I hope)

**Comment by ROBIKALIVE13** [comment]
i almost failed the second one

**Comment by MrTks216** [comment]
oof, still cannot beat third song on normal. i hate you matt

**Comment by ROBIKALIVE13** [comment]
i can beat the third song with that crappy aimbot xd

**Comment by ROBIKALIVE13** [comment]
and spammed my controllers B button xd

**Comment by ROBIKALIVE13** [comment]
i almost failed with THAT method xD

**Comment by MrTks216** [comment]
> i almost failed with THAT method xD

bruh, are you still awake? rn 3:36a.m

**Comment by MrTks216** [comment]
Anyways, i gonna sleep, gn.

**Comment by ROBIKALIVE13** [comment]
gn

**Comment by mcagabe19** [comment]
hahaha i finished on a single

**Comment by A44yFNF** [comment]
amazing

**Comment by EdgeGD** [comment]
is there hitboxes

**Comment by MrTks216** [comment]
> is there hitboxes

yes, there is hitbox

**Comment by MrTks216** [comment]
Hell yeah, finally beat third song on normal. Gonna try wiik 2 next time

**Comment by ROBIKALIVE13** [comment]
> Hell yeah, finally beat third song on normal. Gonna try wiik 2 next time

how? i can only beat easy with hitbox xd

**Comment by MrTks216** [comment]
> > Hell yeah, finally beat third song on normal. Gonna try wiik 2 next time
> 
> how? i can only beat easy with hitbox xd

play with custom control and downscroll.

**Comment by ROBIKALIVE13** [comment]
> > > Hell yeah, finally beat third song on normal. Gonna try wiik 2 next time
> > 
> > how? i can only beat easy with hitbox xd
> 
> play with custom control and downscroll.

its not my style

**Comment by MrTks216** [comment]
> > > > Hell yeah, finally beat third song on normal. Gonna try wiik 2 next time
> > > 
> > > how? i can only beat easy with hitbox xd
> > 
> > play with custom control and downscroll.
> 
> its not my style

Well, you can try it, let you more easy to play.

**Comment by ROBIKALIVE13** [comment]
i beat it on normal without spamming :3

**Comment by MrTks216** [comment]
> i beat it on normal without spamming :3

Oh great, prepare to play wiik 2 on normal.

**Comment by MrTks216** [comment]
it very painful to play wiik 2.

**Comment by ROBIKALIVE13** [comment]
ik
