### ISSUE TITLE
amog us fnf

### ISSUE THREAD

**Issue by silent-ui** [luckydog7/Funkin-android#468]
spam amog us here :trollface: :trollface: 

AMOG US boyfriend sus

**Comment by briannewmc22a** [comment]
When the imposter is sus 😳😳😳😳😳😳😳😳😳😳😳

**Comment by briannewmc22a** [comment]
:trollface:

**Comment by BoyfriendFNF** [comment]
> When the imposter is sus 😳😳😳😳😳😳😳😳😳😳😳

when the impostEr is steering

**Comment by BabayFnf** [comment]
![1619154242130](https://user-images.githubusercontent.com/82819974/115855438-ea87fc80-a433-11eb-95ea-bda20ba277b5.png)

**Comment by EdgeGD** [comment]
sus

**Comment by HatredVi** [comment]
Im going to eat all of you

**Comment by FridayNightVibin** [comment]
Po is kinda sus
