### ISSUE TITLE
please make fnf android version with this engine 

### ISSUE THREAD

**Issue by ElPeppyWall** [luckydog7/Funkin-android#47]
could you please make a version with this [engine?](https://github.com/KadeDev/Kade-Engine)

**Comment by DanisLixo** [comment]
I think he's already using it, I just think.

**Comment by LoserBFDI** [comment]
i agree with him, its going to be less laggy if you used that (im patient).

**Comment by Pixelneery** [comment]
> I think he's already using it, I just think.

Yeah he's not using it there's no ACCURACY bar and percentage of how accurate you are

**Comment by ElPeppyWall** [comment]
@luckydog7 ??
