### ISSUE TITLE
Fnf Don't Funk At Night mod (wip) (tutorial, week 1)

### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#494]
Another High quality mod (work in progress)
and I didn't make this mod. Just showcase.
New remix, New background. Only tutorial and week 1 are done, other didn't finish yet.
Girlfriend replace Alex
Boyfriend replace Steve
Dad replace Enderman
Some of the songs are done, like:
Tutorial, Week 1, South, Monster (only normal can play), Satin Panties, and Milf

Preview:
![Screenshot_2021-04-24-18-28-12-601_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115955803-70d33a00-a52b-11eb-887d-16297a309404.jpg)
![Screenshot_2021-04-24-18-28-21-766_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115955899-1d152080-a52c-11eb-96e9-97e12431eeb5.jpg)
![Screenshot_2021-04-24-18-28-31-546_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115955907-243c2e80-a52c-11eb-92b3-d983e3fa43b3.jpg)
[Tutorial]
![Screenshot_2021-04-24-18-28-43-862_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115955925-3ae28580-a52c-11eb-9ee5-81c7c956f063.jpg)
[Week 1]
![Screenshot_2021-04-24-18-29-10-110_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115955933-4b92fb80-a52c-11eb-8056-5df76341ea22.jpg)
![Screenshot_2021-04-24-18-29-18-078_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/115955940-59488100-a52c-11eb-94ee-639b3f6da25a.jpg)

Download link:
https://mega.nz/file/QogQQD7T#FXeHUQgSNZEe6kPZCCPAEkSp70GN72LHCZBqnrG4gLQ
The original mod : https://gamebanana.com/wips/53478

That all, peace out ✌

**Comment by FridayNightSans** [comment]
Wait, is this your mod? ;-;

**Comment by MrTks216** [comment]
> Wait, is this your mod? ;-;

nah, not mine

**Comment by Justine101213k** [comment]
Minecraft LOL

**Comment by tyromix09** [comment]
Eyyyyy I wanted to do that but I was too lazy to do so, thanks for doing it for me

**Comment by derrickthednflover** [comment]
Is there any new version

**Comment by MrTks216** [comment]
> Is there any new version

this is new version, and i can't download this mod anymore. The creator of this mod already take down download link.
More details in here:
https://gamebanana.com/wips/53478

**Comment by Tankakuka** [comment]
Can this version of the mod be taken down by any means? I did not ask for anyone to port the mod over to anything and I've cancelled the project until further notice.

**Comment by juanroman74454811** [comment]
> Can this version of the mod be taken down by any means? I did not ask for anyone to port the mod over to anything and I've cancelled the project until further notice.

please let me try the mod
