### ISSUE TITLE
JUST MAKE WEEK 7 JESUS FUCKING CHRIST

### ISSUE THREAD

**Issue by kadeable** [luckydog7/Funkin-android#498]

**Comment by LarryFrosty** [comment]
I'd like to see you make it you fucking impatient guy
they havent even got the source code released yet

**Comment by BoyfriendFNF** [comment]
> I'd like to see you make it you fucking impatient guy
> they havent even got the source code released yet

yeah, no source code no week.

**Comment by ROBIKALIVE13** [comment]
WAIT

**Comment by MrTks216** [comment]
Bruh, this kid again.
