### ISSUE TITLE
how do mods for example bsides in that version?

### ISSUE THREAD

**Issue by Gabriel66665** [luckydog7/Funkin-android#52]

**Comment by Pixelneery** [comment]
Hi i made a tutorial on how to mod the game : https://youtu.be/6Gvi85tsEFk

**Comment by Gabriel66665** [comment]
in the old version I know how to do it I'm asking in this version 0.2.7.1

**Comment by Pixelneery** [comment]
> in the old version I know how to do it I'm asking in this version 0.2.7.1

YES IT'S STILL THE SAME WAY THE ONLY DIFFERENT THINGS IS THE FILES LOCATION IS NOW SWAPPED FOR SOME SMOOTHER GAMEPLAY BRUH LIKE THE SONGS FOLDER IS FOR THE SONGS THE DATA FOLDER FOR THE CHARTS AND THE SHARED FOLDER IS FOR WEEK 1, IT'S STILL THE SAME WAY

**Comment by DanisLixo** [comment]
> > in the old version I know how to do it I'm asking in this version 0.2.7.1
> 
> YES IT'S STILL THE SAME WAY THE ONLY DIFFERENT THINGS IS THE FILES LOCATION IS NOW SWAPPED FOR SOME SMOOTHER GAMEPLAY BRUH LIKE THE SONGS FOLDER IS FOR THE SONGS THE DATA FOLDER FOR THE CHARTS AND THE SHARED FOLDER IS FOR WEEK 1, IT'S STILL THE SAME WAY

Okay, after this beautiful and totally controlled tutorial, you know how to do mods. @Gabriel66665 you can closd now

**Comment by Gabriel66665** [comment]
Ok, depois desse tutorial lindo e totalmente controlado, você já sabe como fazer mods. @ Gabriel66665 você pode fechar agora
