### ISSUE TITLE
the character bugs when being on different maps

### ISSUE THREAD

**Issue by DanisLixo** [luckydog7/Funkin-android#53]
For some reason, if I want to change characters in the debug menu, the game crashes.  And when I put a mod and the selected character in the .json file is not originally from the map, when entering the song, the game crashes again. But for some other reason. The BF, GF and the Dad they are not affected by this bug which is... Strange.

https://youtu.be/KIumcfXlTQU

**Comment by Rs232k** [comment]
Source problem.
