### ISSUE TITLE
Does anyone have the bf+gf sprite sheet and xml?

### ISSUE THREAD

**Issue by kffwlp** [luckydog7/Funkin-android#542]

**Comment by VitalieW0WKid** [comment]
Why

**Comment by ElioTheBoi** [comment]
I have the sprites idk about the xml
![Uploading bfAndGF.png…]()
![Uploading bfHoldingGF-DEAD.png…]()

**Comment by ElioTheBoi** [comment]
I only have the sprites idk about the  xml
![Uploading bfAndGF.png…]()
![Uploading bfHoldingGF-DEAD.png…]()

Oops did i upload the files right i didnt really use github before :P

**Comment by DanisLixo** [comment]
https://www.mediafire.com/file/e0v3f9jtrtpd4td/a_strong_boy_holding_ur_hot_girl.zip/file
beep

**Comment by kffwlp** [comment]
Thank you!
