### ISSUE TITLE
Friday Night Funkin' Modded and Modpack (Lite)

### ISSUE THREAD

**Issue by DanisLixo** [luckydog7/Funkin-android#557]
FNF' Modded: https://drive.google.com/file/d/1W3iGtwp9btMyJrpj48iff9s3sAM364Y0/view?usp=drivesdk

Changes:

- The characters and scenarios are now in the shared folder (now you can use senpai on week 3 to play Spookeez);
- Boyfriend now can be Blue Balled (Thanks to FNF' MOBILE Discord Server)
- The songs have the recharts of the week 7 update;
- The Parents now appears (They are tiny);
- You can select Downscroll and immortality in the options;
- Sky Icons.

Added:

- Sky mod included but pls, read the warning;
- Week 7 Songs (Only Freeplay) (No Tankman, Pico on the Speaker and BF Holding GF);
- Test Song With Vocals and the original Chart (Tutorial on Easy).

Note: You can't leave Story mode, you need to return to menu in the pause.

![Screenshot_20210429-200621](https://user-images.githubusercontent.com/58278276/116629495-c3e02f00-a927-11eb-9f56-ac9516e4db2d.png)
![Screenshot_20210429-200547](https://user-images.githubusercontent.com/58278276/116629498-c5115c00-a927-11eb-958a-fa0a9d0e58a8.png)
![Screenshot_20210429-200452](https://user-images.githubusercontent.com/58278276/116629499-c5a9f280-a927-11eb-9e41-69f306a37db5.png)

ok I get it

FNF' Modpack (FNF' MOBILE Discord Server Demo 3.0): https://drive.google.com/file/d/1LIy50N58efnIw7HL1aC4TzhO_sVFSKLj/view?usp=drivesdk

Added:

- Tricky (No Lite);
- Foolhardy;
- Whitty;

Warning: B-sides, Neo, Miku, Matt and Sky are not working.

- Test Song (No chart and no Vocals, sorry:/);
- Downscroll (Note: The Health bar is always on the top.);
- New input (Note: doesn't change anything)

Warning: The gameplay of the game is very unstable, the mod only accepts sick hits.

- Health, Misses and Max Combo now appears (Note: Your life is doubled)

Changed:
App Icon;
Sky Health Icons;
Ballistic Whitty is now low quality 🤟😝.

![Screenshot_20210429-201502](https://user-images.githubusercontent.com/58278276/116629526-d2c6e180-a927-11eb-870a-d1569469ff9d.png)
![Screenshot_20210429-201229](https://user-images.githubusercontent.com/58278276/116629531-d3f80e80-a927-11eb-9f86-0add86478b07.png)
![Screenshot_20210429-200828](https://user-images.githubusercontent.com/58278276/116629534-d490a500-a927-11eb-9a1e-5478bd93201f.png)
![Screenshot_20210429-200735](https://user-images.githubusercontent.com/58278276/116629536-d5c1d200-a927-11eb-898d-c25e114f47c1.png)
![Screenshot_20210429-200718](https://user-images.githubusercontent.com/58278276/116629538-d65a6880-a927-11eb-9127-2f2e67b7b6fc.png)
![Screenshot_20210429-200704](https://user-images.githubusercontent.com/58278276/116629542-d78b9580-a927-11eb-82f2-c7543977fc08.png)

Friday Night Funkin' MOBILE Discord Server: https://discord.gg/RhxQ8Y8y

**Comment by DanisLixo** [comment]
more lite versions: #313

**Comment by DabKnight** [comment]
> FNF' Modded: https://drive.google.com/file/d/1W3iGtwp9btMyJrpj48iff9s3sAM364Y0/view?usp=drivesdk
> 
> Changes:
> 
> * The characters and scenarios are now in the shared folder (now you can use senpai on week 3 to play Spookeez);
> * Boyfriend now can be Blue Balled (Thanks to FNF' MOBILE Discord Server)
> * The songs have the recharts of the week 7 update;
> * The Parents now appears (They are tiny);
> * You can select Downscroll and immortality in the options;
> * Sky Icons.
> 
> Added:
> 
> * Sky mod included but pls, read the warning;
> * Week 7 Songs (Only Freeplay) (No Tankman, Pico on the Speaker and BF Holding GF);
> * Test Song With Vocals and the original Chart (Tutorial on Easy).
> 
> Note: You can't leave Story mode, you need to return to menu in the pause.
> 
> ![Screenshot_20210429-200621](https://user-images.githubusercontent.com/58278276/116629495-c3e02f00-a927-11eb-9f56-ac9516e4db2d.png)
> ![Screenshot_20210429-200547](https://user-images.githubusercontent.com/58278276/116629498-c5115c00-a927-11eb-958a-fa0a9d0e58a8.png)
> ![Screenshot_20210429-200452](https://user-images.githubusercontent.com/58278276/116629499-c5a9f280-a927-11eb-9e41-69f306a37db5.png)
> 
> FNF' Modpack (FNF' MOBILE Discord Server Demo 3.0): https://drive.google.com/file/d/1LIy50N58efnIw7HL1aC4TzhO_sVFSKLj/view?usp=drivesdk
> 
> Added:
> 
> * Tricky (No Lite);
> * Foolhardy;
> * Whitty;
> 
> Warning: B-sides, Neo, Miku, Matt and Sky are not working.
> 
> * Test Song (No chart and no Vocals, sorry:/);
> * Downscroll (Note: The Health bar is always on the top.);
> * New input (Note: doesn't change anything)
> 
> Warning: The gameplay of the game is very unstable, the mod only accepts sick hits.
> 
> * Health, Misses and Max Combo now appears (Note: Your life is doubled)
> 
> Changed:
> App Icon;
> Sky Health Icons;
> Ballistic Whitty is now low quality 🤟😝.
> 
> ![Screenshot_20210429-201502](https://user-images.githubusercontent.com/58278276/116629526-d2c6e180-a927-11eb-870a-d1569469ff9d.png)
> ![Screenshot_20210429-201229](https://user-images.githubusercontent.com/58278276/116629531-d3f80e80-a927-11eb-9f86-0add86478b07.png)
> ![Screenshot_20210429-200828](https://user-images.githubusercontent.com/58278276/116629534-d490a500-a927-11eb-9a1e-5478bd93201f.png)
> ![Screenshot_20210429-200735](https://user-images.githubusercontent.com/58278276/116629536-d5c1d200-a927-11eb-898d-c25e114f47c1.png)
> ![Screenshot_20210429-200718](https://user-images.githubusercontent.com/58278276/116629538-d65a6880-a927-11eb-9127-2f2e67b7b6fc.png)
> ![Screenshot_20210429-200704](https://user-images.githubusercontent.com/58278276/116629542-d78b9580-a927-11eb-82f2-c7543977fc08.png)
> 
> Friday Night Funkin' MOBILE Discord Server: https://discord.gg/RhxQ8Y8y

Damn the server's not english :(

**Comment by FridayNightVibin** [comment]
> > FNF' Modded: https://drive.google.com/file/d/1W3iGtwp9btMyJrpj48iff9s3sAM364Y0/view?usp=drivesdk
> > Changes:
> > 
> > * The characters and scenarios are now in the shared folder (now you can use senpai on week 3 to play Spookeez);
> > * Boyfriend now can be Blue Balled (Thanks to FNF' MOBILE Discord Server)
> > * The songs have the recharts of the week 7 update;
> > * The Parents now appears (They are tiny);
> > * You can select Downscroll and immortality in the options;
> > * Sky Icons.
> > 
> > Added:
> > 
> > * Sky mod included but pls, read the warning;
> > * Week 7 Songs (Only Freeplay) (No Tankman, Pico on the Speaker and BF Holding GF);
> > * Test Song With Vocals and the original Chart (Tutorial on Easy).
> > 
> > Note: You can't leave Story mode, you need to return to menu in the pause.
> > ![Screenshot_20210429-200621](https://user-images.githubusercontent.com/58278276/116629495-c3e02f00-a927-11eb-9f56-ac9516e4db2d.png)
> > ![Screenshot_20210429-200547](https://user-images.githubusercontent.com/58278276/116629498-c5115c00-a927-11eb-958a-fa0a9d0e58a8.png)
> > ![Screenshot_20210429-200452](https://user-images.githubusercontent.com/58278276/116629499-c5a9f280-a927-11eb-9e41-69f306a37db5.png)
> > FNF' Modpack (FNF' MOBILE Discord Server Demo 3.0): https://drive.google.com/file/d/1LIy50N58efnIw7HL1aC4TzhO_sVFSKLj/view?usp=drivesdk
> > Added:
> > 
> > * Tricky (No Lite);
> > * Foolhardy;
> > * Whitty;
> > 
> > Warning: B-sides, Neo, Miku, Matt and Sky are not working.
> > 
> > * Test Song (No chart and no Vocals, sorry:/);
> > * Downscroll (Note: The Health bar is always on the top.);
> > * New input (Note: doesn't change anything)
> > 
> > Warning: The gameplay of the game is very unstable, the mod only accepts sick hits.
> > 
> > * Health, Misses and Max Combo now appears (Note: Your life is doubled)
> > 
> > Changed:
> > App Icon;
> > Sky Health Icons;
> > Ballistic Whitty is now low quality 🤟😝.
> > ![Screenshot_20210429-201502](https://user-images.githubusercontent.com/58278276/116629526-d2c6e180-a927-11eb-870a-d1569469ff9d.png)
> > ![Screenshot_20210429-201229](https://user-images.githubusercontent.com/58278276/116629531-d3f80e80-a927-11eb-9f86-0add86478b07.png)
> > ![Screenshot_20210429-200828](https://user-images.githubusercontent.com/58278276/116629534-d490a500-a927-11eb-9a1e-5478bd93201f.png)
> > ![Screenshot_20210429-200735](https://user-images.githubusercontent.com/58278276/116629536-d5c1d200-a927-11eb-898d-c25e114f47c1.png)
> > ![Screenshot_20210429-200718](https://user-images.githubusercontent.com/58278276/116629538-d65a6880-a927-11eb-9127-2f2e67b7b6fc.png)
> > ![Screenshot_20210429-200704](https://user-images.githubusercontent.com/58278276/116629542-d78b9580-a927-11eb-82f2-c7543977fc08.png)
> > Friday Night Funkin' MOBILE Discord Server: https://discord.gg/RhxQ8Y8y
> 
> Damn the server's not english :(

But u can play Whitty,tricky,foolhardy

**Comment by Zizoplays1** [comment]
I just downloaded it from fridaynightsans yesterday lol

**Comment by kffwlp** [comment]
Thank you so much I've been looking for this

**Comment by FridayNightSans** [comment]
> FNF' Modded: https://drive.google.com/file/d/1W3iGtwp9btMyJrpj48iff9s3sAM364Y0/view?usp=drivesdk
> 
> Changes:
> 
> * The characters and scenarios are now in the shared folder (now you can use senpai on week 3 to play Spookeez);
> * Boyfriend now can be Blue Balled (Thanks to FNF' MOBILE Discord Server)
> * The songs have the recharts of the week 7 update;
> * The Parents now appears (They are tiny);
> * You can select Downscroll and immortality in the options;
> * Sky Icons.
> 
> Added:
> 
> * Sky mod included but pls, read the warning;
> * Week 7 Songs (Only Freeplay) (No Tankman, Pico on the Speaker and BF Holding GF);
> * Test Song With Vocals and the original Chart (Tutorial on Easy).
> 
> Note: You can't leave Story mode, you need to return to menu in the pause.
> 
> ![Screenshot_20210429-200621](https://user-images.githubusercontent.com/58278276/116629495-c3e02f00-a927-11eb-9f56-ac9516e4db2d.png)
> ![Screenshot_20210429-200547](https://user-images.githubusercontent.com/58278276/116629498-c5115c00-a927-11eb-958a-fa0a9d0e58a8.png)
> ![Screenshot_20210429-200452](https://user-images.githubusercontent.com/58278276/116629499-c5a9f280-a927-11eb-9e41-69f306a37db5.png)
> 
> Thanks to FridayNightSans
> 
> FNF' Modpack (FNF' MOBILE Discord Server Demo 3.0): https://drive.google.com/file/d/1LIy50N58efnIw7HL1aC4TzhO_sVFSKLj/view?usp=drivesdk
> 
> Added:
> 
> * Tricky (No Lite);
> * Foolhardy;
> * Whitty;
> 
> Warning: B-sides, Neo, Miku, Matt and Sky are not working.
> 
> * Test Song (No chart and no Vocals, sorry:/);
> * Downscroll (Note: The Health bar is always on the top.);
> * New input (Note: doesn't change anything)
> 
> Warning: The gameplay of the game is very unstable, the mod only accepts sick hits.
> 
> * Health, Misses and Max Combo now appears (Note: Your life is doubled)
> 
> Changed:
> App Icon;
> Sky Health Icons;
> Ballistic Whitty is now low quality 🤟😝.
> 
> ![Screenshot_20210429-201502](https://user-images.githubusercontent.com/58278276/116629526-d2c6e180-a927-11eb-870a-d1569469ff9d.png)
> ![Screenshot_20210429-201229](https://user-images.githubusercontent.com/58278276/116629531-d3f80e80-a927-11eb-9f86-0add86478b07.png)
> ![Screenshot_20210429-200828](https://user-images.githubusercontent.com/58278276/116629534-d490a500-a927-11eb-9a1e-5478bd93201f.png)
> ![Screenshot_20210429-200735](https://user-images.githubusercontent.com/58278276/116629536-d5c1d200-a927-11eb-898d-c25e114f47c1.png)
> ![Screenshot_20210429-200718](https://user-images.githubusercontent.com/58278276/116629538-d65a6880-a927-11eb-9127-2f2e67b7b6fc.png)
> ![Screenshot_20210429-200704](https://user-images.githubusercontent.com/58278276/116629542-d78b9580-a927-11eb-82f2-c7543977fc08.png)
> 
> Friday Night Funkin' MOBILE Discord Server: https://discord.gg/RhxQ8Y8y

Erh? Why thanks?

**Comment by DanisLixo** [comment]
> > FNF' Modded: https://drive.google.com/file/d/1W3iGtwp9btMyJrpj48iff9s3sAM364Y0/view?usp=drivesdk
> > Changes:
> > 
> > * The characters and scenarios are now in the shared folder (now you can use senpai on week 3 to play Spookeez);
> > * Boyfriend now can be Blue Balled (Thanks to FNF' MOBILE Discord Server)
> > * The songs have the recharts of the week 7 update;
> > * The Parents now appears (They are tiny);
> > * You can select Downscroll and immortality in the options;
> > * Sky Icons.
> > 
> > Added:
> > 
> > * Sky mod included but pls, read the warning;
> > * Week 7 Songs (Only Freeplay) (No Tankman, Pico on the Speaker and BF Holding GF);
> > * Test Song With Vocals and the original Chart (Tutorial on Easy).
> > 
> > Note: You can't leave Story mode, you need to return to menu in the pause.
> > ![Screenshot_20210429-200621](https://user-images.githubusercontent.com/58278276/116629495-c3e02f00-a927-11eb-9f56-ac9516e4db2d.png)
> > ![Screenshot_20210429-200547](https://user-images.githubusercontent.com/58278276/116629498-c5115c00-a927-11eb-958a-fa0a9d0e58a8.png)
> > ![Screenshot_20210429-200452](https://user-images.githubusercontent.com/58278276/116629499-c5a9f280-a927-11eb-9e41-69f306a37db5.png)
> > Thanks to FridayNightSans
> > FNF' Modpack (FNF' MOBILE Discord Server Demo 3.0): https://drive.google.com/file/d/1LIy50N58efnIw7HL1aC4TzhO_sVFSKLj/view?usp=drivesdk
> > Added:
> > 
> > * Tricky (No Lite);
> > * Foolhardy;
> > * Whitty;
> > 
> > Warning: B-sides, Neo, Miku, Matt and Sky are not working.
> > 
> > * Test Song (No chart and no Vocals, sorry:/);
> > * Downscroll (Note: The Health bar is always on the top.);
> > * New input (Note: doesn't change anything)
> > 
> > Warning: The gameplay of the game is very unstable, the mod only accepts sick hits.
> > 
> > * Health, Misses and Max Combo now appears (Note: Your life is doubled)
> > 
> > Changed:
> > App Icon;
> > Sky Health Icons;
> > Ballistic Whitty is now low quality 🤟😝.
> > ![Screenshot_20210429-201502](https://user-images.githubusercontent.com/58278276/116629526-d2c6e180-a927-11eb-870a-d1569469ff9d.png)
> > ![Screenshot_20210429-201229](https://user-images.githubusercontent.com/58278276/116629531-d3f80e80-a927-11eb-9f86-0add86478b07.png)
> > ![Screenshot_20210429-200828](https://user-images.githubusercontent.com/58278276/116629534-d490a500-a927-11eb-9a1e-5478bd93201f.png)
> > ![Screenshot_20210429-200735](https://user-images.githubusercontent.com/58278276/116629536-d5c1d200-a927-11eb-898d-c25e114f47c1.png)
> > ![Screenshot_20210429-200718](https://user-images.githubusercontent.com/58278276/116629538-d65a6880-a927-11eb-9127-2f2e67b7b6fc.png)
> > ![Screenshot_20210429-200704](https://user-images.githubusercontent.com/58278276/116629542-d78b9580-a927-11eb-82f2-c7543977fc08.png)
> > Friday Night Funkin' MOBILE Discord Server: https://discord.gg/RhxQ8Y8y
> 
> Erh? Why thanks?

cuz the fnf modded is a modification of your sky build, I saw that you moved the characters and scenarios to the shared folder, because of your build, it is now easier to modify the game

**Comment by Rs232k** [comment]
It's build not from him.

**Comment by hrulol** [comment]
> FNF' Modded: https://drive.google.com/file/d/1W3iGtwp9btMyJrpj48iff9s3sAM364Y0/view?usp=drivesdk
> 
> Changes:
> 
> * The characters and scenarios are now in the shared folder (now you can use senpai on week 3 to play Spookeez);
> * Boyfriend now can be Blue Balled (Thanks to FNF' MOBILE Discord Server)
> * The songs have the recharts of the week 7 update;
> * The Parents now appears (They are tiny);
> * You can select Downscroll and immortality in the options;
> * Sky Icons.
> 
> Added:
> 
> * Sky mod included but pls, read the warning;
> * Week 7 Songs (Only Freeplay) (No Tankman, Pico on the Speaker and BF Holding GF);
> * Test Song With Vocals and the original Chart (Tutorial on Easy).
> 
> Note: You can't leave Story mode, you need to return to menu in the pause.
> 
> ![Screenshot_20210429-200621](https://user-images.githubusercontent.com/58278276/116629495-c3e02f00-a927-11eb-9f56-ac9516e4db2d.png)
> ![Screenshot_20210429-200547](https://user-images.githubusercontent.com/58278276/116629498-c5115c00-a927-11eb-958a-fa0a9d0e58a8.png)
> ![Screenshot_20210429-200452](https://user-images.githubusercontent.com/58278276/116629499-c5a9f280-a927-11eb-9e41-69f306a37db5.png)
> 
> Thanks to FridayNightSans
> 
> FNF' Modpack (FNF' MOBILE Discord Server Demo 3.0): https://drive.google.com/file/d/1LIy50N58efnIw7HL1aC4TzhO_sVFSKLj/view?usp=drivesdk
> 
> Added:
> 
> * Tricky (No Lite);
> * Foolhardy;
> * Whitty;
> 
> Warning: B-sides, Neo, Miku, Matt and Sky are not working.
> 
> * Test Song (No chart and no Vocals, sorry:/);
> * Downscroll (Note: The Health bar is always on the top.);
> * New input (Note: doesn't change anything)
> 
> Warning: The gameplay of the game is very unstable, the mod only accepts sick hits.
> 
> * Health, Misses and Max Combo now appears (Note: Your life is doubled)
> 
> Changed:
> App Icon;
> Sky Health Icons;
> Ballistic Whitty is now low quality 🤟😝.
> 
> ![Screenshot_20210429-201502](https://user-images.githubusercontent.com/58278276/116629526-d2c6e180-a927-11eb-870a-d1569469ff9d.png)
> ![Screenshot_20210429-201229](https://user-images.githubusercontent.com/58278276/116629531-d3f80e80-a927-11eb-9f86-0add86478b07.png)
> ![Screenshot_20210429-200828](https://user-images.githubusercontent.com/58278276/116629534-d490a500-a927-11eb-9a1e-5478bd93201f.png)
> ![Screenshot_20210429-200735](https://user-images.githubusercontent.com/58278276/116629536-d5c1d200-a927-11eb-898d-c25e114f47c1.png)
> ![Screenshot_20210429-200718](https://user-images.githubusercontent.com/58278276/116629538-d65a6880-a927-11eb-9127-2f2e67b7b6fc.png)
> ![Screenshot_20210429-200704](https://user-images.githubusercontent.com/58278276/116629542-d78b9580-a927-11eb-82f2-c7543977fc08.png)
> 
> Friday Night Funkin' MOBILE Discord Server: https://discord.gg/RhxQ8Y8y

it doesnt download for me since its google drive it doesnt notify nor DOWNLOAD it

**Comment by DanisLixo** [comment]
guys, stop reply my comment, im seeing the same screenshots a million times

**Comment by VRtoyboi** [comment]
POV: they're trying to find the link to the fnf mobile Discord server

**Comment by LarryFrosty** [comment]
> POV: you are trying to find the link to the fnf mobile Discord server

You finally find link but you realize it's not an english speaking server

**Comment by DanisLixo** [comment]
> > POV: you are trying to find the link to the fnf mobile Discord server
> 
> You finally find link but you realize it's not an english speaking server

POV: 😔
