### ISSUE TITLE
crazy gf on android without bugs

### ISSUE THREAD

**Issue by stormpancake999** [luckydog7/Funkin-android#558]
Hi, I'm storm, I just want to make a crazy gf mod, good, but how would I do it? I don't want to sacrifice mods, I don't know if someone can put a code to add extra characters

**Comment by FridayNightVibin** [comment]
How to open an issue

**Comment by stormpancake999** [comment]
> Cómo abrir un problema

you know how I can add extra characters to have that mod :v

**Comment by FridayNightVibin** [comment]
Ask FridayNightSans

**Comment by FridayNightVibin** [comment]
Not me

**Comment by stormpancake999** [comment]
> Yo no

Forgotten, I already have a port, thank you

**Comment by FridayNightVibin** [comment]
Ok
