### ISSUE TITLE
More control schemes?

### ISSUE THREAD

**Issue by AriIsADumb** [luckydog7/Funkin-android#56]
The port works pretty well aside from the random crashes, but the controls are pretty difficult to use well

Keyboard controls have been added already, but if possible could you add:
-Controller Support (Bluetooth+USB)
-Controls on both sides so it's easier to hit more complex note patterns

**Comment by Pixelneery** [comment]
CUSTOM CONTROLS AVAILABLE

**Comment by AriIsADumb** [comment]
> CUSTOM CONTROLS AVAILABLE

You can remap the 4 arrows to where you want, but I want the option to have two buttons for each arrow so i could do faster note sections more easily

In addition to that, while keyboard controls are available in that menu while controller controls aren't to my knowledge

**Comment by DanisLixo** [comment]
@AriIsADumb  you can close your issue now.
