### ISSUE TITLE
Yooo big thanks to Xxpert0 to make this mods its week 7 but play it at week 3

### ISSUE THREAD

**Issue by Darksider0912** [luckydog7/Funkin-android#567]
Made by Xxpert0
https://www.mediafire.com/file/6oirj6jkjkfydg4/Week+7+By+xXpert0.apk/file
Thank me later😏

**Comment by DanisLixo** [comment]
bruh, newgrounds is back already

**Comment by LemonGrass5** [comment]
Can You Send Screenshots?

**Comment by DanisLixo** [comment]
> Can You Send Screenshots?

sure
![Screenshot_20210501-004727](https://user-images.githubusercontent.com/58278276/116770226-434d2b80-aa18-11eb-9847-e18aea5bb692.png)



















just kidding

**Comment by FridayNightSans** [comment]
UGH! IM SICKING WITH THESE PORT REPLACE WEEK! IM ONLY LOVE PLAY IT AS BONUS WEEK! AND PLS STOP POSTING ANY ISSUE ABOUT WEEK 7 AND WAIT! >:(

**Comment by FridayNightSans** [comment]
> Made by Xxpert0
> https://www.mediafire.com/file/6oirj6jkjkfydg4/Week+7+By+xXpert0.apk/file
> Thank me later😏

Shit apk

**Comment by Kaique62** [comment]
> Made by Xxpert0
> https://www.mediafire.com/file/6oirj6jkjkfydg4/Week+7+By+xXpert0.apk/file
> Thank me later😏

Maybe I can port it to a new week
