### ISSUE TITLE
Secret about fridaynightsans/special sky mod

### ISSUE THREAD

**Issue by MarkyTheBarky** [luckydog7/Funkin-android#581]
The sky mod mobile friday night sans made has week 7
And he is telling people to stop asking when he doesn't know how it feels like to not be able to play week 7 and only him?
![Screenshot_20210501-120105_APK Editor](https://user-images.githubusercontent.com/81195152/116780657-fa2bc480-aa75-11eb-96bb-b26765f171d9.jpg)
![Screenshot_20210501-120045_APK Editor](https://user-images.githubusercontent.com/81195152/116780658-fac45b00-aa75-11eb-81d2-201d20f47f14.jpg)
![Screenshot_20210501-120029_APK Editor](https://user-images.githubusercontent.com/81195152/116780659-fb5cf180-aa75-11eb-801a-0922e1b5a1fd.jpg)
![Screenshot_20210501-120142_APK Editor](https://user-images.githubusercontent.com/81195152/116780661-fb5cf180-aa75-11eb-8dcf-2f792b9ac839.jpg)
![Screenshot_20210501-120206_APK Editor](https://user-images.githubusercontent.com/81195152/116780662-fbf58800-aa75-11eb-960a-a4a020e84491.jpg)

**Comment by MarkyTheBarky** [comment]
This post is related to #579

**Comment by ROBIKALIVE13** [comment]
are u that type of people that cant wait for week 7?
i think that u are

**Comment by MrTks216** [comment]
> are u that type of people that cant wait for week 7?
> i think that u are

Yeah, same

**Comment by MarkyTheBarky** [comment]
No, I can wait it's just I wanted to clear it out.

**Comment by FridayNightSans** [comment]
> This post is related to #579

I didnt said that by me? Im just sharing it from telegram.
Bruh
And special that im porting week 7 but pico is singing at week 3 lol. Btw, i dont have any computer to mod week 7 in ✌️

**Comment by MarkyTheBarky** [comment]
> > This post is related to #579
> 
> I didnt said that by me? Im just sharing it from telegram.
> Bruh
> And special that im porting week 7 but pico is singing at week 3 lol. Btw, i dont have any computer to mod week 7 in ✌️

I know, that's why I closed this post... My bad, sorry!

**Comment by FridayNightSans** [comment]
> > > This post is related to #579
> > 
> > 
> > I didnt said that by me? Im just sharing it from telegram.
> > Bruh
> > And special that im porting week 7 but pico is singing at week 3 lol. Btw, i dont have any computer to mod week 7 in ✌️
> 
> I know, that's why I closed this post... My bad, sorry!

Its okay tho, im not angry about this. And hey! Me,Neon (myfriend), and iPrime (u know thiz guys right?) Is makin Mega Remixes :v still in process but we will probally will out when iPrime got 450 subs

**Comment by MarkyTheBarky** [comment]
> > > > This post is related to #579
> > > 
> > > 
> > > I didnt said that by me? Im just sharing it from telegram.
> > > Bruh
> > > And special that im porting week 7 but pico is singing at week 3 lol. Btw, i dont have any computer to mod week 7 in ✌️
> > 
> > 
> > I know, that's why I closed this post... My bad, sorry!
> 
> Its okay tho, im not angry about this. And hey! Me,Neon (myfriend), and iPrime (u know thiz guys right?) Is makin Mega Remixes :v still in process but we will probally will out when iPrime got 450 subs

Oh, that's cool!!!! Do u got discord? I can help him reach 450 subs! I can post about his channel in my community post. But I need to know his channel link

**Comment by FridayNightSans** [comment]
No, i cant cause this is still secret. So i cant do anything lol ;-;

**Comment by FridayNightSans** [comment]
Oh wait nvm, here
https://youtube.com/channel/UCpWyByigLOl3Cnzux157CHw

**Comment by cratorjadbruh** [comment]
Uhhhhhhh

**Comment by DanisLixo** [comment]
but you can play the songs #557
