### ISSUE TITLE
need help building

### ISSUE THREAD

**Issue by whiteninja1** [luckydog7/Funkin-android#583]
i dont quite understand what "open project in command line" does it mean to copy the directory or to open a file

**Comment by Kaique62** [comment]
> i dont quite understand what "open project in command line" does it mean to copy the directory or to open a file

Do u want to use the command like test android?

**Comment by whiteninja1** [comment]
yeah about that i didnt know how to export normal fnf i didnt have anything installed but now i do i was just a dumbass
