### ISSUE TITLE
how to add more weeks on fnf mobile like bonus week

### ISSUE THREAD

**Issue by King-Fox-Yt** [luckydog7/Funkin-android#607]
help

**Comment by Ruv023** [comment]
Why are you posting the exact same thing?

**Comment by ROBIKALIVE13** [comment]
> Why are you posting the exact same thing?

bc he doesn't care about what i said i said ONLY PC

**Comment by King-Fox-Yt** [comment]
idc peppy did it 
but idk how

**Comment by ROBIKALIVE13** [comment]
U NEED A COMPUTER

**Comment by ROBIKALIVE13** [comment]
HE DID IT WITH A COMPUTER

**Comment by King-Fox-Yt** [comment]
![496ed30683b06b49c6e0e07fb61bb757](https://user-images.githubusercontent.com/83482176/116828526-31de5d80-ab97-11eb-9d8e-db2ca1c482dc.jpg)

**Comment by MarkyTheBarky** [comment]
OH MY FUCKING GOD, PEPPY DID IT ON A COMPUTER GOD DAMNIT. CANT BELIEVE U 5 YEAR OLD BRATS ARE GOING AROUND ASKING PEOPLE DUMB QUESTIONS. FUCK OFF AND GO CRY TO UR MOM ABOUT IT
