### ISSUE TITLE
Can someone port this mod?

### ISSUE THREAD

**Issue by REAL-DoritosMAN** [luckydog7/Funkin-android#611]
The link is https://gamebanana.com/skins/187658
I don't have a computer so I can't port it myself

**Comment by LuizBarata** [comment]
Use APK Editor Pro, Dowload The Mod And Change The GF Files EZ

**Comment by REAL-DoritosMAN** [comment]
What editor do you use?

**Comment by King-Fox-Yt** [comment]
> What editor do you use?

use apk editor pro or normal apk editor
I can do it for u

**Comment by LuizBarata** [comment]
APK editor Pro lol

**Comment by King-Fox-Yt** [comment]
it will ready as easy

**Comment by King-Fox-Yt** [comment]
I need to test and everyone

**Comment by King-Fox-Yt** [comment]
everything

**Comment by King-Fox-Yt** [comment]
first I need to test it and upload it to download web

**Comment by King-Fox-Yt** [comment]
apk editor is now on chaos

**Comment by King-Fox-Yt** [comment]
I will do it later I did some mistakes and I can get your discord

**Comment by REAL-DoritosMAN** [comment]
Mine?
