### ISSUE TITLE
Funkin' at half native resolution?

### ISSUE THREAD

**Issue by 8ballfall** [luckydog7/Funkin-android#613]
FNF' Android plays at an unplayable framerate no matter what menu or week on my cheapo Tab E 9.6, so I'd like it greatly if you had the option to play at half of a given devices native resolution.

I know about the FNF' Lite stuff, but I'm not looking to play the game with microscopic characters heh :l

I'm gonna upgrade to a Tab S5e in the coming months which I'm sure will absolutely smash this game, but I'd still appreciate it if your awesome work was accessible to more people :)

(Oh yeah also this is the first time I'm doing litterally anything on Github so let me know if I sound real sappy and time wasting, or something.)

**Comment by 8ballfall** [comment]
Also not sure if this information helps, but the latest version removes all black boxes as described (on my device at least), so I know it's not the size of the sprites but rather the resolution of the entire game.

**Comment by Ralphy999** [comment]
> Also not sure if this information helps, but the latest version removes all black boxes as described (on my device at least), so I know it's not the size of the sprites but rather the resolution of the entire game.

It is the resolution

**Comment by 8ballfall** [comment]
Resolution of what? The sprites? The rendering resolution??
