### ISSUE TITLE
Friday night funkin HD mod (Tutorial, week 1-3) with k-dev (Delete)

### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#617]
Before that, i didn't make this mod, just showcase.
No cut screen, no dialogue, only just skin and background change (except week 1 background)

Preview:
![Screenshot_2021-05-03-16-23-18-808_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/116861870-6fde8e80-ac36-11eb-9f95-3cab0f748589.jpg)
![Screenshot_2021-05-03-16-28-00-472_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/116861924-81279b00-ac36-11eb-852d-3a1fb9a696b3.jpg)
[Tutorial] new version(will crash) old version (fix)
![Screenshot_2021-05-03-16-23-58-147_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/116861953-9270a780-ac36-11eb-9bd1-c19fe7547b90.jpg)
[Week 1]
![Screenshot_2021-05-03-16-24-47-938_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/116861984-9dc3d300-ac36-11eb-9c42-1e07f4853151.jpg)
[Week 2]
![Screenshot_2021-05-03-16-25-38-051_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/116862029-b207d000-ac36-11eb-858d-55edfd84a535.jpg)
Monster
![Screenshot_2021-05-03-16-26-27-320_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/116862054-c055ec00-ac36-11eb-9c94-1461d28af50f.jpg)
(If you look closely to monster, you will find something interesting)
[Week3]
![Screenshot_2021-05-03-16-27-08-065_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/116862229-03b05a80-ac37-11eb-8432-c4e51ad3bce6.jpg)

Download link
(Delete)

Hd mod:
https://gamebanana.com/mods/166446

That all, have a nice day :-)

**Comment by ROBIKALIVE13** [comment]
girlfriend doesn't want to teach me how to play xd

**Comment by MrTks216** [comment]
> girlfriend doesn't want to teach me how to play xd

Lol xd

**Comment by FridayNightVibin** [comment]
Bruh it lags

**Comment by FridayNightVibin** [comment]
Wow week seven and tricky

**Comment by MrTks216** [comment]
> Bruh it lags 

Yeah, need better ram phone to run it smoothly

**Comment by MrTks216** [comment]
and forgot tell your guys, the tutorial can't not play, it will crash. I use different versions of k-dev 
of fnf

**Comment by MrTks216** [comment]
if you want to play tutorial, i will upload old ver fnf of this mod, that tutorial can play, it won't crash, but no week 7 and tricky.

**Comment by hrulol** [comment]
lite? 👉👈

**Comment by MrTks216** [comment]
> lite? 👉👈

sorry, can't do it.

**Comment by MrTks216** [comment]
Update old ver k-dev of this mod (No week 7 and tricky, can play tutorial):
https://mega.nz/file/M4RURZAJ#si0-KB7m8PqXt3PpXiJNOzbZGF3dHBoGIJxeORKF9Ew

**Comment by ROBIKALIVE13** [comment]
> if you want to play tutorial, i will upload old ver fnf of this mod, that tutorial can play, it won't crash, but no week 7 and tricky.
> 

so thats why girlfriend doesn't want to teach me. she think its a better idea to yeet the player out of the game. understand

**Comment by MrTks216** [comment]
> > if you want to play tutorial, i will upload old ver fnf of this mod, that tutorial can play, it won't crash, but no week 7 and tricky.
> > 
> 
> so thats why girlfriend doesn't want to teach me. she think its a better idea to yeet the player out of the game. understand

Yeah, sorry about that.

**Comment by ROBIKALIVE13** [comment]
> > > if you want to play tutorial, i will upload old ver fnf of this mod, that tutorial can play, it won't crash, but no week 7 and tricky.
> > > 
> > 
> > so thats why girlfriend doesn't want to teach me. she think its a better idea to yeet the player out of the game. understand
> 
> Yeah, sorry about that.

no its not your fault. its girlfriend fault xd

**Comment by MrTks216** [comment]
> > > > if you want to play tutorial, i will upload old ver fnf of this mod, that tutorial can play, it won't crash, but no week 7 and tricky.
> > > > 
> > > 
> > > so thats why girlfriend doesn't want to teach me. she think its a better idea to yeet the player out of the game. understand
> > 
> > Yeah, sorry about that.
> 
> no its not your fault. its girlfriend fault xd

Lol XD, gonna sleep now, gn.

**Comment by ROBIKALIVE13** [comment]
> > > > > if you want to play tutorial, i will upload old ver fnf of this mod, that tutorial can play, it won't crash, but no week 7 and tricky.
> > > > > 
> > > > 
> > > > so thats why girlfriend doesn't want to teach me. she think its a better idea to yeet the player out of the game. understand
> > > 
> > > Yeah, sorry about that.
> > 
> > no its not your fault. its girlfriend fault xd
> 
> Lol XD, gonna sleep now, gn.

gn

**Comment by MistyFisty** [comment]
im fucking porting this shit so there can be dialoges and then the arrow that pico shoots at you
