### ISSUE TITLE
Can someone port this mod?

### ISSUE THREAD

**Issue by DabKnight** [luckydog7/Funkin-android#618]
I know it's gonna be impossible but just try and make it like the bopeebo rumble port with no effects.
Anyways here is the mod i wanna try:
https://gamebanana.com/mods/download/56040

**Comment by FridayNightVibin** [comment]
What the frick

**Comment by MrTks216** [comment]
> I know it's gonna be impossible but just try and make it like the bopeebo rumble port with no effects.
> Anyways here is the mod i wanna try:
> https://gamebanana.com/mods/download/56040

i know how to port the song, effects need pc to coding.

**Comment by MrTks216** [comment]
you can just replace json and the song, you can play it

**Comment by DabKnight** [comment]
> you can just replace json and the song on tutorial, then you can play it without effects

Ay it worked.
Thanks :D
