### ISSUE TITLE
More help

### ISSUE THREAD

**Issue by pressenterreal** [luckydog7/Funkin-android#62]
Sorry but I need some more help. Where are the input button spritesheets located in release 712? (I mean in the code files, I can see them in-game perfectly fine) @luckydog7

**Comment by DanisLixo** [comment]
eai presente real, precisa de mais ajuda kkkk

**Comment by pressenterreal** [comment]
sim, preciso de mais ajuda, se você puder me dar alguma. (eu tive que traduzir isso)

**Comment by DanisLixo** [comment]
hm, ok. Well, the Input Controls sprites it’s not in the game’s files, it’s just in the source code. so unless you edit by source code, I think it is not possible.

**Comment by pressenterreal** [comment]
I'm just gonna close this for now, as I am making something else since the idea is out the door.
