### ISSUE TITLE
Can someone port the Boy girlfriend mod to mobile?

### ISSUE THREAD

**Issue by REAL-DoritosMAN** [luckydog7/Funkin-android#628]
https://gamebanana.com/skins/187658

I would port it myself if i had a pc

**Comment by ROBIKALIVE13** [comment]
u just need to replace the gf assets

**Comment by GamesGobrrrr** [comment]
Just follow this tutorial https://youtu.be/TTfhZTZQ-9U

**Comment by briannewmc22a** [comment]
To make custom weeks need pc but if is just a skin then you can just put it using android without pc watch a tutorial

**Comment by REAL-DoritosMAN** [comment]
> u just need to replace the gf assets

I did the shared tutorial and week 4 is unplayable
Did i mess something up? I put the car assets image and xml over the girlfriend assets and image
