### ISSUE TITLE
Can you make a compatible version of the game?

### ISSUE THREAD

**Issue by boiswe** [luckydog7/Funkin-android#64]
The game runs well and all but the game sometimes crashes I have to use my father's phone to play the game so I was wondering if you can make the game more playable for other low end devices

**Comment by matthew99729** [comment]
> The game runs well and all but the game sometimes crashes I have to use my father's phone to play the game so I was wondering if you can make the game more playable for other low end devices

It isn't a compatibility issue. The game has a memory issue because it doesn't take advantage of caching so it's constantly adding data to ram. This is a problem because it keeps adding data until android just has to shut down the game for excessive memory usage.
