### ISSUE TITLE
Fnf Smoke 'Em Out Struggle [Full Week] Vs Garcello (New) 

### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#650]
Just quick update, fix some characters spirit. New icon
More info #633
![Screenshot_2021-05-05-06-34-44-877_com.ninjamuffin6969.funkin.jpg](https://user-images.githubusercontent.com/81964285/117080818-30688d00-ad71-11eb-8e2d-6dabe2755888.jpg)
![Screenshot_2021-05-05-06-34-18-566_com.ninjamuffin6969.funkin.jpg](https://user-images.githubusercontent.com/81964285/117080835-378f9b00-ad71-11eb-94b4-3def6a2d332a.jpg)

Download link
Mediafire:
https://www.mediafire.com/file/e1fqdkwkihxvcnd/Fnf_Smoke_%2527Em_Out_Struggle_%255BFull_Week%255D_Vs_Garcello.apk/file
Mega:
https://mega.nz/file/kphwELqS#tS3tEyZ8HgMt6IaPc1Z9rUbakReDqrpHzodQDk4XQjk
Google Drive:
https://drive.google.com/file/d/1--yuKYNcmmoyM8uY-VnZeh5vWsJSlGTP/view?usp=drivesdk

Smoke 'Em Out Struggle [Release Remix Chart]
Mediafire
https://www.mediafire.com/folder/xm7enx5f15kmi/Smoke+'Em+Out+Struggle+[Release+Remix+Chart]
Just replace the file, then you can play remix song. Only this version work.
Mod:
https://gamebanana.com/mods/284053

One more thing, rip Garcello 😢 
That it, peace out ✌

**Comment by RedstoneGuyLol** [comment]
Pretty good!

**Comment by MrTks216** [comment]
i wonder you guys want me upload on Google Drive, yes or no?

**Comment by Qusaithedemon** [comment]
do it to google drive

**Comment by FridayNightVibin** [comment]
The mod its so sad

**Comment by FridayNightVibin** [comment]
I mean the story is sad

**Comment by FridayNightVibin** [comment]
Bruh he fricking dies and fades away as a ghost

**Comment by hrulol** [comment]
> Bruh he fricking dies and fades away as a ghost

have u never seen the mod yet buddy?

**Comment by hrulol** [comment]
anyways i KNEW this would happen when i got into issues. good job though

**Comment by Danydave20** [comment]
Hey bro can you do an optimized version of this if you can't then it's ok

**Comment by MrTks216** [comment]
> Hey bro can you do an optimized version of this if you can't then it's ok

sorry, i can't do it. Hope someone do the optimized version of this mod

**Comment by derrickthednflover** [comment]
Why does it crash

**Comment by MrTks216** [comment]
> Why does it crash

nah, mine was fine, it your phone can't not handle it, need more ram to run it.

**Comment by MrTks216** [comment]
Someone if you interested here
Smoke 'Em Out Struggle [Release Remix Chart]
https://www.mediafire.com/folder/xm7enx5f15kmi/Smoke+'Em+Out+Struggle+[Release+Remix+Chart]
Just replace the file and done, you can play the remix song.

**Comment by joe-mamad** [comment]
It replaces all characters with garcello
