### ISSUE TITLE
Uh where do you put the sorce code

### ISSUE THREAD

**Issue by boiswe** [luckydog7/Funkin-android#652]
I don't know anything bout mods so I need to know where to put the source code cuz I have black boxes

**Comment by DanisLixo** [comment]
the source code doesn't do anything, You've been TROLLED YOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by ActiveClosure** [comment]
> the source code doesn't do anything, You've been TROLLED YOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

It does, have you got any experience with coding?

**Comment by boiswe** [comment]
Kinda

**Comment by boiswe** [comment]
But the reason I'm asking for it is coz it's missing a lot of the animations and sprits

**Comment by DanisLixo** [comment]
> But the reason I'm asking for it is coz it's missing a lot of the animations and sprits

which animations?

**Comment by boiswe** [comment]
Nvm i figured it out

**Comment by boiswe** [comment]
It took a while
