### ISSUE TITLE
MOD PACK

### ISSUE THREAD

**Issue by rmme1hack** [luckydog7/Funkin-android#674]
This is a mod that have tricky zardy and whitty in one game. The bad thing is that neo and b-side doesent work 

 Drive link 
https://drive.google.com/file/d/1crNKQVT7wYge-HBts0RVXAqN2l_0nrpN/view?usp=drivesdk

Srry for not giving credits beafore, I was in big stress trying to find the mod.
Credits by fnf-mobile

For porting the mod

**Comment by stormpancake999** [comment]
Bruh

**Comment by unchavon** [comment]
hey,little shit, at least give credit to fnf mobile, they tried hard and you what? just re-uploading the link without credits or anything, right? what a shame you are

**Comment by FourlyDumb** [comment]
Give credits bruh

**Comment by unchavon** [comment]
WTH bro the credits are FNF MOBILE Not that QUADS CHANNEL

**Comment by hrulol** [comment]
#557 bruh someone already made it.

**Comment by stormpancake999** [comment]
better plan to make your description once to the next
