### ISSUE TITLE
Friday night funkin' Vs Kiryu

### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#681]
Before that, i don't make this mod, just port this mod into Android. This version mod will not same as pc version.
The port i use K-dev demo 2.5:
https://youtu.be/VeeuNJrA-0Q

No dialogue, No ending cutscreen
Week 1 (3 song) + Tutorial (1 extra song add by me)
Tutorial = Baka Mitai
Bopeebo = Machine-gun-kiss
Fresh = Like-a-butterfly
Dadbattle = Discernment
Preview:
![Screenshot_2021-05-07-13-45-36-453_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/117406309-78d5a580-af3f-11eb-8468-80b93c2ef7a8.jpg)
![Screenshot_2021-05-07-13-45-45-353_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/117406338-7ffcb380-af3f-11eb-825a-9fe760b09c0e.jpg)
[Week 極]
![Screenshot_2021-05-07-13-45-58-525_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/117406498-b89c8d00-af3f-11eb-8e46-2c693803b1eb.jpg)
[Kiryu]
![Screenshot_2021-05-07-13-46-14-929_com.ninjamuffin99.funkin.jpg](https://user-images.githubusercontent.com/81964285/117406532-c9e59980-af3f-11eb-8ca2-d96ef1409f45.jpg)

Here the link
Mediafire:
https://www.mediafire.com/file/5aakox7b42iarqy/Friday_night_funkin%2527_Vs_Kiryu.apk/file
Mega:
https://mega.nz/file/NtJFwCAI#9RTYeROa2bG99hZ7AR-8X-Qj7uJfXrMjqHvRKJ9WARs

Vs Kiryu mod
https://gamebanana.com/mods/249504
Baka Mitai mod
https://gamebanana.com/mods/44827

Dame da ne. Dame yo dame na no yo

**Comment by DabKnight** [comment]
WAIT THIS IS A MOD ALREADY?!
I didnt know :0

**Comment by MrTks216** [comment]
> WAIT THIS IS A MOD ALREADY?!
> I didnt know :0

Just came out today lol

**Comment by DabKnight** [comment]
> > WAIT THIS IS A MOD ALREADY?!
> > I didnt know :0
> 
> Just came out today lol

Wow people are so fast lmao

**Comment by moonrocklullaby** [comment]
nice  port dude! just ask next time the devs that is, to do soemthin like this, otherwise, this is a pretty solid port nevertheless
