### ISSUE TITLE
help with building

### ISSUE THREAD

**Issue by jonjonhtml** [luckydog7/Funkin-android#70]
hey i copile it using the source code but there's one erorr when i open the app
![error 2](https://user-images.githubusercontent.com/69421944/111125691-922f2680-857a-11eb-8b79-39b3252de049.jpg)
![error 1](https://user-images.githubusercontent.com/69421944/111125694-93605380-857a-11eb-9677-9060ef1d87f3.jpg)

**Comment by jonjonhtml** [comment]
thx for help

**Comment by Rs232k** [comment]
App from here is works?

**Comment by pearlbits6455** [comment]
I never saw that

**Comment by jonjonhtml** [comment]
Yup but i need using the source i didn't change it yet this try was in the original one i think its because i have to copy some lib folder to c:/haxetoolkit but i didn't understood which lib folder

**Comment by Rs232k** [comment]
> Yup but i need using the source i didn't change it yet this try was in the original one i think its because i have to copy some lib folder to c:/haxetoolkit but i didn't understood which lib folder

Go to haxe installed location, and paste it.
You can backup lib/flixel/4.8.1

**Comment by jonjonhtml** [comment]
Paste what?

**Comment by Rs232k** [comment]
> Paste what?

https://github.com/luckydog7/Funkin-android/tree/master/OPENME!

**Comment by jonjonhtml** [comment]
Thx i am not closing it yet because i will try it only tomorrow at 13:00

**Comment by jonjonhtml** [comment]
i am so dumb thx
