### ISSUE TITLE
Working SKINS

### ISSUE THREAD

**Issue by SadiqJack3** [luckydog7/Funkin-android#709]
Ello I found some working skin i only found one ;-; so i try my best to gind working skins

**Comment by SadiqJack3** [comment]
![Uploading OYFRIEND.png…]()

**Comment by SadiqJack3** [comment]
Boring upload wait the upload or join discord to download fastest https://discord.gg/cqQmauxd

**Comment by ROBIKALIVE13** [comment]
sadiq ehy did u put dangerous role on me? xd

**Comment by ROBIKALIVE13** [comment]
i have been yeeted out of the server

**Comment by ROBIKALIVE13** [comment]
> Boring upload wait the upload or join discord to download fastest i accidentally deleted my server

congrats xd

**Comment by ROBIKALIVE13** [comment]
> Boring upload wait the upload or join discord to download fastest i accidentally deleted my server

will u make another?

**Comment by SadiqJack3** [comment]
From now this is closed

**Comment by SadiqJack3** [comment]
wow welcome back here again for begging working skins LOL!

Join discord server again for skins https://discord.gg/BXKUhuWS

**Comment by SadiqJack3** [comment]
i had enough

**Comment by SadiqJack3** [comment]
adios closes
