### ISSUE TITLE
Subscribe to georgechen1296

### ISSUE THREAD

**Issue by georgechen1236** [luckydog7/Funkin-android#711]
Subscribe Here link: https://m.youtube.com/channel/UCH9N4SNzwE2XineTLwhDccA

**Comment by FridayNightSans** [comment]
> Subscribe Here link: https://m.youtube.com/channel/UCH9N4SNzwE2XineTLwhDccA

Stop bruh, this is a place for sharing mod, report bug and more. Not the place for Sharing YouTube. Bruh

**Comment by BoyfriendFNF** [comment]
> Subscribe Here link: https://m.youtube.com/channel/UCH9N4SNzwE2XineTLwhDccA

no

**Comment by whenthesussy** [comment]
> Subscribe Here link: https://m.youtube.com/channel/UCH9N4SNzwE2XineTLwhDccA

NO

**Comment by steaklake** [comment]
Bruh moment

**Comment by georgechen1236** [comment]
> Bruh moment

Bruh moment

**Comment by helpmeplsokw** [comment]
> > Bruh moment
> 
> Bruh moment

No u

**Comment by ROBIKALIVE13** [comment]
EFFIN DAMNIT THIS PLACE NOT FOR SHARING YOUTUBE CHANNEL ITS FOR MODS,BUG REPORT AND MORE

**Comment by ROBIKALIVE13** [comment]
> Aight because you used the issues wrong,im not subscribing to your channel.

thank god that ur not that stupid

**Comment by DabKnight** [comment]
> > Aight because you used the issues wrong,im not subscribing to your channel.
> 
> thank god that ur not that stupid

Thank you.
Because what kind of idiot would just advertise their channel?!

**Comment by georgechen1236** [comment]
> Aight because you used the issues wrong,im not subscribing to your channel.

FUCK you everyone

**Comment by ROBIKALIVE13** [comment]
> > Aight because you used the issues wrong,im not subscribing to your channel.
> 
> FUCK you everyone 

Toxic folk

**Comment by MarkyTheBarky** [comment]
> > Aight because you used the issues wrong,im not subscribing to your channel.
> 
> FUCK you everyone

Haha bitch better close this issue, now go cry to ur mama because nobody will never subscribe to ur channel ok

**Comment by georgechen1236** [comment]
> > > Aight because you used the issues wrong,im not subscribing to your channel.
> > 
> > 
> > FUCK you everyone
> 
> Haha bitch better close this issue, now go cry to ur mama because nobody will never subscribe to ur channel ok

FUCK you man FUCKing shit

**Comment by FridayNightSans** [comment]
> > Aight because you used the issues wrong,im not subscribing to your channel.
> 
> FUCK you everyone

REPORT TIME

**Comment by georgechen1236** [comment]
> > > Aight because you used the issues wrong,im not subscribing to your channel.
> > 
> > 
> > FUCK you everyone
> 
> REPORT TIME

What do you one report me

**Comment by RoadRings** [comment]
lmao

**Comment by GamesGobrrrr** [comment]
One word, Simple context

N O

**Comment by NeonNotFound** [comment]
The most dumb person spotted

**Comment by MrTks216** [comment]
Bruh, You guys still keep going lol.

**Comment by NeonNotFound** [comment]
> Bruh, You guys still keep talking in here lol.

Yeah lmao

**Comment by DabKnight** [comment]
Bruh moment.

**Comment by georgechen1236** [comment]
Stop click my channel
