### ISSUE TITLE
Fnf Vs Tord (Remastered) 

### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#714]
Before that, i don't make this mod, just port mod into android and this mod will not same as pc version
The port that i use fnf android lite sky mod
https://mega.nz/file/l4Ay1bxK#KNKHnqGrU-KvU_NXAFn8zpHaaNgjnNjQaPdofmWze14
Replace week 1
Two new song 
Bopeebo = Norway
Fresh = Tordbot

Preview
![Screenshot_2021-05-09-14-32-39-153_com.ninjamuffin99.funkin.mod.sky.jpg](https://user-images.githubusercontent.com/81964285/117566698-c5111900-b0ea-11eb-9b1f-1098b9432992.jpg)
![Screenshot_2021-05-09-14-32-50-566_com.ninjamuffin99.funkin.mod.sky.jpg](https://user-images.githubusercontent.com/81964285/117566702-cd695400-b0ea-11eb-9912-a64112f241ab.jpg)
![Screenshot_2021-05-09-14-33-13-518_com.ninjamuffin99.funkin.mod.sky.jpg](https://user-images.githubusercontent.com/81964285/117566770-36e96280-b0eb-11eb-833d-189ddc3debc0.jpg)
[Tord]
![Screenshot_2021-05-09-17-15-32-737_com.ninjamuffin99.funkin.mod.tord.jpg](https://user-images.githubusercontent.com/81964285/117566792-4a94c900-b0eb-11eb-97cc-30ee468f8ab1.jpg)
[Mini size tordbot] 
![Screenshot_2021-05-09-17-16-13-341_com.ninjamuffin99.funkin.mod.tord.jpg](https://user-images.githubusercontent.com/81964285/117566825-7a43d100-b0eb-11eb-82fd-c464e62330f7.jpg)
Yes, it was mini size tordbot, i try make the spirit more smaller than the original, if i don't do that, it will become like this:
![Screenshot_2021-05-09-12-52-49-922_com.ninjamuffin99.funkin.mod.sky.jpg](https://user-images.githubusercontent.com/81964285/117566943-2685b780-b0ec-11eb-9187-637b197e2b0b.jpg)

Download link
Mediafire:
https://www.mediafire.com/file/ampxabroiyf83ak/FNF_Vs_Tord_%2528Remastered%2529.apk/file
Mega:
https://mega.nz/file/Ux4TGKIT#O3YEPTjkvRLSHlR0Vo1zbGnQPvujs0XyHAXoKDZgB5g
The mod:
https://gamebanana.com/mods/183165

That it, peace out✌

**Comment by hrulol** [comment]
BRUH THIS IS EPIK
