### ISSUE TITLE
💀🎃 XML and png

### ISSUE THREAD

**Issue by georgechen1236** [luckydog7/Funkin-android#717]

**Comment by DzGithub2805** [comment]
Skid and pump?

**Comment by georgechen1236** [comment]
> Skid and pump?

Yes

**Comment by DzGithub2805** [comment]
https://drive.google.com/file/d/1C-YlnjVAZpwIu5bzESIjrdQ2kLwMipJ1/view?usp=drivesdk

**Comment by DzGithub2805** [comment]
Updated link: https://drive.google.com/file/d/1C-YlnjVAZpwIu5bzESIjrdQ2kLwMipJ1/view?usp=drivesdk

**Comment by georgechen1236** [comment]
> Updated link: https://drive.google.com/file/d/1C-YlnjVAZpwIu5bzESIjrdQ2kLwMipJ1/view?usp=drivesdk

That original

**Comment by DzGithub2805** [comment]
So you want what?

**Comment by DzGithub2805** [comment]
a
