### ISSUE TITLE
Whitty B3 Remixed

### ISSUE THREAD

**Issue by DzGithub2805** [luckydog7/Funkin-android#719]
pls port it to android

here is a mod: https://gamebanana.com/mods/57755

PC screen shot
![Screenshot_20210510-111428_YouTube](https://user-images.githubusercontent.com/83911327/117605144-41eed200-b181-11eb-8683-f7891a122bfe.jpg)

**Comment by ROBIKALIVE13** [comment]
> pls port it to android
> 
> here is a mod: https://gamebanana.com/mods/57755
> 
> PC screen shot
> ![Screenshot_20210510-111428_YouTube](https://user-images.githubusercontent.com/83911327/117605144-41eed200-b181-11eb-8683-f7891a122bfe.jpg)
> 
> 

why would u ask for b3 whitty if u have a pc? 🤦
