### ISSUE TITLE
help I need a resize website

### ISSUE THREAD

**Issue by King-Fox-Yt** [luckydog7/Funkin-android#764]
for some reason I used bulk resize to resize my own boyfriend skin and for some reason it's so bugged out boyfriend is u underground and showing the dead screen on top of him here is a video here is a video when that happened https://youtu.be/6SimPfuUItY

**Comment by King-Fox-Yt** [comment]
I need fucking help

**Comment by DabKnight** [comment]
Try to edit the xml so that the correct graphics work.
Or just find one from a bunch of apks that is for the said png skin.

**Comment by DabKnight** [comment]
> Try to edit the xml so that it works right.
> Or just find one from a bunch of apks that is for the said png skin.

**Comment by King-Fox-Yt** [comment]
> > Try to edit the xml so that it works right.
> > Or just find one from a bunch of apks that is for the said png skin.

I learn how to xml lmao

**Comment by King-Fox-Yt** [comment]
time to cloae6

**Comment by kffwlp** [comment]
Is it possible to make the .xml files on Android?
