### ISSUE TITLE
FNF Vs. K.K. Slider

### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#772]
Before that, i don't make this mod, just port the mod into Fnf Android.This mod will not same as pc version.
The fnf port that i use fnf android lite sky mod
https://mega.nz/file/l4Ay1bxK#KNKHnqGrU-KvU_NXAFn8zpHaaNgjnNjQaPdofmWze14
New characters, K.K.Slider from animal crossing
Three New Original Song, New Background.
Replace week 5. (Still kinda buggy) 
Cocoa = K.K. Cruisin'
Eggnog = Bubblegum K.K.
Winter-Horrorland = K.K. Metal
Preview:
![Screenshot_2021-05-13-21-38-05-055_com.ninjamuffin99.funkin.mod.KKS.jpg](https://user-images.githubusercontent.com/81964285/118134983-14ca4a00-b435-11eb-8c5d-c2910370e756.jpg)
Week 🐾(Bug)
![Screenshot_2021-05-13-21-38-23-618_com.ninjamuffin99.funkin.mod.KKS.jpg](https://user-images.githubusercontent.com/81964285/118135188-4e02ba00-b435-11eb-9e3e-47176569c5a9.jpg)
K.K. Slider
![Screenshot_2021-05-13-21-38-41-702_com.ninjamuffin99.funkin.mod.KKS.jpg](https://user-images.githubusercontent.com/81964285/118135259-6377e400-b435-11eb-8a34-b320f9b5af83.jpg)

Download link
Mediafire:
https://www.mediafire.com/file/8hzmidgr6mdn6ky/FNF_Vs_K.K._Slider.apk/file
Mega:
https://mega.nz/file/Qw5EQBCT#-eX19CCQSjNtNSusHpcjw06DXJmhO4IzMXejpUsp-20
The mod:
https://gamebanana.com/mods/285101

That it, Tight Bars, Little Man

**Comment by FridayNightVibin** [comment]
Nice mod man

**Comment by FridayNightVibin** [comment]
What the funk why is the last song hard its like hex but more faster

**Comment by MrTks216** [comment]
> What the funk why is the last song hard its like hex but more faster

Yeah, the third song kinda hard, i already beat it lol

**Comment by ROBIKALIVE13** [comment]
> > What the funk why is the last song hard its like hex but more faster
> 
> Yeah, the third song kinda hard, but i already beat it lol

i almost died btw 1 miss and i failed it

**Comment by MrTks216** [comment]
> > > What the funk why is the last song hard its like hex but more faster
> > 
> > Yeah, the third song kinda hard, but i already beat it lol
> 
> i almost died btw 1 miss and i failed it

oof.
