### ISSUE TITLE
Week 7 apk

### ISSUE THREAD

**Issue by DzGithub2805** [luckydog7/Funkin-android#794]
Here is the apk: https://drive.google.com/file/d/1Dur8ASzwwG83GpIH4E8jqLgonYul8G3X/view?usp=drivesdk

Screenshot
![Screenshot_20210511-191723](https://user-images.githubusercontent.com/83911327/118353107-1e67c500-b58f-11eb-85c2-a0b9e280c3ff.jpg)
This is week 3

**Comment by LemonGrass5** [comment]
Add cutscenes

**Comment by DzGithub2805** [comment]
> Add cutscenes

ITS A WEEK 3 MOTHERFUCKA

**Comment by LemonGrass5** [comment]
> > Add cutscenes
> 
> ITS A WEEK 3 MOTHERFUCKA

Chill the fak out maa guy.

**Comment by FridayNightSans** [comment]
Wait week 3? Ok ima funk out
