### ISSUE TITLE
Vs AGUTI mod please

### ISSUE THREAD

**Issue by AngeleAkane** [luckydog7/Funkin-android#809]
Please :³

**Comment by georgechen1236** [comment]
No

**Comment by DzGithub2805** [comment]
#804

**Comment by LarryFrosty** [comment]
There's always that one guy that asks for every fucking mod to be ported when they see a new one

**Comment by AngeleAkane** [comment]
> There's always that one guy that asks for every fucking mod to be ported when they see a new one

sorry, i hadn't realized it, i had barely seen the mod ;-;
