### ISSUE TITLE
How do i add dialogue in fnf mobile

### ISSUE THREAD

**Issue by VitalieW0WKid** [luckydog7/Funkin-android#819]
I just wanna know what apps I need to use,how to I use,etc.
Sorry but i can't figure out how to put mods

**Comment by MarkyTheBarky** [comment]
> I just wanna know what apps I need to use,how to I use,etc.
> Sorry but i can't figure out how to put mods

U can only do it on pc, not mobile

**Comment by nattangomes** [comment]
> > I just wanna know what apps I need to use,how to I use,etc.
> > Sorry but i can't figure out how to put mods
> 
> U can only do it on pc, not mobile

i think it is possible on mobile
dont know how to code but i think its possible

**Comment by VitalieW0WKid** [comment]
> > I just wanna know what apps I need to use,how to I use,etc.
> > Sorry but i can't figure out how to put mods
> 
> U can only do it on pc, not mobile

The fnf mobile port hasn't almost the same engine and coding
So it is possible

**Comment by ppllo** [comment]
But how does play the source code

**Comment by ppllo** [comment]
But How i play the game
With source code

**Comment by ROBIKALIVE13** [comment]
> > > I just wanna know what apps I need to use,how to I use,etc.
> > > Sorry but i can't figure out how to put mods
> > 
> > U can only do it on pc, not mobile
> 
> The fnf mobile port hasn't almost the same engine and coding?
> So it is possible

u can just edit it for now

**Comment by VitalieW0WKid** [comment]
> > > > I just wanna know what apps I need to use,how to I use,etc.
> > > > Sorry but i can't figure out how to put mods
> > > 
> > > 
> > > U can only do it on pc, not mobile
> > 
> > 
> > The fnf mobile port hasn't almost the same engine and coding?
> > So it is possible
> 
> u can just edit it for now

Yea but where are the .hx files?

**Comment by Rs232k** [comment]
> > > > > I just wanna know what apps I need to use,how to I use,etc.
> > > > > Sorry but i can't figure out how to put mods
> > > > 
> > > > 
> > > > U can only do it on pc, not mobile
> > > 
> > > 
> > > The fnf mobile port hasn't almost the same engine and coding?
> > > So it is possible
> > 
> > 
> > u can just edit it for now
> 
> Yea but where are the .hx files?

you can't

**Comment by Rs232k** [comment]
Use PC and read tutorial
