### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by GordoiteYT** [luckydog7/Funkin-android#839]
Hey creator or random person! (sorry if im wasting your time, my apologies) i was wondering, how much RAM does FNF for mobile use? I am just wondering.

**Comment by Kris6528** [comment]
An average of 286MB and maximum usage of 2.1 - 5 GB ram[depends of hoe much longer u playing the game]

**Comment by GordoiteYT** [comment]
so can it run on my 2GB RAM phone with 32GB of storage?

> An average of 286MB and maximum usage of 2.1 - 5 GB ram[depends of hoe much longer u playing the game]

**Comment by Kris6528** [comment]
I think it's playable,but the game will have more freeze and game crash

**Comment by GordoiteYT** [comment]
oh ok

**Comment by AbujasGaming** [comment]
My phone is 2.5 ram

**Comment by GordoiteYT** [comment]
> My phone is 2.5 ram

So you have 400 mb of RAM if you play,

**Comment by GordoiteYT** [comment]
btw pico just gave me a black screen and it crashed the game (and my phone) so yeah my phone is kinda broken idk how.
