### ISSUE TITLE
FNF V.S. TABI Ex Boyfriend

### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#842]
Before that, i didn't make this mod, just port this mod into fnf android, this version will not same as pc version.
The app that i use fnf android lite sky mod
https://mega.nz/file/l4Ay1bxK#KNKHnqGrU-KvU_NXAFn8zpHaaNgjnNjQaPdofmWze14
New characters, New song, New background
Have dialogue, but No cutscreen, No voice acting
Preview:
![Screenshot_2021-05-17-18-38-19-507_com.ninjamuffin99.funkin.mod.sky.jpg](https://user-images.githubusercontent.com/81964285/118531170-2040ac80-b778-11eb-86ea-8cfe9192e71c.jpg)
![Screenshot_2021-05-18-01-27-49-500_com.ninjamuffin99.funkin.mod.tabi.jpg](https://user-images.githubusercontent.com/81964285/118531306-46664c80-b778-11eb-8a6a-1f52a93e1f0e.jpg)
[Curse]
![Screenshot_2021-05-17-18-38-37-471_com.ninjamuffin99.funkin.mod.sky.jpg](https://user-images.githubusercontent.com/81964285/118531390-5f6efd80-b778-11eb-8f7e-87067be2068d.jpg)
[Dialogue]
![Screenshot_2021-05-18-04-26-10-171_com.ninjamuffin99.funkin.mod.tabi.jpg](https://user-images.githubusercontent.com/81964285/118552285-52aad380-b791-11eb-9da2-0de67704e8d4.jpg)
[TABI]
![Screenshot_2021-05-17-23-01-01-256_com.ninjamuffin99.funkin.mod.tabi.jpg](https://user-images.githubusercontent.com/81964285/118531468-744b9100-b778-11eb-98a0-6ad2eee4b37f.jpg)
![Screenshot_2021-05-17-23-19-37-545_com.ninjamuffin99.funkin.mod.tabi.jpg](https://user-images.githubusercontent.com/81964285/118531505-7ca3cc00-b778-11eb-9196-e52c34bc4aac.jpg)

Download link
Mediafire:
(delete)
Mega:
(delete)
Google Drive:
(delete)
The mod:
https://gamebanana.com/mods/286388

That it, and also special thanks ROBIKALIVE13 to do image for good, bad and secret ending.
Peace out ✌

**Comment by ROBIKALIVE13** [comment]
YES

**Comment by ALAE1234M** [comment]
Thanks for the mod

**Comment by DanisLixo** [comment]
![Screenshot_20210519-010604](https://user-images.githubusercontent.com/58278276/118916573-a2121080-b905-11eb-8c1a-b0db824c195d.png)
bruh momento

**Comment by MrTks216** [comment]
> ![Screenshot_20210519-010604](https://user-images.githubusercontent.com/58278276/118916573-a2121080-b905-11eb-8c1a-b0db824c195d.png)
> bruh momento

what the... they already making android port, good to know lol

**Comment by hakerSALAD** [comment]
Hey can you give an link from google drive

**Comment by MrTks216** [comment]
> Hey can you give an link from google drive

here
https://drive.google.com/file/d/1-6jVIEXKzkE9rFA7eY186L9fMEK1x5Np/view?usp=drivesdk
