### ISSUE TITLE
Lite versions (shitty edition) just so you can play while Luckydog7 is sleeping on the chair and programming with his feet

### ISSUE THREAD

**Issue by DanisLixo** [luckydog7/Funkin-android#86]
funk: https://www.mediafire.com/download/znir293cd4zlcpv

Bugs:
Game crashes (sometimes)
Black texture (maybe)
Cocoa and Eggnog is not working (I'll solve it in a little while)
In the selection of weeks, the BF is all there
Im alive (Yes, this is a bug)
The BF doesn't have his Death animation (idle BF)
The train never existed
gfChristmas.png now it's in Low Quality (aaaaaaaaaa)
Added:
Your mom (not really)
Deleted:
the incredible unnecessary files

Funk Low End Phones: https://www.mediafire.com/download/2gut4lcwrm5mll5

Bugs:
game crashes (sometimes on week 4, and Cocoa and Eggnog 100%)
Black texture (rare)
I'm still alive (buuuuug)

Warning: The characters (BF, GF, Dad, Spooky kids and pico) are too small, And the GF does nothing, she just dances :|

Special Thanks:
Hadobedo (FunkiniOS): For the sprites of the Low End version.
Aura The Furry (YouTube channel): for teh Lite version of the BF.
Ninjamuffin99: For leaving the source code of the old versions still available.
Luckydog7: for the port sent it well man, keep up the good work!
Ibis Paint: Mods. 
P.S.: cara do tijolinho.

**Comment by Rs232k** [comment]
Well done! All -weeks- done without crash. That's 18 total games. In 19 crash. Ram 4gb

**Comment by Crunchyyy456** [comment]
Marry me

**Comment by Crunchyyy456** [comment]
> Marry me

But in all seriousness well done, 3 crashes (i crashed when i tried to play week 2 on easy) other than that this is perfect

**Comment by DanisLixo** [comment]
I will close this issue probably tomorrow, because this version is now outdated.

**Comment by InfernoTheGamer2479** [comment]
> I will close this issue probably tomorrow, because this version is now outdated.

Are you gonna update it soon though?

**Comment by DanisLixo** [comment]
yes, I want Boyfriend to do the death animation, but I want the image not to be so big, for the parents of week 5 I'm putting together their animations and removing some animations. already for the monster, it will do the animation, but I don't know if I will be able to leave the image between 4096x4096.

**Comment by DanisLixo** [comment]
update
