### ISSUE TITLE
FNF MEGAMIX GOOD OPTIMIZATION

### ISSUE THREAD

**Issue by arrivedercihehe** [luckydog7/Funkin-android#860]
mylazily Frankenstein'd 2 apks to get the (probably) optimal mobile Funkin sessions

features:

*all weeks have been optimized

*has not been fully turned into *VOID NIGHT FUNKIN* (there are some blank sprites but most of the stuff is intact (sadly most mod characters have been voidefied but still have the BG :)))

CREDITS:
@NeonNotFound: og optimized assets (stolen with permission ofc : ])

@woaa12: og optimization of #817

*gamerbross: making the megamix mod

@arrivedercihehe (me): lazily combined the two
neons and woaas apk

bugs: main menu lags like hell but actual gameplay doesn't so don't worry bout it
ballistic doesn't work, it just straight up crashed while loading

**update:
STRESS NOW LOADS WOOOOO (no pico or gameover animations and it's hella laggy so not recommended)
removed whitty cutscenes assets so I could readd whitty's in-game sprite

download: https://download1351.mediafire.com/y4h8bk2e0tig/4m9ybpehaly6op2/gen_signed8.apk

![Screenshot_20210519-030957](https://user-images.githubusercontent.com/84143676/118734601-cf9c8280-b84f-11eb-8bc9-29fcf98c1bff.png)
![Screenshot_20210520-111608](https://user-images.githubusercontent.com/84143676/118936213-65720380-b95d-11eb-97a1-b5001cf19d0d.png)

**Comment by NeonNotFound** [comment]
Epic

**Comment by arrivedercihehe** [comment]
btw replaced the neon mod (not the dude mentioned earlier) with the og week 6

**Comment by sonicyt1234** [comment]
You mean the old school design?

**Comment by arrivedercihehe** [comment]
> lazily Frankenstein'd 2 apks to get the (probably) optimal mobile Funkin sessions
> 
> features:
> 
> *all weeks have been optimized
> 
> *has not been fully turned into _VOID NIGHT FUNKIN_ (there are some blank sprites but most of the stuff is intact)
> 
> CREDITS:
> @NeonNotFound: og optimized assets (stolen with permission ofc : ])
> 
> @woaa12: og optimization of #817
> 
> *gamerbross: making the megamix mod
> 
> @arrivedercihehe (me): lazily combined the two
> neons and woaas apk
> 
> bugs: main menu lags like hell but actual gameplay doesn't so don't worry bout it
 stress will crash (I believe it's because of the pico shooting sprite sheet)
> 
> **update:
> removed gf and most mod character sprites
> less details on most mod weeks and weeks 3 & 7
> 
> download: https://drive.google.com/file/d/1-lu10z2WapTIvZfM5La2uuAJcA0aKODw/view?usp=drivesdk

**Comment by woaa12** [comment]
> btw replaced the neon mod (not the dude mentioned earlier) with the og week 6

okay

**Comment by woaa12** [comment]
wait but it IS og week 6 :')

**Comment by woaa12** [comment]
wait im stupid it said replaced :,,,,,,,,)

**Comment by woaa12** [comment]
i looking to add more mods and make it more liter, :))))))))

**Comment by FridayNightSans** [comment]
How abuout whitty?

**Comment by ChickenHat23** [comment]
What is megamix mod?

**Comment by ppllo** [comment]
But the icons still have the black square

**Comment by Rainbowbunn** [comment]
Can you have a version with pico shooting and gf

**Comment by FridayNightSans** [comment]
> But the icons still have the black square

Because it past 4096×4096 pixel

**Comment by arrivedercihehe** [comment]
> But the icons still have the black square

that's probably a thing with your phone since all the icons are visible for me
