### ISSUE TITLE
Hello! Can someone make a lite version of picoShooting.xml and picoShooting.png for me?

### ISSUE THREAD

**Issue by kffwlp** [luckydog7/Funkin-android#863]
I want to make a lite version of week 7 so I could play it with no black sprites but I can't make a lite version of picoShooting.xml and picoShooting.png. If anyone can, please make out for me (I think you need to modify picoShootongOffsets.txt too)

**Comment by Ralphy999** [comment]
> I want to make a lite version of week 7 so I could play it with no black sprites but I can't make a lite version of picoShooting.xml and picoShooting.png. If anyone can, please make out for me (I think you need to modify picoShootongOffsets.txt too)

Do u have gf tankman???? Lite version?

**Comment by kffwlp** [comment]
> > I want to make a lite version of week 7 so I could play it with no black sprites but I can't make a lite version of picoShooting.xml and picoShooting.png. If anyone can, please make out for me (I think you need to modify picoShootongOffsets.txt too)
> 
> Do u have gf tankman???? Lite version?

I replaced gf tankman with the gf lite assets and modified the .xml
