### ISSUE TITLE
Add weege mod pls

### ISSUE THREAD

**Issue by nsebheebsjbdn** [luckydog7/Funkin-android#874]

**Comment by nsebheebsjbdn** [comment]
Pls

**Comment by GetMonke** [comment]
Someone already posted the weegee mod. Find it in the issues tab. Please don't be lazy.

**Comment by nsebheebsjbdn** [comment]
> Someone already posted the weegee mod. Find it in the issues tab. Please don't be lazy.
> You just need to search it in the search bar in the issues tab.

Ok

**Comment by VitalieW0WKid** [comment]
I don't like people who are so lazy to search
