### ISSUE TITLE
Megamix Optimized (gamebross version) oh work :p

### ISSUE THREAD

**Issue by FridayNightSans** [luckydog7/Funkin-android#877]
Im making optimized for this now, i will done soon cause u know that. Im always make optimized before playing any fnf apk tho ;-;

And btw
At Foolhardy week then should i use Retro Remix or not?

Ok pp, no picture thiz tỉme lol

**Comment by FridayNightSans** [comment]
Fact: this place now kinda got a lot war, i should found  some chill  mod to make ;-;

**Comment by kffwlp** [comment]
> Fact: this place now kinda got a lot war, i should found  some chill  mod to make ;-;

This place is just a warzone at this point

**Comment by FridayNightSans** [comment]
> > Fact: this place now kinda got a lot war, i should found  some chill  mod to make ;-;
> 
> This place is just a warzone at this point

Yes, ima go make some chill mod

**Comment by FridayNightSans** [comment]
![Uploading image0_1-1.gif…]()
![Uploading image1.gif…]()

**Comment by bloodheroC** [comment]
Oooooo

**Comment by Justine101213k** [comment]
Oh Make Optimized

**Comment by FridayNightSans** [comment]
Damn, someone already did it. Oh well, i wont do this anymore
