### ISSUE TITLE
Just a Question:

### ISSUE THREAD

**Issue by ChickenHat23** [luckydog7/Funkin-android#879]
What is the megamix mod?

**Comment by Kaique62** [comment]
it's a lot of mods in only 1 apk

**Comment by ChickenHat23** [comment]
Oh i downloaded it and it seems that the dialogues are spanish...

Is there an english ver of the apk?

pls reference it would be appreciated ❤️

**Comment by ROBIKALIVE13** [comment]
> Oh i downloaded it and it seems that the dialogues are spanish...
> 
> Is there an english ver of the apk?
> 
> pls reference it would be appreciated ❤️

im planning to do it
