### ISSUE TITLE
What About Week 7 Source Code? 

### ISSUE THREAD

**Issue by CreatorOlixter** [luckydog7/Funkin-android#881]
I seen much People saying that the source code was released, and moch other that says that it isn't released

I'm confussed

**Comment by MrTks216** [comment]
nah, source code not release yet, here the proof https://github.com/luckydog7/Funkin-android/releases/tag/0.2.7.1-build.6

**Comment by arrivedercihehe** [comment]
I believe it was released unofficially via dataminers extracting it with inspect element

**Comment by CreatorOlixter** [comment]
Ok thanks :)
