### ISSUE TITLE
Why my fnf crashes on samsung a10

### ISSUE THREAD

**Issue by Kirill2006183** [luckydog7/Funkin-android#884]
Hello everyone, some weeks fly out and some weeks do not fly out yet when I downloaded the fnf game from a friend on a weak device, a friend went to play without leaving my friend characteristics operative memory 2GB MT6580 processor 32-bit sorry for my English

**Comment by StrawRetro** [comment]
> Hello everyone, some weeks fly out and some weeks do not fly out yet when I downloaded the fnf game from a friend on a weak device, a friend went to play without leaving my friend characteristics operative memory 2GB MT6580 processor 32-bit sorry for my English

ur ram still low, u need download LOW END version.

**Comment by Kirill2006183** [comment]
Here are my specs 2GB RAM Samsung Exynos 7 Octa processor

**Comment by Kirill2006183** [comment]
> > Hello everyone, some weeks fly out and some weeks do not fly out yet when I downloaded the fnf game from a friend on a weak device, a friend went to play without leaving my friend characteristics operative memory 2GB MT6580 processor 32-bit sorry for my English
> 
> ur ram still low, u need download LOW END version.

Here are my specs 2GB RAM Samsung Exynos 7 Octa processor

**Comment by StrawRetro** [comment]
> > > Hello everyone, some weeks fly out and some weeks do not fly out yet when I downloaded the fnf game from a friend on a weak device, a friend went to play without leaving my friend characteristics operative memory 2GB MT6580 processor 32-bit sorry for my English
> > 
> > 
> > ur ram still low, u need download LOW END version.
> 
> Here are my specs 2GB RAM Samsung Exynos 7 Octa processor

I know ur phone dude, ur ram is too low also ur processor still bad too, dont play too much fnf, u can burn mainboard

**Comment by Kirill2006183** [comment]
> > > > Hello everyone, some weeks fly out and some weeks do not fly out yet when I downloaded the fnf game from a friend on a weak device, a friend went to play without leaving my friend characteristics operative memory 2GB MT6580 processor 32-bit sorry for my English
> > > 
> > > 
> > > ur ram still low, u need download LOW END version.
> > 
> > 
> > Here are my specs 2GB RAM Samsung Exynos 7 Octa processor
> 
> I know ur phone dude, ur ram is too low also ur processor still bad too, dont play too much fnf, u can burn mainboard

Well, when I downloaded it from a friend, it started my friend on a weak android 6 phone, my friend's mt6580 processor, it started up maybe there is some restriction on the Samsung a10 from android 10

**Comment by Kirill2006183** [comment]
> > > > Hello everyone, some weeks fly out and some weeks do not fly out yet when I downloaded the fnf game from a friend on a weak device, a friend went to play without leaving my friend characteristics operative memory 2GB MT6580 processor 32-bit sorry for my English
> > > 
> > > 
> > > ur ram still low, u need download LOW END version.
> > 
> > 
> > Here are my specs 2GB RAM Samsung Exynos 7 Octa processor
> 
> I know ur phone dude, ur ram is too low also ur processor still bad too, dont play too much fnf, u can burn mainboard

Why my friend for started on the video accelerator on mail-400 it costs the mt6580 processor well, my friend also has a weak phone well, for some reason it started

**Comment by StrawRetro** [comment]
> > > > > Hello everyone, some weeks fly out and some weeks do not fly out yet when I downloaded the fnf game from a friend on a weak device, a friend went to play without leaving my friend characteristics operative memory 2GB MT6580 processor 32-bit sorry for my English
> > > > 
> > > > 
> > > > ur ram still low, u need download LOW END version.
> > > 
> > > 
> > > Here are my specs 2GB RAM Samsung Exynos 7 Octa processor
> > 
> > 
> > I know ur phone dude, ur ram is too low also ur processor still bad too, dont play too much fnf, u can burn mainboard
> 
> Why my friend for started on the video accelerator on mail-400 it costs the mt6580 processor well, my friend also has a weak phone well, for some reason it started

A series are trash dude. i have A70 its not bad bc greatest a series phone but under A50 was trash.

**Comment by Kirill2006183** [comment]
> > > > > > Hello everyone, some weeks fly out and some weeks do not fly out yet when I downloaded the fnf game from a friend on a weak device, a friend went to play without leaving my friend characteristics operative memory 2GB MT6580 processor 32-bit sorry for my English
> > > > > 
> > > > > 
> > > > > ur ram still low, u need download LOW END version.
> > > > 
> > > > 
> > > > Here are my specs 2GB RAM Samsung Exynos 7 Octa processor
> > > 
> > > 
> > > I know ur phone dude, ur ram is too low also ur processor still bad too, dont play too much fnf, u can burn mainboard
> > 
> > 
> > Why my friend for started on the video accelerator on mail-400 it costs the mt6580 processor well, my friend also has a weak phone well, for some reason it started
> 
> A series are trash dude. i have A70 its not bad bc greatest a series phone but under A50 was trash.

Even when my second friend wanted to download well, you know what model of phone Samsung a12 it costs 3GB of RAM well, equally crashes some weeks well, some Samsung model is a limitation of some I think Selinux interferes I can't turn it off

**Comment by Kirill2006183** [comment]
> > > > > > Hello everyone, some weeks fly out and some weeks do not fly out yet when I downloaded the fnf game from a friend on a weak device, a friend went to play without leaving my friend characteristics operative memory 2GB MT6580 processor 32-bit sorry for my English
> > > > > 
> > > > > 
> > > > > ur ram still low, u need download LOW END version.
> > > > 
> > > > 
> > > > Here are my specs 2GB RAM Samsung Exynos 7 Octa processor
> > > 
> > > 
> > > I know ur phone dude, ur ram is too low also ur processor still bad too, dont play too much fnf, u can burn mainboard
> > 
> > 
> > Why my friend for started on the video accelerator on mail-400 it costs the mt6580 processor well, my friend also has a weak phone well, for some reason it started
> 
> A series are trash dude. i have A70 its not bad bc greatest a series phone but under A50 was trash.

I still found that still prevents Kernel Insecure probably for this crashes

**Comment by Rs232k** [comment]
Samsung consumes more ram. That's it, no selinux errors.
