### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BayIstahsiz** [luckydog7/Funkin-android#897]
How to add new weeks ?

**Comment by georgechen1236** [comment]
https://user-images.githubusercontent.com/83620839/119098008-f7563b00-ba47-11eb-9189-0e6feaf5fdc7.mp4

**Comment by DabKnight** [comment]
> How to add new weeks ?

You need pc

**Comment by BayIstahsiz** [comment]
Oh my not needed pc sad :(
