### ISSUE TITLE
Doesn't allow me to use my own song/remix I created

### ISSUE THREAD

**Issue by PichukaPok** [luckydog7/Funkin-android#898]
I made a blammed remix from FL Studio and this happened, the song is muted and the arrows are gone, I even changed the song title to inst.ogg and that doesn't even work, even if I put the arrows it doesn't work like it's supposed to, I plan to make my own mod from this unofficial port but since this bug exist it really difficult for me to do it, so could you please fix it if you can?

**Comment by PichukaPok** [comment]
Cant upload a video, sorry somehow it doesn't work

**Comment by PichukaPok** [comment]
![Screenshot_20210521_162127](https://user-images.githubusercontent.com/81952450/119106358-dcd48f80-ba50-11eb-888d-7bc3bbfda1a6.jpg)

The arrow part I said it doesn't know what it's doing, meaning it's being glitchy it would scroll up again and again with the same note, so you cant hit any except 1

**Comment by GetMonke** [comment]
Try downloading another port and change it there. For example the "FNF B side duet"
I changed the bopeebo with another wong and it works fine for me.

**Comment by GamesGobrrrr** [comment]
Did you converted the songs/remix you made from MP3 to ogg? If no, that's why it doesn't have sound. Use a audio convert, I recommend this one  https://play.google.com/store/apps/details?id=com.blackcoderandroid.audioconverterva

**Comment by PichukaPok** [comment]
> Did you converted the songs/remix you made from MP3 to ogg? If no, that's why it doesn't have sound. Use a audio convert, I recommend this one https://play.google.com/store/apps/details?id=com.blackcoderandroid.audioconverterva

Dude thank you so much, this actually worked! I don't think this is a bug but most likely because I didn't convert it to ogg properly, like thank you so much this actually work
