### ISSUE TITLE
could you install the Tricky mod?

### ISSUE THREAD

**Issue by DekarRowe** [luckydog7/Funkin-android#90]
Recently the Tricky mod was released and I was wondering if you could install it, the mod is already installed, it just needs to be converted to an apk, maybe

**Comment by ElPeppyWall** [comment]
here is the mod for android 
[https://www.mediafire.com/file/39wnupw96vj4ipx/tricky_mod.apk/file](https://www.mediafire.com/file/39wnupw96vj4ipx/tricky_mod.apk/file)

**Comment by DekarRowe** [comment]
> here is the mod for android 
> [https://www.mediafire.com/file/39wnupw96vj4ipx/tricky_mod.apk/file](https://www.mediafire.com/file/39wnupw96vj4ipx/tricky_mod.apk/file) 

Thx, did you install it?

**Comment by ElPeppyWall** [comment]
> > here is the mod for android
> > https://www.mediafire.com/file/39wnupw96vj4ipx/tricky_mod.apk/file
> 
> Thx, did you install it?

Yes

**Comment by DekarRowe** [comment]
> > > here is the mod for android
> > > https://www.mediafire.com/file/39wnupw96vj4ipx/tricky_mod.apk/file
> > 
> > Thx, did you install it?
> 
> Yes

So, Could you install more mods for me? I will pay you, but not with money xd

**Comment by ElPeppyWall** [comment]
> > > > here is the mod for android
> > > > https://www.mediafire.com/file/39wnupw96vj4ipx/tricky_mod.apk/file
> > > 
> > > 
> > > Thx, did you install it?
> > 
> > 
> > Yes
> 
> So, Could you install more mods for me? I will pay you, but not with money xd

Sure
