### ISSUE TITLE
Can someone port the new Fnf: Mic'd Up Engine?

### ISSUE THREAD

**Issue by DabKnight** [luckydog7/Funkin-android#919]
Can someone do that?
Its this one:
https://gamebanana.com/mods/44236

**Comment by GetMonke** [comment]
Someone is already in the process of doing micd't.
![Screenshot_20210522-163814_YouTube](https://user-images.githubusercontent.com/84018856/119220232-22aa5a00-bb1c-11eb-8336-e0171446f994.jpg)

**Comment by DabKnight** [comment]
> Someone is already in the process of doing micd't.
> ![Screenshot_20210522-163814_YouTube](https://user-images.githubusercontent.com/84018856/119220232-22aa5a00-bb1c-11eb-8336-e0171446f994.jpg)

Ayo what?
N I C E

**Comment by ROBIKALIVE13** [comment]
zacks newest post about it
![IMG_20210525_191820.jpg](https://user-images.githubusercontent.com/82233686/119547078-f2b9bb80-bd94-11eb-8810-f47b5cbc2c98.jpg)

**Comment by DabKnight** [comment]
> zacks newest post about it
> ![IMG_20210525_191820.jpg](https://user-images.githubusercontent.com/82233686/119547078-f2b9bb80-bd94-11eb-8810-f47b5cbc2c98.jpg)

Yo WHAAAAAAAT

**Comment by ROBIKALIVE13** [comment]
![IMG_20210526_201130.jpg](https://user-images.githubusercontent.com/82233686/119710425-a20e9500-be5e-11eb-9937-24e9d89a6c4a.jpg)![IMG_20210526_201138.jpg](https://user-images.githubusercontent.com/82233686/119710431-a3d85880-be5e-11eb-9a10-034234f0c72d.jpg)![IMG_20210526_201000.jpg](https://user-images.githubusercontent.com/82233686/119710436-a6d34900-be5e-11eb-9071-d9bc64a90cae.jpg)
heres the last leaks
