### ISSUE TITLE
But that it make me angry

### ISSUE THREAD

**Issue by MariosGX13** [luckydog7/Funkin-android#938]
Every time i play week 5 and its time for winter horrorland (1/3 times i played) it crashes 
Specs:
Huawei mediapad t5
Ram:3gb

**Comment by GetMonke** [comment]
Ram is self explanatory

**Comment by ROBIKALIVE13** [comment]
> Every time i play week 5 and its time for winter horrorland (1/3 times i played) it crashes 
> Specs:
> Huawei mediapad t5
> Ram:3gb
> 

it can be a ram problem

**Comment by MariosGX13** [comment]
I don't think so because I run it in a 4gb ram (xiaomi redmi note 9) and it crashed again

**Comment by Rs232k** [comment]
Game uses more ram, your 4 GB is not enough, and it's stock miui, means system and system apps consumes your ram too.

**Comment by MariosGX13** [comment]
Thanks but luckydog7 pls fix this

**Comment by MariosGX13** [comment]
Thanks but pls luckydog7 fix this
