### ISSUE TITLE
Can Someone Make A Go Weegee From Weegeepie

### ISSUE THREAD

**Issue by JoseGithubFNF** [luckydog7/Funkin-android#948]
PLEASE!!!!!! PORT IT Here's The Link If You Wanna Port PORT IT PLEASE!!!!!!!! https://gamebanana.com/mods/289122

**Comment by ROBIKALIVE13** [comment]
> PLEASE!!!!!! PORT IT Here's The Link If You Wanna Port PORT IT PLEASE!!!!!!!! https://gamebanana.com/mods/289122

look first ._.

**Comment by JoseGithubFNF** [comment]
Ok

**Comment by DabKnight** [comment]
> PLEASE!!!!!! PORT IT Here's The Link If You Wanna Port PORT IT PLEASE!!!!!!!! https://gamebanana.com/mods/289122

Here lol:
https://www.mediafire.com/file/cw7w805x7b5jvev/Weegeepie.apk/file

**Comment by JoseGithubFNF** [comment]
HOLY MOLY THANK YOU SO MUCH!!!!!!!

**Comment by lolvan06** [comment]
> > PLEASE!!!!!! PORT IT Here's The Link If You Wanna Port PORT IT PLEASE!!!!!!!! https://gamebanana.com/mods/289122
> 
> Here lol:
> https://www.mediafire.com/file/cw7w805x7b5jvev/Weegeepie.apk/file

how to open mediafie it said theres a typo pare
