### ISSUE TITLE
FNF Mobile (Only Week1-7) No mod by gamerbross

### ISSUE THREAD

**Issue by MrTks216** [luckydog7/Funkin-android#949]
Gone

**Comment by ROBIKALIVE13** [comment]
why does george dislikes everything ?

**Comment by georgechen1236** [comment]
What

**Comment by DabKnight** [comment]
Nice!
I can finally play the actual vanilla with week 7 :))

**Comment by 1lemonx** [comment]
> This version fnf mobile only have tutorial, week1-7, No mod, I already deleted the mod file and unused file make less mb, loading more smoothly.
> Here the link
> Mediafire:
> https://www.mediafire.com/file/p4v1z1m78af1xnn/FNF_Tiktok_Engine_%2528only_week1-7%2529.apk/file
> The original one
> Google Drive:
> https://drive.google.com/file/d/1ArmdjXMj_0kts9ts3zblko16lsZsnJJ_/view
> 
> That all, bye lol

good god, is it a bulky package it runs pretty slow .

**Comment by DanisLixo** [comment]
I loved the fact that engine is called **Tik Tok Engine**

**Comment by DanisLixo** [comment]
I loved the fact that engine is called **Tik Tok Engine**

**Comment by HighFlyer-222** [comment]
i tried week 7... bf, gf and some of the tankmen in the background were black squares and cutscenes didn't exist, i was like "at least it's playable" until it started crashing when i try to open any song

lol

**Comment by OptimizedMaker** [comment]
> i tried week 7... bf, gf and some of the tankmen in the background were black squares and cutscenes didn't exist, i was like "at least it's playable" until it started crashing when i try to open any song
> 
> lol

#979 i Made optimized version
