### ISSUE TITLE
Can You write On the Json name?

### ISSUE THREAD

**Issue by TailsGithub** [luckydog7/Funkin-android#96]
Like how do You put Another Song name??Example:

Tutorial>>Debug Mode>>Song>>Tutorial>>Bobeepo

**Comment by TailsGithub** [comment]
![Screenshot_20210318-095332~2](https://user-images.githubusercontent.com/77502521/111656204-eb43c800-87cf-11eb-8c91-399946e479b7.png)

**Comment by TailsGithub** [comment]
> Hacker's keyboard

How

**Comment by DanisLixo** [comment]
Play store, install hackers keyboard

**Comment by TailsGithub** [comment]
And....?

**Comment by DanisLixo** [comment]
https://youtu.be/iZ777fy-0KI

**Comment by DanisLixo** [comment]
now close the issue pls.
