### ISSUE TITLE
Bug that keeps haunting me:

### ISSUE THREAD

**Issue by BoyfriendFNF** [luckydog7/Funkin-android#97]
For the love of God when will the crashing be fixed?? I wanna play Monster but it just CRASHES
THE SAME FOR OTHER SONGS AAAAAAAA

**Comment by DanisLixo** [comment]
LMAO, that's hilarious

**Comment by BoyfriendFNF** [comment]
> LMAO, that's hilarious #86

does the build have the newest version

**Comment by DanisLixo** [comment]
Fixing bugs 😎
