### ISSUE TITLE
NEED HELP MAKING A FNF MOD FOR FUN

### ISSUE THREAD

**Issue by InfernoTheGamer2479** [luckydog7/Funkin-android#971]
Yo, me and my friends are looking for help on making a fnf mod for fun! If you wanna help out, send me a friend request on Discord!

InfernoTheGamer#3657

Again, this mod is only for fun. You can add in your Oc in the mod if you like!

(P.s. Sorry if im using the Issue wrong, Its my first time. I don't do these often...)

**Comment by InfernoTheGamer2479** [comment]
If I don't accept your friend request, that means im asleep.

**Comment by gunkilock** [comment]
I just sent request

**Comment by InfernoTheGamer2479** [comment]
> I just sent request

Ight, I just woke up, I'll accept it

**Comment by CircularCircle** [comment]
I sent a request

**Comment by InfernoTheGamer2479** [comment]
> I sent a request

Ight, I accepted it!

**Comment by InfernoTheGamer2479** [comment]
> Yo, me and my friends are looking for help on making a fnf mod for fun! If you wanna help out, send me a friend request on Discord!
> 
> InfernoTheGamer#3657
> 
> Again, this mod is only for fun. You can add in your Oc in the mod if you like!
> 
> (P.s. Sorry if im using the Issue wrong, Its my first time. I don't do these often...)

My tag isn't 3657 anymore, its 6969 now cuz I recently got nitro

**Comment by InfernoTheGamer2479** [comment]
Oh, and btw, Please leave a reply here if you sent a friend request because I might get confused on who wants to help to people who just randomly found me and sent a friend request, thanks

**Comment by InfernoTheGamer2479** [comment]
Im just gonna close this issue, since people are just ignoring it, we got enough people anyway
