### ISSUE TITLE
luckydog's whitty mod

### ISSUE THREAD

**Issue by StrawRetro** [luckydog7/Funkin-android#974]
First thing i need to say about #969  IT'S NOT ORIGINAL MOD FUCKING BALLISTIC IS REMIXED AND U JUST SAYIN "whitty android mod" BUT IT'S NOT, IF U WANT TO REALASE IT FIRST THING U NEED TO SAY "ballistic remixed but sucks" CURSE U FR BC CANT CHANGE CONTROLLER TOO, IF U WANT TO SAY ENYONE TO IT WAS NOT ORIGINAL WHITTY AT ALL! INPUTS, OPTIMISE AND ETC ALL OF THEM SUCKS AND SUCKS, IF U WANT TO DO SMTHN AND MAKE US SMTHN NEW GO WORK ON FUCKING WEEK 7 NOT THIS BULLSHIT RIGHT? ALSO GIVE US NEW CONTROLLER SECTION AT ALL, WE WAITED FOR MONTHS, I SAID WAIT TO EVERYONE BUT FR I SAID THAT WORDS FOR NOTHING I GUESS? Do not download this shit if u dont have any controller like keyboard. (also immortal is too bad thoo.)

**Comment by ROBIKALIVE13** [comment]
> First thing i need to say about #969  IT'S NOT ORIGINAL MOD FUCKING BALLISTIC IS REMIXED AND U JUST SAYIN "whitty android mod" BUT IT'S NOT, IF U WANT TO REALASE IT FIRST THING U NEED TO SAY "ballistic remixed but sucks" CURSE U FR BC CANT CHANGE CONTROLLER TOO, IF U WANT TO SAY ENYONE TO IT WAS NOT ORIGINAL WHITTY AT ALL! INPUTS, OPTIMISE AND ETC ALL OF THEM SUCKS AND SUCKS, IF U WANT TO DO SMTHN AND MAKE US SMTHN NEW GO WORK ON FUCKING WEEK 7 NOT THIS BULLSHIT RIGHT? ALSO GIVE US NEW CONTROLLER SECTION AT ALL, WE WAITED FOR MONTHS, I SAID WAIT TO EVERYONE BUT FR I SAID THAT WORDS FOR NOTHING I GUESS? Do not download this shit if u dont have any controller like keyboard. (also immortal is too bad thoo.)

theres an old baklistic in the freeplay section ._.

**Comment by StrawRetro** [comment]
> > First thing i need to say about #969  IT'S NOT ORIGINAL MOD FUCKING BALLISTIC IS REMIXED AND U JUST SAYIN "whitty android mod" BUT IT'S NOT, IF U WANT TO REALASE IT FIRST THING U NEED TO SAY "ballistic remixed but sucks" CURSE U FR BC CANT CHANGE CONTROLLER TOO, IF U WANT TO SAY ENYONE TO IT WAS NOT ORIGINAL WHITTY AT ALL! INPUTS, OPTIMISE AND ETC ALL OF THEM SUCKS AND SUCKS, IF U WANT TO DO SMTHN AND MAKE US SMTHN NEW GO WORK ON FUCKING WEEK 7 NOT THIS BULLSHIT RIGHT? ALSO GIVE US NEW CONTROLLER SECTION AT ALL, WE WAITED FOR MONTHS, I SAID WAIT TO EVERYONE BUT FR I SAID THAT WORDS FOR NOTHING I GUESS? Do not download this shit if u dont have any controller like keyboard. (also immortal is too bad thoo.)
> 
> theres an old ballistic in the freeplay section ._.

maybe i want to play story mod ?

**Comment by ROBIKALIVE13** [comment]
> > > First thing i need to say about #969  IT'S NOT ORIGINAL MOD FUCKING BALLISTIC IS REMIXED AND U JUST SAYIN "whitty android mod" BUT IT'S NOT, IF U WANT TO REALASE IT FIRST THING U NEED TO SAY "ballistic remixed but sucks" CURSE U FR BC CANT CHANGE CONTROLLER TOO, IF U WANT TO SAY ENYONE TO IT WAS NOT ORIGINAL WHITTY AT ALL! INPUTS, OPTIMISE AND ETC ALL OF THEM SUCKS AND SUCKS, IF U WANT TO DO SMTHN AND MAKE US SMTHN NEW GO WORK ON FUCKING WEEK 7 NOT THIS BULLSHIT RIGHT? ALSO GIVE US NEW CONTROLLER SECTION AT ALL, WE WAITED FOR MONTHS, I SAID WAIT TO EVERYONE BUT FR I SAID THAT WORDS FOR NOTHING I GUESS? Do not download this shit if u dont have any controller like keyboard. (also immortal is too bad thoo.)
> > 
> > theres an old ballistic in the freeplay section ._.
> 
> maybe i want to play story mod ?

then play it on story then go back to freeplay or replace it ._. that easy

**Comment by ROBIKALIVE13** [comment]
> > > > First thing i need to say about #969  IT'S NOT ORIGINAL MOD FUCKING BALLISTIC IS REMIXED AND U JUST SAYIN "whitty android mod" BUT IT'S NOT, IF U WANT TO REALASE IT FIRST THING U NEED TO SAY "ballistic remixed but sucks" CURSE U FR BC CANT CHANGE CONTROLLER TOO, IF U WANT TO SAY ENYONE TO IT WAS NOT ORIGINAL WHITTY AT ALL! INPUTS, OPTIMISE AND ETC ALL OF THEM SUCKS AND SUCKS, IF U WANT TO DO SMTHN AND MAKE US SMTHN NEW GO WORK ON FUCKING WEEK 7 NOT THIS BULLSHIT RIGHT? ALSO GIVE US NEW CONTROLLER SECTION AT ALL, WE WAITED FOR MONTHS, I SAID WAIT TO EVERYONE BUT FR I SAID THAT WORDS FOR NOTHING I GUESS? Do not download this shit if u dont have any controller like keyboard. (also immortal is too bad thoo.)
> > > 
> > > theres an old ballistic in the freeplay section ._.
> > 
> > maybe i want to play story mod ?
> 
> then play it on story then go back to freeplay or replace it ._. that easy

and thats the way u thank him?

**Comment by StrawRetro** [comment]
> > > > > First thing i need to say about #969  IT'S NOT ORIGINAL MOD FUCKING BALLISTIC IS REMIXED AND U JUST SAYIN "whitty android mod" BUT IT'S NOT, IF U WANT TO REALASE IT FIRST THING U NEED TO SAY "ballistic remixed but sucks" CURSE U FR BC CANT CHANGE CONTROLLER TOO, IF U WANT TO SAY ENYONE TO IT WAS NOT ORIGINAL WHITTY AT ALL! INPUTS, OPTIMISE AND ETC ALL OF THEM SUCKS AND SUCKS, IF U WANT TO DO SMTHN AND MAKE US SMTHN NEW GO WORK ON FUCKING WEEK 7 NOT THIS BULLSHIT RIGHT? ALSO GIVE US NEW CONTROLLER SECTION AT ALL, WE WAITED FOR MONTHS, I SAID WAIT TO EVERYONE BUT FR I SAID THAT WORDS FOR NOTHING I GUESS? Do not download this shit if u dont have any controller like keyboard. (also immortal is too bad thoo.)
> > > > 
> > > > 
> > > > theres an old ballistic in the freeplay section ._.
> > > 
> > > 
> > > maybe i want to play story mod ?
> > 
> > 
> > then play it on story then go back to freeplay or replace it ._. that easy
> 
> and thats the way u thank him?

first, there is better whitty mod with other controller section, second optimise is bad too, third so many things is not works, if not works doesnt he needs to delete them?and last one fourth why he is wasting his time before he needs to make week 7?

**Comment by ArcidonYT** [comment]
> First thing i need to say about #969 IT'S NOT ORIGINAL MOD FUCKING BALLISTIC IS REMIXED AND U JUST SAYIN "whitty android mod" BUT IT'S NOT, IF U WANT TO REALASE IT FIRST THING U NEED TO SAY "ballistic remixed but sucks" CURSE U FR BC CANT CHANGE CONTROLLER TOO, IF U WANT TO SAY ENYONE TO IT WAS NOT ORIGINAL WHITTY AT ALL! INPUTS, OPTIMISE AND ETC ALL OF THEM SUCKS AND SUCKS, IF U WANT TO DO SMTHN AND MAKE US SMTHN NEW GO WORK ON FUCKING WEEK 7 NOT THIS BULLSHIT RIGHT? ALSO GIVE US NEW CONTROLLER SECTION AT ALL, WE WAITED FOR MONTHS, I SAID WAIT TO EVERYONE BUT FR I SAID THAT WORDS FOR NOTHING I GUESS? Do not download this shit if u dont have any controller like keyboard. (also immortal is too bad thoo.)

give the man a fucking break you talking like ghost now

**Comment by StrawRetro** [comment]
> > First thing i need to say about #969 IT'S NOT ORIGINAL MOD FUCKING BALLISTIC IS REMIXED AND U JUST SAYIN "whitty android mod" BUT IT'S NOT, IF U WANT TO REALASE IT FIRST THING U NEED TO SAY "ballistic remixed but sucks" CURSE U FR BC CANT CHANGE CONTROLLER TOO, IF U WANT TO SAY ENYONE TO IT WAS NOT ORIGINAL WHITTY AT ALL! INPUTS, OPTIMISE AND ETC ALL OF THEM SUCKS AND SUCKS, IF U WANT TO DO SMTHN AND MAKE US SMTHN NEW GO WORK ON FUCKING WEEK 7 NOT THIS BULLSHIT RIGHT? ALSO GIVE US NEW CONTROLLER SECTION AT ALL, WE WAITED FOR MONTHS, I SAID WAIT TO EVERYONE BUT FR I SAID THAT WORDS FOR NOTHING I GUESS? Do not download this shit if u dont have any controller like keyboard. (also immortal is too bad thoo.)
> 
> give the man a fucking break you talking like ghost now

if he wants break why woul he makes mods like this? answer me bro? im not asking to him make something, im giving opinion? whybhe made whitty mod begire week 7? also u cant answer me too right?

**Comment by MrTks216** [comment]
> > > First thing i need to say about #969 IT'S NOT ORIGINAL MOD FUCKING BALLISTIC IS REMIXED AND U JUST SAYIN "whitty android mod" BUT IT'S NOT, IF U WANT TO REALASE IT FIRST THING U NEED TO SAY "ballistic remixed but sucks" CURSE U FR BC CANT CHANGE CONTROLLER TOO, IF U WANT TO SAY ENYONE TO IT WAS NOT ORIGINAL WHITTY AT ALL! INPUTS, OPTIMISE AND ETC ALL OF THEM SUCKS AND SUCKS, IF U WANT TO DO SMTHN AND MAKE US SMTHN NEW GO WORK ON FUCKING WEEK 7 NOT THIS BULLSHIT RIGHT? ALSO GIVE US NEW CONTROLLER SECTION AT ALL, WE WAITED FOR MONTHS, I SAID WAIT TO EVERYONE BUT FR I SAID THAT WORDS FOR NOTHING I GUESS? Do not download this shit if u dont have any controller like keyboard. (also immortal is too bad thoo.)
> > 
> > give the man a fucking break you talking like ghost now
> 
> if he wants break why woul he makes mods like this? answer me bro? im not asking to him make something, im giving opinion? whybhe made whitty mod begire week 7? also u cant answer me too right?

You know the week 7 source code not yet.

**Comment by StrawRetro** [comment]
> > > > First thing i need to say about #969 IT'S NOT ORIGINAL MOD FUCKING BALLISTIC IS REMIXED AND U JUST SAYIN "whitty android mod" BUT IT'S NOT, IF U WANT TO REALASE IT FIRST THING U NEED TO SAY "ballistic remixed but sucks" CURSE U FR BC CANT CHANGE CONTROLLER TOO, IF U WANT TO SAY ENYONE TO IT WAS NOT ORIGINAL WHITTY AT ALL! INPUTS, OPTIMISE AND ETC ALL OF THEM SUCKS AND SUCKS, IF U WANT TO DO SMTHN AND MAKE US SMTHN NEW GO WORK ON FUCKING WEEK 7 NOT THIS BULLSHIT RIGHT? ALSO GIVE US NEW CONTROLLER SECTION AT ALL, WE WAITED FOR MONTHS, I SAID WAIT TO EVERYONE BUT FR I SAID THAT WORDS FOR NOTHING I GUESS? Do not download this shit if u dont have any controller like keyboard. (also immortal is too bad thoo.)
> > > 
> > > 
> > > give the man a fucking break you talking like ghost now
> > 
> > 
> > if he wants break why woul he makes mods like this? answer me bro? im not asking to him make something, im giving opinion? whybhe made whitty mod begire week 7? also u cant answer me too right?
> 
> You know the week 7 source code not yet.

BAHSJQHAHAHHAA ARE U KIDDING ME? ARE U LIVING IN CAVE OR SMTHN? SOURCE CODE OUT ALR LIKE 3 WEEKS? SRSLY ARE U LIVE IN CAVE OR SMTHN ?

**Comment by MrTks216** [comment]
> > > > > First thing i need to say about #969 IT'S NOT ORIGINAL MOD FUCKING BALLISTIC IS REMIXED AND U JUST SAYIN "whitty android mod" BUT IT'S NOT, IF U WANT TO REALASE IT FIRST THING U NEED TO SAY "ballistic remixed but sucks" CURSE U FR BC CANT CHANGE CONTROLLER TOO, IF U WANT TO SAY ENYONE TO IT WAS NOT ORIGINAL WHITTY AT ALL! INPUTS, OPTIMISE AND ETC ALL OF THEM SUCKS AND SUCKS, IF U WANT TO DO SMTHN AND MAKE US SMTHN NEW GO WORK ON FUCKING WEEK 7 NOT THIS BULLSHIT RIGHT? ALSO GIVE US NEW CONTROLLER SECTION AT ALL, WE WAITED FOR MONTHS, I SAID WAIT TO EVERYONE BUT FR I SAID THAT WORDS FOR NOTHING I GUESS? Do not download this shit if u dont have any controller like keyboard. (also immortal is too bad thoo.)
> > > > 
> > > > 
> > > > give the man a fucking break you talking like ghost now
> > > 
> > > 
> > > if he wants break why woul he makes mods like this? answer me bro? im not asking to him make something, im giving opinion? whybhe made whitty mod begire week 7? also u cant answer me too right?
> > 
> > You know the week 7 source code not yet.
> 
> BAHSJQHAHAHHAA ARE U KIDDING ME? ARE U LIVING IN CAVE OR SMTHN? SOURCE CODE OUT ALR LIKE 3 WEEKS? SRSLY ARE U LIVE IN CAVE OR SMTHN ?

https://github.com/luckydog7/Funkin-android/releases/tag/0.2.7.1-build.6
read the text that luckydog wrote about source code

**Comment by StrawRetro** [comment]
> > > > > > First thing i need to say about #969 IT'S NOT ORIGINAL MOD FUCKING BALLISTIC IS REMIXED AND U JUST SAYIN "whitty android mod" BUT IT'S NOT, IF U WANT TO REALASE IT FIRST THING U NEED TO SAY "ballistic remixed but sucks" CURSE U FR BC CANT CHANGE CONTROLLER TOO, IF U WANT TO SAY ENYONE TO IT WAS NOT ORIGINAL WHITTY AT ALL! INPUTS, OPTIMISE AND ETC ALL OF THEM SUCKS AND SUCKS, IF U WANT TO DO SMTHN AND MAKE US SMTHN NEW GO WORK ON FUCKING WEEK 7 NOT THIS BULLSHIT RIGHT? ALSO GIVE US NEW CONTROLLER SECTION AT ALL, WE WAITED FOR MONTHS, I SAID WAIT TO EVERYONE BUT FR I SAID THAT WORDS FOR NOTHING I GUESS? Do not download this shit if u dont have any controller like keyboard. (also immortal is too bad thoo.)
> > > > > 
> > > > > 
> > > > > give the man a fucking break you talking like ghost now
> > > > 
> > > > 
> > > > if he wants break why woul he makes mods like this? answer me bro? im not asking to him make something, im giving opinion? whybhe made whitty mod begire week 7? also u cant answer me too right?
> > > 
> > > 
> > > You know the week 7 source code not yet.
> > 
> > 
> > BAHSJQHAHAHHAA ARE U KIDDING ME? ARE U LIVING IN CAVE OR SMTHN? SOURCE CODE OUT ALR LIKE 3 WEEKS? SRSLY ARE U LIVE IN CAVE OR SMTHN ?
> 
> https://github.com/luckydog7/Funkin-android/releases/tag/0.2.7.1-build.6
> read the text that luckydog wrote about source code

if source code is not out yet https://www.mediafire.com/file/8svmygqd9so6wb8/FNF_MOBILE_GARCELLO_v0.5.apk/file 
wtf is this? how did he put Ugh animation, pico, bf carries gf and talking animation? just tell me bro how? lmao.

**Comment by MrTks216** [comment]
> > > > > > > First thing i need to say about #969 IT'S NOT ORIGINAL MOD FUCKING BALLISTIC IS REMIXED AND U JUST SAYIN "whitty android mod" BUT IT'S NOT, IF U WANT TO REALASE IT FIRST THING U NEED TO SAY "ballistic remixed but sucks" CURSE U FR BC CANT CHANGE CONTROLLER TOO, IF U WANT TO SAY ENYONE TO IT WAS NOT ORIGINAL WHITTY AT ALL! INPUTS, OPTIMISE AND ETC ALL OF THEM SUCKS AND SUCKS, IF U WANT TO DO SMTHN AND MAKE US SMTHN NEW GO WORK ON FUCKING WEEK 7 NOT THIS BULLSHIT RIGHT? ALSO GIVE US NEW CONTROLLER SECTION AT ALL, WE WAITED FOR MONTHS, I SAID WAIT TO EVERYONE BUT FR I SAID THAT WORDS FOR NOTHING I GUESS? Do not download this shit if u dont have any controller like keyboard. (also immortal is too bad thoo.)
> > > > > > 
> > > > > > 
> > > > > > give the man a fucking break you talking like ghost now
> > > > > 
> > > > > 
> > > > > if he wants break why woul he makes mods like this? answer me bro? im not asking to him make something, im giving opinion? whybhe made whitty mod begire week 7? also u cant answer me too right?
> > > > 
> > > > 
> > > > You know the week 7 source code not yet.
> > > 
> > > 
> > > BAHSJQHAHAHHAA ARE U KIDDING ME? ARE U LIVING IN CAVE OR SMTHN? SOURCE CODE OUT ALR LIKE 3 WEEKS? SRSLY ARE U LIVE IN CAVE OR SMTHN ?
> > 
> > https://github.com/luckydog7/Funkin-android/releases/tag/0.2.7.1-build.6
> > read the text that luckydog wrote about source code
> 
> if source code is not out yet https://www.mediafire.com/file/8svmygqd9so6wb8/FNF_MOBILE_GARCELLO_v0.5.apk/file 
> wtf is this? how did he put Ugh animation, pico, bf carries gf and talking animation? just tell me bro how? lmao.

You know these file takes from newgrounds right,
it is unofficially via dataminers extracting it with inspect element from newgrounds, and these file only have png and other stuff, that even not the source code

**Comment by ROBIKALIVE13** [comment]
and he wont do it until its officialy out (DOWNLOADABLE)

**Comment by ROBIKALIVE13** [comment]
> > > > > > > First thing i need to say about #969 IT'S NOT ORIGINAL MOD FUCKING BALLISTIC IS REMIXED AND U JUST SAYIN "whitty android mod" BUT IT'S NOT, IF U WANT TO REALASE IT FIRST THING U NEED TO SAY "ballistic remixed but sucks" CURSE U FR BC CANT CHANGE CONTROLLER TOO, IF U WANT TO SAY ENYONE TO IT WAS NOT ORIGINAL WHITTY AT ALL! INPUTS, OPTIMISE AND ETC ALL OF THEM SUCKS AND SUCKS, IF U WANT TO DO SMTHN AND MAKE US SMTHN NEW GO WORK ON FUCKING WEEK 7 NOT THIS BULLSHIT RIGHT? ALSO GIVE US NEW CONTROLLER SECTION AT ALL, WE WAITED FOR MONTHS, I SAID WAIT TO EVERYONE BUT FR I SAID THAT WORDS FOR NOTHING I GUESS? Do not download this shit if u dont have any controller like keyboard. (also immortal is too bad thoo.)
> > > > > > 
> > > > > > 
> > > > > > give the man a fucking break you talking like ghost now
> > > > > 
> > > > > 
> > > > > if he wants break why woul he makes mods like this? answer me bro? im not asking to him make something, im giving opinion? whybhe made whitty mod begire week 7? also u cant answer me too right?
> > > > 
> > > > 
> > > > You know the week 7 source code not yet.
> > > 
> > > 
> > > BAHSJQHAHAHHAA ARE U KIDDING ME? ARE U LIVING IN CAVE OR SMTHN? SOURCE CODE OUT ALR LIKE 3 WEEKS? SRSLY ARE U LIVE IN CAVE OR SMTHN ?
> > 
> > https://github.com/luckydog7/Funkin-android/releases/tag/0.2.7.1-build.6
> > read the text that luckydog wrote about source code
> 
> if source code is not out yet https://www.mediafire.com/file/8svmygqd9so6wb8/FNF_MOBILE_GARCELLO_v0.5.apk/file 
> wtf is this? how did he put Ugh animation, pico, bf carries gf and talking animation? just tell me bro how? lmao.

WHY DO U WANT TO RUSH LUCKY DOG WHEN THERES A FUNKIN APK?

**Comment by MrTks216** [comment]
> and he wont do it until its officialy out (DOWNLOADABLE)

True.

**Comment by ROBIKALIVE13** [comment]
Bc he doesn't want to get copyrighted

**Comment by RxyhanD** [comment]
> > > > > > > First thing i need to say about #969 IT'S NOT ORIGINAL MOD FUCKING BALLISTIC IS REMIXED AND U JUST SAYIN "whitty android mod" BUT IT'S NOT, IF U WANT TO REALASE IT FIRST THING U NEED TO SAY "ballistic remixed but sucks" CURSE U FR BC CANT CHANGE CONTROLLER TOO, IF U WANT TO SAY ENYONE TO IT WAS NOT ORIGINAL WHITTY AT ALL! INPUTS, OPTIMISE AND ETC ALL OF THEM SUCKS AND SUCKS, IF U WANT TO DO SMTHN AND MAKE US SMTHN NEW GO WORK ON FUCKING WEEK 7 NOT THIS BULLSHIT RIGHT? ALSO GIVE US NEW CONTROLLER SECTION AT ALL, WE WAITED FOR MONTHS, I SAID WAIT TO EVERYONE BUT FR I SAID THAT WORDS FOR NOTHING I GUESS? Do not download this shit if u dont have any controller like keyboard. (also immortal is too bad thoo.)
> > > > > > 
> > > > > > 
> > > > > > give the man a fucking break you talking like ghost now
> > > > > 
> > > > > 
> > > > > if he wants break why woul he makes mods like this? answer me bro? im not asking to him make something, im giving opinion? whybhe made whitty mod begire week 7? also u cant answer me too right?
> > > > 
> > > > 
> > > > You know the week 7 source code not yet.
> > > 
> > > 
> > > BAHSJQHAHAHHAA ARE U KIDDING ME? ARE U LIVING IN CAVE OR SMTHN? SOURCE CODE OUT ALR LIKE 3 WEEKS? SRSLY ARE U LIVE IN CAVE OR SMTHN ?
> > 
> > 
> > https://github.com/luckydog7/Funkin-android/releases/tag/0.2.7.1-build.6
> > read the text that luckydog wrote about source code
> 
> if source code is not out yet https://www.mediafire.com/file/8svmygqd9so6wb8/FNF_MOBILE_GARCELLO_v0.5.apk/file
> wtf is this? how did he put Ugh animation, pico, bf carries gf and talking animation? just tell me bro how? lmao.

lmao. you couldn't talk anymore?

**Comment by StrawRetro** [comment]
> > > > > > > > First thing i need to say about #969 IT'S NOT ORIGINAL MOD FUCKING BALLISTIC IS REMIXED AND U JUST SAYIN "whitty android mod" BUT IT'S NOT, IF U WANT TO REALASE IT FIRST THING U NEED TO SAY "ballistic remixed but sucks" CURSE U FR BC CANT CHANGE CONTROLLER TOO, IF U WANT TO SAY ENYONE TO IT WAS NOT ORIGINAL WHITTY AT ALL! INPUTS, OPTIMISE AND ETC ALL OF THEM SUCKS AND SUCKS, IF U WANT TO DO SMTHN AND MAKE US SMTHN NEW GO WORK ON FUCKING WEEK 7 NOT THIS BULLSHIT RIGHT? ALSO GIVE US NEW CONTROLLER SECTION AT ALL, WE WAITED FOR MONTHS, I SAID WAIT TO EVERYONE BUT FR I SAID THAT WORDS FOR NOTHING I GUESS? Do not download this shit if u dont have any controller like keyboard. (also immortal is too bad thoo.)
> > > > > > > 
> > > > > > > 
> > > > > > > give the man a fucking break you talking like ghost now
> > > > > > 
> > > > > > 
> > > > > > if he wants break why woul he makes mods like this? answer me bro? im not asking to him make something, im giving opinion? whybhe made whitty mod begire week 7? also u cant answer me too right?
> > > > > 
> > > > > 
> > > > > You know the week 7 source code not yet.
> > > > 
> > > > 
> > > > BAHSJQHAHAHHAA ARE U KIDDING ME? ARE U LIVING IN CAVE OR SMTHN? SOURCE CODE OUT ALR LIKE 3 WEEKS? SRSLY ARE U LIVE IN CAVE OR SMTHN ?
> > > 
> > > 
> > > https://github.com/luckydog7/Funkin-android/releases/tag/0.2.7.1-build.6
> > > read the text that luckydog wrote about source code
> > 
> > 
> > if source code is not out yet https://www.mediafire.com/file/8svmygqd9so6wb8/FNF_MOBILE_GARCELLO_v0.5.apk/file
> > wtf is this? how did he put Ugh animation, pico, bf carries gf and talking animation? just tell me bro how? lmao.
> 
> lmao. you couldn't talk anymore?

Im wasting my time with "Optimised" games like call of duty, not wasting time with you guys, lmao.

**Comment by ROBIKALIVE13** [comment]
> > > > > > > > > First thing i need to say about #969 IT'S NOT ORIGINAL MOD FUCKING BALLISTIC IS REMIXED AND U JUST SAYIN "whitty android mod" BUT IT'S NOT, IF U WANT TO REALASE IT FIRST THING U NEED TO SAY "ballistic remixed but sucks" CURSE U FR BC CANT CHANGE CONTROLLER TOO, IF U WANT TO SAY ENYONE TO IT WAS NOT ORIGINAL WHITTY AT ALL! INPUTS, OPTIMISE AND ETC ALL OF THEM SUCKS AND SUCKS, IF U WANT TO DO SMTHN AND MAKE US SMTHN NEW GO WORK ON FUCKING WEEK 7 NOT THIS BULLSHIT RIGHT? ALSO GIVE US NEW CONTROLLER SECTION AT ALL, WE WAITED FOR MONTHS, I SAID WAIT TO EVERYONE BUT FR I SAID THAT WORDS FOR NOTHING I GUESS? Do not download this shit if u dont have any controller like keyboard. (also immortal is too bad thoo.)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > give the man a fucking break you talking like ghost now
> > > > > > > 
> > > > > > > 
> > > > > > > if he wants break why woul he makes mods like this? answer me bro? im not asking to him make something, im giving opinion? whybhe made whitty mod begire week 7? also u cant answer me too right?
> > > > > > 
> > > > > > 
> > > > > > You know the week 7 source code not yet.
> > > > > 
> > > > > 
> > > > > BAHSJQHAHAHHAA ARE U KIDDING ME? ARE U LIVING IN CAVE OR SMTHN? SOURCE CODE OUT ALR LIKE 3 WEEKS? SRSLY ARE U LIVE IN CAVE OR SMTHN ?
> > > > 
> > > > 
> > > > https://github.com/luckydog7/Funkin-android/releases/tag/0.2.7.1-build.6
> > > > read the text that luckydog wrote about source code
> > > 
> > > 
> > > if source code is not out yet https://www.mediafire.com/file/8svmygqd9so6wb8/FNF_MOBILE_GARCELLO_v0.5.apk/file
> > > wtf is this? how did he put Ugh animation, pico, bf carries gf and talking animation? just tell me bro how? lmao.
> > 
> > lmao. you couldn't talk anymore?
> 
> Im wasting my time with "Optimised" games like call of duty, not wasting time with you guys, lmao.

actually we dont care about that

**Comment by HighFlyer-222** [comment]
just fucking chill already. if you don't like what luckydog is doing, then just go do it for yourself. porting a mod's songs isn't that hard, also there are tons of whitty ports out there, just google it up smh
luckydog7 really does his best for us to enjoy everything, with the cutscenes, animations etc. so it's normal that week 7 may be late and you literally just linked a ported week 7 apk, you can just use that until we get a port from luckydog??

**Comment by ArcidonYT** [comment]
> > > First thing i need to say about #969 IT'S NOT ORIGINAL MOD FUCKING BALLISTIC IS REMIXED AND U JUST SAYIN "whitty android mod" BUT IT'S NOT, IF U WANT TO REALASE IT FIRST THING U NEED TO SAY "ballistic remixed but sucks" CURSE U FR BC CANT CHANGE CONTROLLER TOO, IF U WANT TO SAY ENYONE TO IT WAS NOT ORIGINAL WHITTY AT ALL! INPUTS, OPTIMISE AND ETC ALL OF THEM SUCKS AND SUCKS, IF U WANT TO DO SMTHN AND MAKE US SMTHN NEW GO WORK ON FUCKING WEEK 7 NOT THIS BULLSHIT RIGHT? ALSO GIVE US NEW CONTROLLER SECTION AT ALL, WE WAITED FOR MONTHS, I SAID WAIT TO EVERYONE BUT FR I SAID THAT WORDS FOR NOTHING I GUESS? Do not download this shit if u dont have any controller like keyboard. (also immortal is too bad thoo.)
> > 
> > 
> > give the man a fucking break you talking like ghost now
> 
> if he wants break why would he makes mods like this? answer me bro? im not asking to him make something, im giving opinion? whybhe made whitty mod begire week 7? also u cant answer me too right?

To not make people waiting and bored
