### ISSUE TITLE
I have this problem when compiling the game

### ISSUE THREAD

**Issue by Adr3p0** [luckydog7/Funkin-android#980]
When compiling whitty's mod to use the kade engine Windows power sell throws me this warning "Array Access is not allowed on {+ length: int}" I don't know what that means I would like to port some mods to Android using kade engine. What could I do?

**Comment by Adr3p0** [comment]
:/

**Comment by luckydog7** [comment]
install haxe 4.2.2

**Comment by Adr3p0** [comment]
> install haxe 4.2.2

Thanks if it worked
