### ISSUE TITLE
Why does friday night funkin kick me out of the game it's pissing me off

### ISSUE THREAD

**Issue by toybonnie23** [luckydog7/Funkin-android#985]
**this issue has duplicates?**
Black textures - https://github.com/luckydog7/Funkin-android/issues/12 (max texture size problem)
Crash - https://github.com/luckydog7/Funkin-android/issues/10 (ram problem)

**Comment by kffwlp** [comment]
You probably have low ram

**Comment by georgechen1236** [comment]
Ayy bro you don't download low end mod 
Here: https://github.com/luckydog7/Funkin-android/releases/tag/0.2.7.1-build.6

**Comment by ROBIKALIVE13** [comment]
> Ayy bro you don't download low end mod 
> Here: https://github.com/luckydog7/Funkin-android/releases/tag/0.2.7.1-build.6

thats not a low end ._.

**Comment by toybonnie23** [comment]
Thx
