### ISSUE TITLE
Fucking low end mod deleted that now 😡

### ISSUE THREAD

**Issue by georgechen1236** [luckydog7/Funkin-android#986]
go to download luckydog7 FNF

**Comment by GetMonke** [comment]
Wat?

**Comment by georgechen1236** [comment]
> Wat?

You don't download low end mod

**Comment by GetMonke** [comment]
> > Wat?
> 
> You don't download low end mod

It makes your phone crash less. What seem s to be the problem?

**Comment by georgechen1236** [comment]
> > > Wat?
> > 
> > 
> > You don't download low end mod
> 
> It makes your phone crash less. What seem s to be the problem?

**Comment by georgechen1236** [comment]
> Hmm.



> Hmm.

Download don't low end download no black texture 

Here: https://github.com/luckydog7/Funkin-android/releases/tag/0.2.7.1-build.6

**Comment by GetMonke** [comment]
What? I can't understand your grammar.

Uhh... 
"There's no low end version"
Is that what you are trying to say?

**Comment by georgechen1236** [comment]
> What? I can't understand your grammar.
> 
> Uhh...
> "There's no low end version"
> Is that what you are trying to say?

What I trying to say

**Comment by ROBIKALIVE13** [comment]
> What? I can't understand your grammar.
> 
> Uhh... 
> "There's no low end version"
> Is that what you are trying to say?

i dont know he can speak "very understanding" sentences

**Comment by GetMonke** [comment]
> > What? I can't understand your grammar.
> > Uhh...
> > "There's no low end version"
> > Is that what you are trying to say?
> 
> What I trying to say

Advice though. Don't use explicit language. It makes you look like a child.

**Comment by ROBIKALIVE13** [comment]
> > > What? I can't understand your grammar.
> > > Uhh...
> > > "There's no low end version"
> > > Is that what you are trying to say?
> > 
> > What I trying to say
> 
> You want FNF that can run on your device but still looks the same?

idk maybe he wants low end

**Comment by GetMonke** [comment]
> > > > What? I can't understand your grammar.
> > > > Uhh...
> > > > "There's no low end version"
> > > > Is that what you are trying to say?
> > > 
> > > 
> > > What I trying to say
> > 
> > 
> > You want FNF that can run on your device but still looks the same?
> 
> idk maybe he wants low end

Maybe he's saying that "low end versions" has black texture bug. So he wants someone to optimise the latest version?

**Comment by ROBIKALIVE13** [comment]
> > > > > What? I can't understand your grammar.
> > > > > Uhh...
> > > > > "There's no low end version"
> > > > > Is that what you are trying to say?
> > > > 
> > > > 
> > > > What I trying to say
> > > 
> > > 
> > > You want FNF that can run on your device but still looks the same?
> > 
> > idk maybe he wants low end
> 
> Maybe he's saying that "low end versions" has black texture bug. So he wants someone to optimise the latest version?

can be

**Comment by GetMonke** [comment]
> > > > > > What? I can't understand your grammar.
> > > > > > Uhh...
> > > > > > "There's no low end version"
> > > > > > Is that what you are trying to say?
> > > > > 
> > > > > 
> > > > > What I trying to say
> > > > 
> > > > 
> > > > You want FNF that can run on your device but still looks the same?
> > > 
> > > 
> > > idk maybe he wants low end
> > 
> > 
> > Maybe he's saying that "low end versions" has black texture bug. So he wants someone to optimise the latest version?
> 
> can be

I still hated him for what he did on the vs bob repository.

I wanna say "bruh this is impossible lolol xD"

**Comment by georgechen1236** [comment]
Never gonna say goodbye
